export interface IconMeta {
  name: string;
  file: string;
  category: string;
  tags: string[];
}

export const ICON_LIST: IconMeta[] = [
  {
    name: "Heart",
    file: "heart-icon",
    category: "UI essentials",
    tags: ["heart","love","favorite","like"],
  },
  {
    name: "Star",
    file: "star-icon",
    category: "UI essentials",
    tags: ["star","favorite","rating"],
  },
  {
    name: "Moon",
    file: "moon-icon",
    category: "UI essentials",
    tags: ["moon","night","dark"],
  },
  {
    name: "Sun",
    file: "sun-icon",
    category: "UI essentials",
    tags: ["sun","day","light","weather"],
  },
  {
    name: "Check",
    file: "check-icon",
    category: "UI essentials",
    tags: ["check","done","success"],
  },
  {
    name: "Bookmark",
    file: "bookmark-icon",
    category: "UI essentials",
    tags: ["bookmark","save","favorite"],
  },
  {
    name: "Settings",
    file: "settings-icon",
    category: "UI essentials",
    tags: ["settings","gear","configuration"],
  },
  {
    name: "Copy",
    file: "copy-icon",
    category: "UI essentials",
    tags: ["copy","duplicate","clipboard"],
  },
  {
    name: "Send",
    file: "send-icon",
    category: "UI essentials",
    tags: ["send","message","plane","paper"],
  },
  {
    name: "Bell",
    file: "bell-icon",
    category: "UI essentials",
    tags: ["bell","notification","alert"],
  },
  {
    name: "Camera",
    file: "camera-icon",
    category: "Media",
    tags: ["camera","photo","image","lens"],
  },
  {
    name: "Coffee",
    file: "coffee-icon",
    category: "Comida",
    tags: ["coffee","cafe","drink","break"],
  },
  {
    name: "Rocket",
    file: "rocket-icon",
    category: "UI essentials",
    tags: ["rocket","launch","ship"],
  },
  {
    name: "Smartphone",
    file: "smartphone-icon",
    category: "Celular",
    tags: ["smartphone","phone","mobile","cell"],
  },
  {
    name: "Tablet",
    file: "tablet-icon",
    category: "Celular",
    tags: ["tablet","screen","device"],
  },
  {
    name: "Laptop",
    file: "laptop-icon",
    category: "Celular",
    tags: ["laptop","computer","notebook"],
  },
  {
    name: "Monitor",
    file: "monitor-icon",
    category: "Celular",
    tags: ["monitor","screen","display"],
  },
  {
    name: "Battery",
    file: "battery-icon",
    category: "Celular",
    tags: ["battery","charge","power"],
  },
  {
    name: "Battery charging",
    file: "battery-charging-icon",
    category: "Celular",
    tags: ["battery","charging","power","energy"],
  },
  {
    name: "Wifi",
    file: "wifi-icon",
    category: "Celular",
    tags: ["wifi","wireless","internet","signal"],
  },
  {
    name: "Bluetooth",
    file: "bluetooth-icon",
    category: "Celular",
    tags: ["bluetooth","wireless","connect"],
  },
  {
    name: "Signal",
    file: "signal-icon",
    category: "Celular",
    tags: ["signal","antenna","bars","network"],
  },
  {
    name: "Phone",
    file: "phone-icon",
    category: "Celular",
    tags: ["phone","call","telephone"],
  },
  {
    name: "Code",
    file: "code-icon",
    category: "Desarrollo",
    tags: ["code","coding","developer","programming"],
  },
  {
    name: "Terminal",
    file: "terminal-icon",
    category: "Desarrollo",
    tags: ["terminal","console","command","shell"],
  },
  {
    name: "Git branch",
    file: "git-branch-icon",
    category: "Desarrollo",
    tags: ["git","branch","version","control"],
  },
  {
    name: "Database",
    file: "database-icon",
    category: "Desarrollo",
    tags: ["database","data","storage"],
  },
  {
    name: "Server",
    file: "server-icon",
    category: "Desarrollo",
    tags: ["server","hosting","backend"],
  },
  {
    name: "CPU",
    file: "cpu-icon",
    category: "Desarrollo",
    tags: ["cpu","chip","processor","hardware"],
  },
  {
    name: "File code",
    file: "file-code-icon",
    category: "Desarrollo",
    tags: ["file","code","source","programming"],
  },
  {
    name: "Languages",
    file: "languages-icon",
    category: "Desarrollo",
    tags: ["languages","translate","code","i18n"],
  },
  {
    name: "Calculator",
    file: "calculator-icon",
    category: "Desarrollo",
    tags: ["calculator","math","numbers"],
  },
  {
    name: "Bug",
    file: "bug-icon",
    category: "Desarrollo",
    tags: ["bug","insect","error","debug"],
  },
  {
    name: "Pizza",
    file: "pizza-icon",
    category: "Comida",
    tags: ["pizza","food","italian"],
  },
  {
    name: "Beer",
    file: "beer-icon",
    category: "Comida",
    tags: ["beer","drink","bar"],
  },
  {
    name: "Donut",
    file: "donut-icon",
    category: "Comida",
    tags: ["donut","doughnut","sweet","dessert"],
  },
  {
    name: "Ice cream",
    file: "ice-cream-bowl-icon",
    category: "Comida",
    tags: ["ice","cream","dessert","sweet"],
  },
  {
    name: "Cake",
    file: "cake-icon",
    category: "Comida",
    tags: ["cake","dessert","birthday"],
  },
  {
    name: "Apple",
    file: "apple-icon",
    category: "Comida",
    tags: ["apple","fruit","healthy"],
  },
  {
    name: "Sandwich",
    file: "sandwich-icon",
    category: "Comida",
    tags: ["sandwich","food","lunch"],
  },
  {
    name: "Utensils",
    file: "utensils-icon",
    category: "Comida",
    tags: ["utensils","fork","knife","eat","food"],
  },
  {
    name: "Croissant",
    file: "croissant-icon",
    category: "Comida",
    tags: ["croissant","bread","breakfast","pastry"],
  },
  {
    name: "Popcorn",
    file: "popcorn-icon",
    category: "Comida",
    tags: ["popcorn","movie","snack"],
  },
  {
    name: "Cloud",
    file: "cloud-icon",
    category: "Clima",
    tags: ["cloud","weather","sky"],
  },
  {
    name: "Cloud rain",
    file: "cloud-rain-icon",
    category: "Clima",
    tags: ["cloud","rain","weather","water"],
  },
  {
    name: "Cloud snow",
    file: "cloud-snow-icon",
    category: "Clima",
    tags: ["cloud","snow","winter","cold"],
  },
  {
    name: "Lightning",
    file: "cloud-lightning-icon",
    category: "Clima",
    tags: ["lightning","storm","thunder","cloud"],
  },
  {
    name: "Cloud sun",
    file: "cloud-sun-icon",
    category: "Clima",
    tags: ["cloud","sun","weather","partly"],
  },
  {
    name: "Snowflake",
    file: "snowflake-icon",
    category: "Clima",
    tags: ["snowflake","snow","winter","cold"],
  },
  {
    name: "Wind",
    file: "wind-icon",
    category: "Clima",
    tags: ["wind","air","weather","breeze"],
  },
  {
    name: "Umbrella",
    file: "umbrella-icon",
    category: "Clima",
    tags: ["umbrella","rain","protection"],
  },
  {
    name: "Rainbow",
    file: "rainbow-icon",
    category: "Clima",
    tags: ["rainbow","colors","sky","rain"],
  },
  {
    name: "Tornado",
    file: "tornado-icon",
    category: "Clima",
    tags: ["tornado","wind","storm","spin"],
  },
  {
    name: "Music",
    file: "music-icon",
    category: "Música",
    tags: ["music","note","song"],
  },
  {
    name: "Music note",
    file: "music-2-icon",
    category: "Música",
    tags: ["music","note","song"],
  },
  {
    name: "Headphones",
    file: "headphones-icon",
    category: "Música",
    tags: ["headphones","audio","listen","music"],
  },
  {
    name: "Mic",
    file: "mic-icon",
    category: "Música",
    tags: ["mic","microphone","voice","record"],
  },
  {
    name: "Play",
    file: "play-icon",
    category: "Música",
    tags: ["play","video","music","media"],
  },
  {
    name: "Pause",
    file: "pause-icon",
    category: "Música",
    tags: ["pause","video","music","media"],
  },
  {
    name: "Volume",
    file: "volume-2-icon",
    category: "Música",
    tags: ["volume","sound","loud","audio"],
  },
  {
    name: "Clapperboard",
    file: "clapperboard-icon",
    category: "Música",
    tags: ["clapperboard","film","movie","action"],
  },
  {
    name: "Gamepad",
    file: "gamepad-icon",
    category: "Música",
    tags: ["gamepad","controller","gaming","play"],
  },
  {
    name: "Film",
    file: "film-icon",
    category: "Música",
    tags: ["film","movie","video","reel"],
  },
  {
    name: "Plane",
    file: "plane-icon",
    category: "Viajes",
    tags: ["plane","airplane","travel","flight"],
  },
  {
    name: "Car",
    file: "car-icon",
    category: "Viajes",
    tags: ["car","vehicle","travel","drive"],
  },
  {
    name: "Bus",
    file: "bus-icon",
    category: "Viajes",
    tags: ["bus","vehicle","transport"],
  },
  {
    name: "Ship",
    file: "ship-icon",
    category: "Viajes",
    tags: ["ship","boat","sea","travel"],
  },
  {
    name: "Compass",
    file: "compass-icon",
    category: "Viajes",
    tags: ["compass","direction","navigate","travel"],
  },
  {
    name: "Map",
    file: "map-icon",
    category: "Viajes",
    tags: ["map","travel","navigation"],
  },
  {
    name: "Navigation",
    file: "navigation-icon",
    category: "Viajes",
    tags: ["navigation","gps","direction","arrow"],
  },
  {
    name: "Map pin",
    file: "map-pin-icon",
    category: "Viajes",
    tags: ["pin","location","map","address"],
  },
  {
    name: "Ticket",
    file: "ticket-icon",
    category: "Viajes",
    tags: ["ticket","entrance","event"],
  },
  {
    name: "Anchor",
    file: "anchor-icon",
    category: "Viajes",
    tags: ["anchor","ship","sea","marine"],
  },
  {
    name: "Home",
    file: "house-icon",
    category: "Hogar",
    tags: ["home","house","living"],
  },
  {
    name: "Lamp",
    file: "lamp-icon",
    category: "Hogar",
    tags: ["lamp","light","desk"],
  },
  {
    name: "Sofa",
    file: "sofa-icon",
    category: "Hogar",
    tags: ["sofa","couch","furniture","living"],
  },
  {
    name: "Bed",
    file: "bed-icon",
    category: "Hogar",
    tags: ["bed","sleep","rest"],
  },
  {
    name: "Lightbulb",
    file: "lightbulb-icon",
    category: "Hogar",
    tags: ["lightbulb","idea","light"],
  },
  {
    name: "TV",
    file: "tv-icon",
    category: "Hogar",
    tags: ["tv","television","screen"],
  },
  {
    name: "Keyboard",
    file: "keyboard-icon",
    category: "Hogar",
    tags: ["keyboard","type","key","input"],
  },
  {
    name: "Printer",
    file: "printer-icon",
    category: "Hogar",
    tags: ["printer","print","paper"],
  },
  {
    name: "Thermometer",
    file: "thermometer-icon",
    category: "Hogar",
    tags: ["thermometer","temperature","hot"],
  },
  {
    name: "Washing machine",
    file: "washing-machine-icon",
    category: "Hogar",
    tags: ["washing","machine","laundry","clean"],
  },
  {
    name: "Dollar",
    file: "dollar-sign-icon",
    category: "Negocios",
    tags: ["dollar","money","currency","cash"],
  },
  {
    name: "Bitcoin",
    file: "bitcoin-icon",
    category: "Negocios",
    tags: ["bitcoin","crypto","money","currency"],
  },
  {
    name: "Credit card",
    file: "credit-card-icon",
    category: "Negocios",
    tags: ["card","credit","payment","money"],
  },
  {
    name: "Wallet",
    file: "wallet-icon",
    category: "Negocios",
    tags: ["wallet","money","payment"],
  },
  {
    name: "Tag",
    file: "tag-icon",
    category: "Negocios",
    tags: ["tag","label","price","sale"],
  },
  {
    name: "Receipt",
    file: "receipt-icon",
    category: "Negocios",
    tags: ["receipt","invoice","bill","shop"],
  },
  {
    name: "Shopping cart",
    file: "shopping-cart-icon",
    category: "Negocios",
    tags: ["cart","shopping","buy","store"],
  },
  {
    name: "Trending up",
    file: "trending-up-icon",
    category: "Negocios",
    tags: ["trending","up","growth","chart"],
  },
  {
    name: "Pie chart",
    file: "chart-pie-icon",
    category: "Negocios",
    tags: ["pie","chart","stats","data"],
  },
  {
    name: "Coins",
    file: "coins-icon",
    category: "Negocios",
    tags: ["coins","money","currency","cash"],
  },
  {
    name: "Trophy",
    file: "trophy-icon",
    category: "Deportes",
    tags: ["trophy","award","winner","prize"],
  },
  {
    name: "Medal",
    file: "medal-icon",
    category: "Deportes",
    tags: ["medal","award","winner","olympics"],
  },
  {
    name: "Target",
    file: "target-icon",
    category: "Deportes",
    tags: ["target","goal","aim","shoot"],
  },
  {
    name: "Gift",
    file: "gift-icon",
    category: "Deportes",
    tags: ["gift","present","birthday","reward"],
  },
  {
    name: "Sparkle",
    file: "sparkle-icon",
    category: "Deportes",
    tags: ["sparkle","shine","glow","star"],
  },
  {
    name: "Palette",
    file: "palette-icon",
    category: "Deportes",
    tags: ["palette","colors","art","design"],
  },
  {
    name: "Gem",
    file: "gem-icon",
    category: "Deportes",
    tags: ["gem","diamond","jewel","premium"],
  },
  {
    name: "Arrow up",
    file: "arrow-up-icon",
    category: "Flechas",
    tags: ["arrow","up","direction","navigation"],
  },
  {
    name: "Arrow down",
    file: "arrow-down-icon",
    category: "Flechas",
    tags: ["arrow","down","direction","navigation"],
  },
  {
    name: "Arrow right",
    file: "arrow-right-icon",
    category: "Flechas",
    tags: ["arrow","right","direction","navigation"],
  },
  {
    name: "Arrow left",
    file: "arrow-left-icon",
    category: "Flechas",
    tags: ["arrow","left","direction","navigation"],
  },
  {
    name: "Arrow up right",
    file: "arrow-up-right-icon",
    category: "Flechas",
    tags: ["arrow","diagonal","direction"],
  },
  {
    name: "Arrow down left",
    file: "arrow-down-left-icon",
    category: "Flechas",
    tags: ["arrow","diagonal","direction"],
  },
  {
    name: "Arrow left right",
    file: "arrow-left-right-icon",
    category: "Flechas",
    tags: ["arrow","swap","exchange","between"],
  },
  {
    name: "Arrow up down",
    file: "arrow-up-down-icon",
    category: "Flechas",
    tags: ["arrow","swap","vertical","between"],
  },
  {
    name: "Arrow down to line",
    file: "arrow-down-to-line-icon",
    category: "Flechas",
    tags: ["arrow","download","inbox","bottom"],
  },
  {
    name: "Arrow up from line",
    file: "arrow-up-from-line-icon",
    category: "Flechas",
    tags: ["arrow","upload","outbox","top"],
  },
  {
    name: "Clock",
    file: "clock-icon",
    category: "Tiempo",
    tags: ["clock","time","hour","watch"],
  },
  {
    name: "Alarm clock",
    file: "alarm-clock-icon",
    category: "Tiempo",
    tags: ["alarm","clock","wake","time"],
  },
  {
    name: "Timer",
    file: "timer-icon",
    category: "Tiempo",
    tags: ["timer","time","stopwatch","countdown"],
  },
  {
    name: "Hourglass",
    file: "hourglass-icon",
    category: "Tiempo",
    tags: ["hourglass","time","sand","wait"],
  },
  {
    name: "Watch",
    file: "watch-icon",
    category: "Tiempo",
    tags: ["watch","time","clock","wearable"],
  },
  {
    name: "Clock",
    file: "clock-3-icon",
    category: "Tiempo",
    tags: ["clock","time","hour","watch","3"],
  },
  {
    name: "Calendar",
    file: "calendar-icon",
    category: "Tiempo",
    tags: ["calendar","date","event","schedule"],
  },
  {
    name: "Calendar days",
    file: "calendar-days-icon",
    category: "Tiempo",
    tags: ["calendar","date","days","schedule"],
  },
  {
    name: "Calendar check",
    file: "calendar-check-icon",
    category: "Tiempo",
    tags: ["calendar","check","done","event"],
  },
  {
    name: "Timer reset",
    file: "timer-reset-icon",
    category: "Tiempo",
    tags: ["timer","reset","restart","reload"],
  },
  {
    name: "Mail",
    file: "mail-icon",
    category: "Comunicación",
    tags: ["mail","email","message","letter"],
  },
  {
    name: "Message circle",
    file: "message-circle-icon",
    category: "Comunicación",
    tags: ["message","chat","talk","bubble"],
  },
  {
    name: "Message square",
    file: "message-square-icon",
    category: "Comunicación",
    tags: ["message","chat","talk","bubble"],
  },
  {
    name: "Message more",
    file: "message-circle-more-icon",
    category: "Comunicación",
    tags: ["message","chat","more","bubble"],
  },
  {
    name: "Message text",
    file: "message-square-text-icon",
    category: "Comunicación",
    tags: ["message","chat","text","bubble"],
  },
  {
    name: "Message dot",
    file: "message-square-dot-icon",
    category: "Comunicación",
    tags: ["message","chat","dot","notification"],
  },
  {
    name: "Message plus",
    file: "message-square-plus-icon",
    category: "Comunicación",
    tags: ["message","chat","add","new"],
  },
  {
    name: "Voicemail",
    file: "voicemail-icon",
    category: "Comunicación",
    tags: ["voicemail","voice","audio","message"],
  },
  {
    name: "Mail plus",
    file: "mail-plus-icon",
    category: "Comunicación",
    tags: ["mail","email","add","compose"],
  },
  {
    name: "At sign",
    file: "at-sign-icon",
    category: "Comunicación",
    tags: ["at","mention","email","signal"],
  },
  {
    name: "Chart line",
    file: "chart-line-icon",
    category: "Gráficas",
    tags: ["chart","line","graph","stats"],
  },
  {
    name: "Chart spline",
    file: "chart-spline-icon",
    category: "Gráficas",
    tags: ["chart","spline","curved","stats"],
  },
  {
    name: "Chart column",
    file: "chart-column-icon",
    category: "Gráficas",
    tags: ["chart","bar","column","stats"],
  },
  {
    name: "Chart column big",
    file: "chart-column-big-icon",
    category: "Gráficas",
    tags: ["chart","bar","column","stats"],
  },
  {
    name: "Chart area",
    file: "chart-area-icon",
    category: "Gráficas",
    tags: ["chart","area","fill","stats"],
  },
  {
    name: "Chart bar",
    file: "chart-bar-big-icon",
    category: "Gráficas",
    tags: ["chart","bar","horizontal","stats"],
  },
  {
    name: "Chart combined",
    file: "chart-no-axes-combined-icon",
    category: "Gráficas",
    tags: ["chart","combined","line","bar"],
  },
  {
    name: "Chart columns",
    file: "chart-no-axes-column-icon",
    category: "Gráficas",
    tags: ["chart","columns","bar","stats"],
  },
  {
    name: "Chart scatter",
    file: "chart-scatter-icon",
    category: "Gráficas",
    tags: ["chart","scatter","dots","stats"],
  },
  {
    name: "Chart gantt",
    file: "chart-no-axes-gantt-icon",
    category: "Gráficas",
    tags: ["chart","gantt","timeline","project"],
  },
  {
    name: "Locate fixed",
    file: "locate-fixed-icon",
    category: "Mapas",
    tags: ["locate","position","gps","pin"],
  },
  {
    name: "Map pin off",
    file: "map-pin-off-icon",
    category: "Mapas",
    tags: ["map","pin","off","location"],
  },
  {
    name: "Map pinned",
    file: "map-pinned-icon",
    category: "Mapas",
    tags: ["map","pin","location","save"],
  },
  {
    name: "Navigation",
    file: "navigation-2-icon",
    category: "Mapas",
    tags: ["navigation","gps","direction","compass"],
  },
  {
    name: "Navigation off",
    file: "navigation-off-icon",
    category: "Mapas",
    tags: ["navigation","gps","off","direction"],
  },
  {
    name: "Crosshair",
    file: "crosshair-icon",
    category: "Mapas",
    tags: ["crosshair","aim","target","center"],
  },
  {
    name: "Route",
    file: "route-icon",
    category: "Mapas",
    tags: ["route","path","travel","journey"],
  },
  {
    name: "Signpost",
    file: "signpost-big-icon",
    category: "Mapas",
    tags: ["signpost","direction","street","guide"],
  },
  {
    name: "Earth",
    file: "earth-icon",
    category: "Mapas",
    tags: ["earth","globe","world","planet"],
  },
  {
    name: "Globe",
    file: "globe-icon",
    category: "Mapas",
    tags: ["globe","world","web","global"],
  },
  {
    name: "File text",
    file: "file-text-icon",
    category: "Oficina",
    tags: ["file","document","text","report"],
  },
  {
    name: "File plus",
    file: "file-plus-icon",
    category: "Oficina",
    tags: ["file","document","add","new"],
  },
  {
    name: "File check",
    file: "file-check-icon",
    category: "Oficina",
    tags: ["file","document","check","done"],
  },
  {
    name: "File search",
    file: "file-search-icon",
    category: "Oficina",
    tags: ["file","search","find","document"],
  },
  {
    name: "Folder",
    file: "folder-icon",
    category: "Oficina",
    tags: ["folder","directory","files"],
  },
  {
    name: "Folder open",
    file: "folder-open-icon",
    category: "Oficina",
    tags: ["folder","open","directory","files"],
  },
  {
    name: "Clipboard paste",
    file: "clipboard-paste-icon",
    category: "Oficina",
    tags: ["clipboard","paste","copy","document"],
  },
  {
    name: "Clipboard check",
    file: "clipboard-check-icon",
    category: "Oficina",
    tags: ["clipboard","check","done","task"],
  },
  {
    name: "Pencil",
    file: "pencil-icon",
    category: "Oficina",
    tags: ["pencil","write","edit","draw"],
  },
  {
    name: "Glasses",
    file: "glasses-icon",
    category: "Oficina",
    tags: ["glasses","spectacles","vision","read"],
  },
  {
    name: "Laptop",
    file: "laptop-minimal-icon",
    category: "Dispositivos",
    tags: ["laptop","computer","notebook"],
  },
  {
    name: "Mouse",
    file: "mouse-icon",
    category: "Dispositivos",
    tags: ["mouse","pointer","computer","input"],
  },
  {
    name: "Gamepad",
    file: "gamepad-2-icon",
    category: "Dispositivos",
    tags: ["gamepad","controller","gaming","play"],
  },
  {
    name: "Keyboard music",
    file: "keyboard-music-icon",
    category: "Dispositivos",
    tags: ["keyboard","music","piano","keys"],
  },
  {
    name: "Webcam",
    file: "webcam-icon",
    category: "Dispositivos",
    tags: ["webcam","camera","video","stream"],
  },
  {
    name: "Hard drive",
    file: "hard-drive-icon",
    category: "Dispositivos",
    tags: ["hard","drive","storage","disk"],
  },
  {
    name: "USB",
    file: "usb-icon",
    category: "Dispositivos",
    tags: ["usb","connect","cable","port"],
  },
  {
    name: "Phone call",
    file: "phone-call-icon",
    category: "Dispositivos",
    tags: ["phone","call","ring","talk"],
  },
  {
    name: "Microphone",
    file: "mic-vocal-icon",
    category: "Dispositivos",
    tags: ["mic","microphone","voice","record"],
  },
  {
    name: "Router",
    file: "router-icon",
    category: "Dispositivos",
    tags: ["router","network","wifi","internet"],
  },
  {
    name: "Image",
    file: "image-icon",
    category: "Multimedia",
    tags: ["image","picture","photo","graphic"],
  },
  {
    name: "Image plus",
    file: "image-plus-icon",
    category: "Multimedia",
    tags: ["image","picture","add","photo"],
  },
  {
    name: "Image upload",
    file: "image-up-icon",
    category: "Multimedia",
    tags: ["image","upload","share","picture"],
  },
  {
    name: "Image download",
    file: "image-down-icon",
    category: "Multimedia",
    tags: ["image","download","save","picture"],
  },
  {
    name: "Video",
    file: "video-icon",
    category: "Multimedia",
    tags: ["video","camera","record","movie"],
  },
  {
    name: "Video off",
    file: "video-off-icon",
    category: "Multimedia",
    tags: ["video","off","muted","camera"],
  },
  {
    name: "Videotape",
    file: "videotape-icon",
    category: "Multimedia",
    tags: ["videotape","vhs","tape","vintage"],
  },
  {
    name: "Aperture",
    file: "aperture-icon",
    category: "Multimedia",
    tags: ["aperture","camera","lens","photo"],
  },
  {
    name: "Images",
    file: "images-icon",
    category: "Multimedia",
    tags: ["images","photos","gallery","pictures"],
  },
  {
    name: "Image play",
    file: "image-play-icon",
    category: "Multimedia",
    tags: ["image","video","play","picture"],
  },
  {
    name: "Shopping bag",
    file: "shopping-bag-icon",
    category: "Comercio",
    tags: ["bag","shopping","buy","store"],
  },
  {
    name: "Shopping basket",
    file: "shopping-basket-icon",
    category: "Comercio",
    tags: ["basket","shopping","buy","store"],
  },
  {
    name: "Store",
    file: "store-icon",
    category: "Comercio",
    tags: ["store","shop","market","commerce"],
  },
  {
    name: "Hand coins",
    file: "hand-coins-icon",
    category: "Finanzas",
    tags: ["hand","coins","money","cash"],
  },
  {
    name: "Piggy bank",
    file: "piggy-bank-icon",
    category: "Finanzas",
    tags: ["piggy","bank","savings","money"],
  },
  {
    name: "Vault",
    file: "vault-icon",
    category: "Finanzas",
    tags: ["vault","safe","bank","secure"],
  },
  {
    name: "Dollar circle",
    file: "circle-dollar-sign-icon",
    category: "Finanzas",
    tags: ["dollar","money","currency","coin"],
  },
  {
    name: "Euro circle",
    file: "circle-euro-icon",
    category: "Finanzas",
    tags: ["euro","money","currency","coin"],
  },
  {
    name: "Candlestick chart",
    file: "chart-candlestick-icon",
    category: "Finanzas",
    tags: ["candlestick","chart","stocks","finance"],
  },
  {
    name: "Trending down",
    file: "trending-down-icon",
    category: "Finanzas",
    tags: ["trending","down","decrease","chart"],
  },
  {
    name: "Dice 1",
    file: "dice-1-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 2",
    file: "dice-2-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 3",
    file: "dice-3-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 4",
    file: "dice-4-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 5",
    file: "dice-5-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Sword",
    file: "sword-icon",
    category: "Juegos",
    tags: ["sword","blade","knight","weapon"],
  },
  {
    name: "Swords",
    file: "swords-icon",
    category: "Juegos",
    tags: ["swords","cross","battle","war"],
  },
  {
    name: "Shield",
    file: "shield-icon",
    category: "Juegos",
    tags: ["shield","defense","protect","guard"],
  },
  {
    name: "Shield half",
    file: "shield-half-icon",
    category: "Juegos",
    tags: ["shield","defense","half","protect"],
  },
  {
    name: "Castle",
    file: "castle-icon",
    category: "Juegos",
    tags: ["castle","fort","king","chess"],
  },
];

export function getIconCount(): number {
  return ICON_LIST.length;
}

export function getFeaturedIcons(limit = 5): IconMeta[] {
  return ICON_LIST.slice(-limit).reverse();
}

export function getCategories(): string[] {
  return Array.from(new Set(ICON_LIST.map((icon) => icon.category)));
}
