export interface IconMeta {
  name: string;
  file: string;
  category: string;
  tags: string[];
}

export const ICON_LIST: IconMeta[] = [
  {
    name: "Heart",
    file: "heart-icon",
    category: "UI essentials",
    tags: ["heart","love","favorite","like"],
  },
  {
    name: "Star",
    file: "star-icon",
    category: "UI essentials",
    tags: ["star","favorite","rating"],
  },
  {
    name: "Moon",
    file: "moon-icon",
    category: "UI essentials",
    tags: ["moon","night","dark"],
  },
  {
    name: "Sun",
    file: "sun-icon",
    category: "UI essentials",
    tags: ["sun","day","light","weather"],
  },
  {
    name: "Check",
    file: "check-icon",
    category: "UI essentials",
    tags: ["check","done","success"],
  },
  {
    name: "Bookmark",
    file: "bookmark-icon",
    category: "UI essentials",
    tags: ["bookmark","save","favorite"],
  },
  {
    name: "Settings",
    file: "settings-icon",
    category: "UI essentials",
    tags: ["settings","gear","configuration"],
  },
  {
    name: "Copy",
    file: "copy-icon",
    category: "UI essentials",
    tags: ["copy","duplicate","clipboard"],
  },
  {
    name: "Send",
    file: "send-icon",
    category: "UI essentials",
    tags: ["send","message","plane","paper"],
  },
  {
    name: "Bell",
    file: "bell-icon",
    category: "UI essentials",
    tags: ["bell","notification","alert"],
  },
  {
    name: "Camera",
    file: "camera-icon",
    category: "Media",
    tags: ["camera","photo","image","lens"],
  },
  {
    name: "Coffee",
    file: "coffee-icon",
    category: "Comida",
    tags: ["coffee","cafe","drink","break"],
  },
  {
    name: "Rocket",
    file: "rocket-icon",
    category: "UI essentials",
    tags: ["rocket","launch","ship"],
  },
  {
    name: "Smartphone",
    file: "smartphone-icon",
    category: "Celular",
    tags: ["smartphone","phone","mobile","cell"],
  },
  {
    name: "Tablet",
    file: "tablet-icon",
    category: "Celular",
    tags: ["tablet","screen","device"],
  },
  {
    name: "Laptop",
    file: "laptop-icon",
    category: "Celular",
    tags: ["laptop","computer","notebook"],
  },
  {
    name: "Monitor",
    file: "monitor-icon",
    category: "Celular",
    tags: ["monitor","screen","display"],
  },
  {
    name: "Battery",
    file: "battery-icon",
    category: "Celular",
    tags: ["battery","charge","power"],
  },
  {
    name: "Battery charging",
    file: "battery-charging-icon",
    category: "Celular",
    tags: ["battery","charging","power","energy"],
  },
  {
    name: "Wifi",
    file: "wifi-icon",
    category: "Celular",
    tags: ["wifi","wireless","internet","signal"],
  },
  {
    name: "Bluetooth",
    file: "bluetooth-icon",
    category: "Celular",
    tags: ["bluetooth","wireless","connect"],
  },
  {
    name: "Signal",
    file: "signal-icon",
    category: "Celular",
    tags: ["signal","antenna","bars","network"],
  },
  {
    name: "Phone",
    file: "phone-icon",
    category: "Celular",
    tags: ["phone","call","telephone"],
  },
  {
    name: "Code",
    file: "code-icon",
    category: "Desarrollo",
    tags: ["code","coding","developer","programming"],
  },
  {
    name: "Terminal",
    file: "terminal-icon",
    category: "Desarrollo",
    tags: ["terminal","console","command","shell"],
  },
  {
    name: "Git branch",
    file: "git-branch-icon",
    category: "Desarrollo",
    tags: ["git","branch","version","control"],
  },
  {
    name: "Database",
    file: "database-icon",
    category: "Desarrollo",
    tags: ["database","data","storage"],
  },
  {
    name: "Server",
    file: "server-icon",
    category: "Desarrollo",
    tags: ["server","hosting","backend"],
  },
  {
    name: "CPU",
    file: "cpu-icon",
    category: "Desarrollo",
    tags: ["cpu","chip","processor","hardware"],
  },
  {
    name: "File code",
    file: "file-code-icon",
    category: "Desarrollo",
    tags: ["file","code","source","programming"],
  },
  {
    name: "Languages",
    file: "languages-icon",
    category: "Desarrollo",
    tags: ["languages","translate","code","i18n"],
  },
  {
    name: "Calculator",
    file: "calculator-icon",
    category: "Desarrollo",
    tags: ["calculator","math","numbers"],
  },
  {
    name: "Bug",
    file: "bug-icon",
    category: "Desarrollo",
    tags: ["bug","insect","error","debug"],
  },
  {
    name: "Pizza",
    file: "pizza-icon",
    category: "Comida",
    tags: ["pizza","food","italian"],
  },
  {
    name: "Beer",
    file: "beer-icon",
    category: "Comida",
    tags: ["beer","drink","bar"],
  },
  {
    name: "Donut",
    file: "donut-icon",
    category: "Comida",
    tags: ["donut","doughnut","sweet","dessert"],
  },
  {
    name: "Ice cream",
    file: "ice-cream-bowl-icon",
    category: "Comida",
    tags: ["ice","cream","dessert","sweet"],
  },
  {
    name: "Cake",
    file: "cake-icon",
    category: "Comida",
    tags: ["cake","dessert","birthday"],
  },
  {
    name: "Apple",
    file: "apple-icon",
    category: "Comida",
    tags: ["apple","fruit","healthy"],
  },
  {
    name: "Sandwich",
    file: "sandwich-icon",
    category: "Comida",
    tags: ["sandwich","food","lunch"],
  },
  {
    name: "Utensils",
    file: "utensils-icon",
    category: "Comida",
    tags: ["utensils","fork","knife","eat","food"],
  },
  {
    name: "Cherry",
    file: "cherry-icon",
    category: "Comida",
    tags: ["cherry","fruit","sweet"],
  },
  {
    name: "Salad",
    file: "salad-icon",
    category: "Comida",
    tags: ["salad","vegetables","healthy","food"],
  },
  {
    name: "Croissant",
    file: "croissant-icon",
    category: "Comida",
    tags: ["croissant","bread","breakfast"],
  },
  {
    name: "Fish",
    file: "fish-icon",
    category: "Comida",
    tags: ["fish","seafood","food"],
  },
  {
    name: "Carrot",
    file: "carrot-icon",
    category: "Comida",
    tags: ["carrot","vegetable","healthy","rabbit"],
  },
  {
    name: "Hamburger",
    file: "hamburger-icon",
    category: "Comida",
    tags: ["hamburger","burger","fast food","food"],
  },
  {
    name: "Drumstick",
    file: "drumstick-icon",
    category: "Comida",
    tags: ["drumstick","chicken","food","meat"],
  },
  {
    name: "Popcorn",
    file: "popcorn-icon",
    category: "Comida",
    tags: ["popcorn","movie","snack"],
  },
  {
    name: "Cloud",
    file: "cloud-icon",
    category: "Clima",
    tags: ["cloud","weather","sky"],
  },
  {
    name: "Cloud rain",
    file: "cloud-rain-icon",
    category: "Clima",
    tags: ["cloud","rain","weather","water"],
  },
  {
    name: "Cloud snow",
    file: "cloud-snow-icon",
    category: "Clima",
    tags: ["cloud","snow","winter","cold"],
  },
  {
    name: "Lightning",
    file: "cloud-lightning-icon",
    category: "Clima",
    tags: ["lightning","storm","thunder","cloud"],
  },
  {
    name: "Cloud sun",
    file: "cloud-sun-icon",
    category: "Clima",
    tags: ["cloud","sun","weather","partly"],
  },
  {
    name: "Snowflake",
    file: "snowflake-icon",
    category: "Clima",
    tags: ["snowflake","snow","winter","cold"],
  },
  {
    name: "Wind",
    file: "wind-icon",
    category: "Clima",
    tags: ["wind","air","weather","breeze"],
  },
  {
    name: "Umbrella",
    file: "umbrella-icon",
    category: "Clima",
    tags: ["umbrella","rain","protection"],
  },
  {
    name: "Rainbow",
    file: "rainbow-icon",
    category: "Clima",
    tags: ["rainbow","colors","sky","rain"],
  },
  {
    name: "Tornado",
    file: "tornado-icon",
    category: "Clima",
    tags: ["tornado","wind","storm","spin"],
  },
  {
    name: "Music",
    file: "music-icon",
    category: "Música",
    tags: ["music","note","song"],
  },
  {
    name: "Music note",
    file: "music-2-icon",
    category: "Música",
    tags: ["music","note","song"],
  },
  {
    name: "Headphones",
    file: "headphones-icon",
    category: "Música",
    tags: ["headphones","audio","listen","music"],
  },
  {
    name: "Mic",
    file: "mic-icon",
    category: "Música",
    tags: ["mic","microphone","voice","record"],
  },
  {
    name: "Play",
    file: "play-icon",
    category: "Música",
    tags: ["play","video","music","media"],
  },
  {
    name: "Pause",
    file: "pause-icon",
    category: "Música",
    tags: ["pause","video","music","media"],
  },
  {
    name: "Volume",
    file: "volume-2-icon",
    category: "Música",
    tags: ["volume","sound","loud","audio"],
  },
  {
    name: "Clapperboard",
    file: "clapperboard-icon",
    category: "Música",
    tags: ["clapperboard","film","movie","action"],
  },
  {
    name: "Gamepad",
    file: "gamepad-icon",
    category: "Música",
    tags: ["gamepad","controller","gaming","play"],
  },
  {
    name: "Film",
    file: "film-icon",
    category: "Música",
    tags: ["film","movie","video","reel"],
  },
  {
    name: "Plane",
    file: "plane-icon",
    category: "Viajes",
    tags: ["plane","airplane","travel","flight"],
  },
  {
    name: "Car",
    file: "car-icon",
    category: "Viajes",
    tags: ["car","vehicle","travel","drive"],
  },
  {
    name: "Bus",
    file: "bus-icon",
    category: "Viajes",
    tags: ["bus","vehicle","transport"],
  },
  {
    name: "Ship",
    file: "ship-icon",
    category: "Viajes",
    tags: ["ship","boat","sea","travel"],
  },
  {
    name: "Compass",
    file: "compass-icon",
    category: "Viajes",
    tags: ["compass","direction","navigate","travel"],
  },
  {
    name: "Map",
    file: "map-icon",
    category: "Viajes",
    tags: ["map","travel","navigation"],
  },
  {
    name: "Navigation",
    file: "navigation-icon",
    category: "Viajes",
    tags: ["navigation","gps","direction","arrow"],
  },
  {
    name: "Map pin",
    file: "map-pin-icon",
    category: "Viajes",
    tags: ["pin","location","map","address"],
  },
  {
    name: "Ticket",
    file: "ticket-icon",
    category: "Viajes",
    tags: ["ticket","entrance","event"],
  },
  {
    name: "Anchor",
    file: "anchor-icon",
    category: "Viajes",
    tags: ["anchor","ship","sea","marine"],
  },
  {
    name: "Home",
    file: "house-icon",
    category: "Hogar",
    tags: ["home","house","living"],
  },
  {
    name: "Lamp",
    file: "lamp-icon",
    category: "Hogar",
    tags: ["lamp","light","desk"],
  },
  {
    name: "Sofa",
    file: "sofa-icon",
    category: "Hogar",
    tags: ["sofa","couch","furniture","living"],
  },
  {
    name: "Bed",
    file: "bed-icon",
    category: "Hogar",
    tags: ["bed","sleep","rest"],
  },
  {
    name: "Lightbulb",
    file: "lightbulb-icon",
    category: "Hogar",
    tags: ["lightbulb","idea","light"],
  },
  {
    name: "TV",
    file: "tv-icon",
    category: "Hogar",
    tags: ["tv","television","screen"],
  },
  {
    name: "Keyboard",
    file: "keyboard-icon",
    category: "Hogar",
    tags: ["keyboard","type","key","input"],
  },
  {
    name: "Printer",
    file: "printer-icon",
    category: "Hogar",
    tags: ["printer","print","paper"],
  },
  {
    name: "Thermometer",
    file: "thermometer-icon",
    category: "Hogar",
    tags: ["thermometer","temperature","hot"],
  },
  {
    name: "Washing machine",
    file: "washing-machine-icon",
    category: "Hogar",
    tags: ["washing","machine","laundry","clean"],
  },
  {
    name: "Dollar",
    file: "dollar-sign-icon",
    category: "Negocios",
    tags: ["dollar","money","currency","cash"],
  },
  {
    name: "Bitcoin",
    file: "bitcoin-icon",
    category: "Negocios",
    tags: ["bitcoin","crypto","money","currency"],
  },
  {
    name: "Credit card",
    file: "credit-card-icon",
    category: "Negocios",
    tags: ["card","credit","payment","money"],
  },
  {
    name: "Wallet",
    file: "wallet-icon",
    category: "Negocios",
    tags: ["wallet","money","payment"],
  },
  {
    name: "Tag",
    file: "tag-icon",
    category: "Negocios",
    tags: ["tag","label","price","sale"],
  },
  {
    name: "Receipt",
    file: "receipt-icon",
    category: "Negocios",
    tags: ["receipt","invoice","bill","shop"],
  },
  {
    name: "Shopping cart",
    file: "shopping-cart-icon",
    category: "Negocios",
    tags: ["cart","shopping","buy","store"],
  },
  {
    name: "Trending up",
    file: "trending-up-icon",
    category: "Negocios",
    tags: ["trending","up","growth","chart"],
  },
  {
    name: "Pie chart",
    file: "chart-pie-icon",
    category: "Negocios",
    tags: ["pie","chart","stats","data"],
  },
  {
    name: "Coins",
    file: "coins-icon",
    category: "Negocios",
    tags: ["coins","money","currency","cash"],
  },
  {
    name: "Trophy",
    file: "trophy-icon",
    category: "Deportes",
    tags: ["trophy","award","winner","prize"],
  },
  {
    name: "Medal",
    file: "medal-icon",
    category: "Deportes",
    tags: ["medal","award","winner","olympics"],
  },
  {
    name: "Target",
    file: "target-icon",
    category: "Deportes",
    tags: ["target","goal","aim","shoot"],
  },
  {
    name: "Gift",
    file: "gift-icon",
    category: "Deportes",
    tags: ["gift","present","birthday","reward"],
  },
  {
    name: "Sparkle",
    file: "sparkle-icon",
    category: "Deportes",
    tags: ["sparkle","shine","glow","star"],
  },
  {
    name: "Palette",
    file: "palette-icon",
    category: "Deportes",
    tags: ["palette","colors","art","design"],
  },
  {
    name: "Gem",
    file: "gem-icon",
    category: "Deportes",
    tags: ["gem","diamond","jewel","premium"],
  },
  {
    name: "Arrow up",
    file: "arrow-up-icon",
    category: "Flechas",
    tags: ["arrow","up","direction","navigation"],
  },
  {
    name: "Arrow down",
    file: "arrow-down-icon",
    category: "Flechas",
    tags: ["arrow","down","direction","navigation"],
  },
  {
    name: "Arrow right",
    file: "arrow-right-icon",
    category: "Flechas",
    tags: ["arrow","right","direction","navigation"],
  },
  {
    name: "Arrow left",
    file: "arrow-left-icon",
    category: "Flechas",
    tags: ["arrow","left","direction","navigation"],
  },
  {
    name: "Arrow up right",
    file: "arrow-up-right-icon",
    category: "Flechas",
    tags: ["arrow","diagonal","direction"],
  },
  {
    name: "Arrow down left",
    file: "arrow-down-left-icon",
    category: "Flechas",
    tags: ["arrow","diagonal","direction"],
  },
  {
    name: "Arrow left right",
    file: "arrow-left-right-icon",
    category: "Flechas",
    tags: ["arrow","swap","exchange","between"],
  },
  {
    name: "Arrow up down",
    file: "arrow-up-down-icon",
    category: "Flechas",
    tags: ["arrow","swap","vertical","between"],
  },
  {
    name: "Arrow down to line",
    file: "arrow-down-to-line-icon",
    category: "Flechas",
    tags: ["arrow","download","inbox","bottom"],
  },
  {
    name: "Arrow up from line",
    file: "arrow-up-from-line-icon",
    category: "Flechas",
    tags: ["arrow","upload","outbox","top"],
  },
  {
    name: "Clock",
    file: "clock-icon",
    category: "Tiempo",
    tags: ["clock","time","hour","watch"],
  },
  {
    name: "Alarm clock",
    file: "alarm-clock-icon",
    category: "Tiempo",
    tags: ["alarm","clock","wake","time"],
  },
  {
    name: "Timer",
    file: "timer-icon",
    category: "Tiempo",
    tags: ["timer","time","stopwatch","countdown"],
  },
  {
    name: "Hourglass",
    file: "hourglass-icon",
    category: "Tiempo",
    tags: ["hourglass","time","sand","wait"],
  },
  {
    name: "Watch",
    file: "watch-icon",
    category: "Tiempo",
    tags: ["watch","time","clock","wearable"],
  },
  {
    name: "Clock",
    file: "clock-3-icon",
    category: "Tiempo",
    tags: ["clock","time","hour","watch","3"],
  },
  {
    name: "Calendar",
    file: "calendar-icon",
    category: "Tiempo",
    tags: ["calendar","date","event","schedule"],
  },
  {
    name: "Calendar days",
    file: "calendar-days-icon",
    category: "Tiempo",
    tags: ["calendar","date","days","schedule"],
  },
  {
    name: "Calendar check",
    file: "calendar-check-icon",
    category: "Tiempo",
    tags: ["calendar","check","done","event"],
  },
  {
    name: "Timer reset",
    file: "timer-reset-icon",
    category: "Tiempo",
    tags: ["timer","reset","restart","reload"],
  },
  {
    name: "Mail",
    file: "mail-icon",
    category: "Comunicación",
    tags: ["mail","email","message","letter"],
  },
  {
    name: "Message circle",
    file: "message-circle-icon",
    category: "Comunicación",
    tags: ["message","chat","talk","bubble"],
  },
  {
    name: "Message square",
    file: "message-square-icon",
    category: "Comunicación",
    tags: ["message","chat","talk","bubble"],
  },
  {
    name: "Message more",
    file: "message-circle-more-icon",
    category: "Comunicación",
    tags: ["message","chat","more","bubble"],
  },
  {
    name: "Message text",
    file: "message-square-text-icon",
    category: "Comunicación",
    tags: ["message","chat","text","bubble"],
  },
  {
    name: "Message dot",
    file: "message-square-dot-icon",
    category: "Comunicación",
    tags: ["message","chat","dot","notification"],
  },
  {
    name: "Message plus",
    file: "message-square-plus-icon",
    category: "Comunicación",
    tags: ["message","chat","add","new"],
  },
  {
    name: "Voicemail",
    file: "voicemail-icon",
    category: "Comunicación",
    tags: ["voicemail","voice","audio","message"],
  },
  {
    name: "Mail plus",
    file: "mail-plus-icon",
    category: "Comunicación",
    tags: ["mail","email","add","compose"],
  },
  {
    name: "At sign",
    file: "at-sign-icon",
    category: "Comunicación",
    tags: ["at","mention","email","signal"],
  },
  {
    name: "Chart line",
    file: "chart-line-icon",
    category: "Gráficas",
    tags: ["chart","line","graph","stats"],
  },
  {
    name: "Chart spline",
    file: "chart-spline-icon",
    category: "Gráficas",
    tags: ["chart","spline","curved","stats"],
  },
  {
    name: "Chart column",
    file: "chart-column-icon",
    category: "Gráficas",
    tags: ["chart","bar","column","stats"],
  },
  {
    name: "Chart column big",
    file: "chart-column-big-icon",
    category: "Gráficas",
    tags: ["chart","bar","column","stats"],
  },
  {
    name: "Chart area",
    file: "chart-area-icon",
    category: "Gráficas",
    tags: ["chart","area","fill","stats"],
  },
  {
    name: "Chart bar",
    file: "chart-bar-big-icon",
    category: "Gráficas",
    tags: ["chart","bar","horizontal","stats"],
  },
  {
    name: "Chart combined",
    file: "chart-no-axes-combined-icon",
    category: "Gráficas",
    tags: ["chart","combined","line","bar"],
  },
  {
    name: "Chart columns",
    file: "chart-no-axes-column-icon",
    category: "Gráficas",
    tags: ["chart","columns","bar","stats"],
  },
  {
    name: "Chart scatter",
    file: "chart-scatter-icon",
    category: "Gráficas",
    tags: ["chart","scatter","dots","stats"],
  },
  {
    name: "Chart gantt",
    file: "chart-no-axes-gantt-icon",
    category: "Gráficas",
    tags: ["chart","gantt","timeline","project"],
  },
  {
    name: "Locate fixed",
    file: "locate-fixed-icon",
    category: "Mapas",
    tags: ["locate","position","gps","pin"],
  },
  {
    name: "Map pin off",
    file: "map-pin-off-icon",
    category: "Mapas",
    tags: ["map","pin","off","location"],
  },
  {
    name: "Map pinned",
    file: "map-pinned-icon",
    category: "Mapas",
    tags: ["map","pin","location","save"],
  },
  {
    name: "Navigation",
    file: "navigation-2-icon",
    category: "Mapas",
    tags: ["navigation","gps","direction","compass"],
  },
  {
    name: "Navigation off",
    file: "navigation-off-icon",
    category: "Mapas",
    tags: ["navigation","gps","off","direction"],
  },
  {
    name: "Crosshair",
    file: "crosshair-icon",
    category: "Mapas",
    tags: ["crosshair","aim","target","center"],
  },
  {
    name: "Route",
    file: "route-icon",
    category: "Mapas",
    tags: ["route","path","travel","journey"],
  },
  {
    name: "Signpost",
    file: "signpost-big-icon",
    category: "Mapas",
    tags: ["signpost","direction","street","guide"],
  },
  {
    name: "Earth",
    file: "earth-icon",
    category: "Mapas",
    tags: ["earth","globe","world","planet"],
  },
  {
    name: "Globe",
    file: "globe-icon",
    category: "Mapas",
    tags: ["globe","world","web","global"],
  },
  {
    name: "File text",
    file: "file-text-icon",
    category: "Oficina",
    tags: ["file","document","text","report"],
  },
  {
    name: "File plus",
    file: "file-plus-icon",
    category: "Oficina",
    tags: ["file","document","add","new"],
  },
  {
    name: "File check",
    file: "file-check-icon",
    category: "Oficina",
    tags: ["file","document","check","done"],
  },
  {
    name: "File search",
    file: "file-search-icon",
    category: "Oficina",
    tags: ["file","search","find","document"],
  },
  {
    name: "Folder",
    file: "folder-icon",
    category: "Oficina",
    tags: ["folder","directory","files"],
  },
  {
    name: "Folder open",
    file: "folder-open-icon",
    category: "Oficina",
    tags: ["folder","open","directory","files"],
  },
  {
    name: "Clipboard paste",
    file: "clipboard-paste-icon",
    category: "Oficina",
    tags: ["clipboard","paste","copy","document"],
  },
  {
    name: "Clipboard check",
    file: "clipboard-check-icon",
    category: "Oficina",
    tags: ["clipboard","check","done","task"],
  },
  {
    name: "Pencil",
    file: "pencil-icon",
    category: "Oficina",
    tags: ["pencil","write","edit","draw"],
  },
  {
    name: "Glasses",
    file: "glasses-icon",
    category: "Oficina",
    tags: ["glasses","spectacles","vision","read"],
  },
  {
    name: "Laptop",
    file: "laptop-minimal-icon",
    category: "Dispositivos",
    tags: ["laptop","computer","notebook"],
  },
  {
    name: "Mouse",
    file: "mouse-icon",
    category: "Dispositivos",
    tags: ["mouse","pointer","computer","input"],
  },
  {
    name: "Gamepad",
    file: "gamepad-2-icon",
    category: "Dispositivos",
    tags: ["gamepad","controller","gaming","play"],
  },
  {
    name: "Keyboard music",
    file: "keyboard-music-icon",
    category: "Dispositivos",
    tags: ["keyboard","music","piano","keys"],
  },
  {
    name: "Webcam",
    file: "webcam-icon",
    category: "Dispositivos",
    tags: ["webcam","camera","video","stream"],
  },
  {
    name: "Hard drive",
    file: "hard-drive-icon",
    category: "Dispositivos",
    tags: ["hard","drive","storage","disk"],
  },
  {
    name: "USB",
    file: "usb-icon",
    category: "Dispositivos",
    tags: ["usb","connect","cable","port"],
  },
  {
    name: "Phone call",
    file: "phone-call-icon",
    category: "Dispositivos",
    tags: ["phone","call","ring","talk"],
  },
  {
    name: "Microphone",
    file: "mic-vocal-icon",
    category: "Dispositivos",
    tags: ["mic","microphone","voice","record"],
  },
  {
    name: "Router",
    file: "router-icon",
    category: "Dispositivos",
    tags: ["router","network","wifi","internet"],
  },
  {
    name: "Image",
    file: "image-icon",
    category: "Multimedia",
    tags: ["image","picture","photo","graphic"],
  },
  {
    name: "Image plus",
    file: "image-plus-icon",
    category: "Multimedia",
    tags: ["image","picture","add","photo"],
  },
  {
    name: "Image upload",
    file: "image-up-icon",
    category: "Multimedia",
    tags: ["image","upload","share","picture"],
  },
  {
    name: "Image download",
    file: "image-down-icon",
    category: "Multimedia",
    tags: ["image","download","save","picture"],
  },
  {
    name: "Video",
    file: "video-icon",
    category: "Multimedia",
    tags: ["video","camera","record","movie"],
  },
  {
    name: "Video off",
    file: "video-off-icon",
    category: "Multimedia",
    tags: ["video","off","muted","camera"],
  },
  {
    name: "Videotape",
    file: "videotape-icon",
    category: "Multimedia",
    tags: ["videotape","vhs","tape","vintage"],
  },
  {
    name: "Aperture",
    file: "aperture-icon",
    category: "Multimedia",
    tags: ["aperture","camera","lens","photo"],
  },
  {
    name: "Images",
    file: "images-icon",
    category: "Multimedia",
    tags: ["images","photos","gallery","pictures"],
  },
  {
    name: "Image play",
    file: "image-play-icon",
    category: "Multimedia",
    tags: ["image","video","play","picture"],
  },
  {
    name: "Shopping bag",
    file: "shopping-bag-icon",
    category: "Comercio",
    tags: ["bag","shopping","buy","store"],
  },
  {
    name: "Shopping basket",
    file: "shopping-basket-icon",
    category: "Comercio",
    tags: ["basket","shopping","buy","store"],
  },
  {
    name: "Store",
    file: "store-icon",
    category: "Comercio",
    tags: ["store","shop","market","commerce"],
  },
  {
    name: "Hand coins",
    file: "hand-coins-icon",
    category: "Finanzas",
    tags: ["hand","coins","money","cash"],
  },
  {
    name: "Piggy bank",
    file: "piggy-bank-icon",
    category: "Finanzas",
    tags: ["piggy","bank","savings","money"],
  },
  {
    name: "Vault",
    file: "vault-icon",
    category: "Finanzas",
    tags: ["vault","safe","bank","secure"],
  },
  {
    name: "Dollar circle",
    file: "circle-dollar-sign-icon",
    category: "Finanzas",
    tags: ["dollar","money","currency","coin"],
  },
  {
    name: "Euro circle",
    file: "circle-euro-icon",
    category: "Finanzas",
    tags: ["euro","money","currency","coin"],
  },
  {
    name: "Candlestick chart",
    file: "chart-candlestick-icon",
    category: "Finanzas",
    tags: ["candlestick","chart","stocks","finance"],
  },
  {
    name: "Trending down",
    file: "trending-down-icon",
    category: "Finanzas",
    tags: ["trending","down","decrease","chart"],
  },
  {
    name: "Dice 1",
    file: "dice-1-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 2",
    file: "dice-2-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 3",
    file: "dice-3-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 4",
    file: "dice-4-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Dice 5",
    file: "dice-5-icon",
    category: "Juegos",
    tags: ["dice","game","random","luck"],
  },
  {
    name: "Sword",
    file: "sword-icon",
    category: "Juegos",
    tags: ["sword","blade","knight","weapon"],
  },
  {
    name: "Swords",
    file: "swords-icon",
    category: "Juegos",
    tags: ["swords","cross","battle","war"],
  },
  {
    name: "Shield",
    file: "shield-icon",
    category: "Juegos",
    tags: ["shield","defense","protect","guard"],
  },
  {
    name: "Shield half",
    file: "shield-half-icon",
    category: "Juegos",
    tags: ["shield","defense","half","protect"],
  },
  {
    name: "Castle",
    file: "castle-icon",
    category: "Juegos",
    tags: ["castle","fort","king","chess"],
  },
  {
    name: "Heart pulse",
    file: "heart-pulse-icon",
    category: "Salud",
    tags: ["heart","pulse","heartbeat","health"],
  },
  {
    name: "Stethoscope",
    file: "stethoscope-icon",
    category: "Salud",
    tags: ["stethoscope","doctor","medical","health"],
  },
  {
    name: "Activity",
    file: "activity-icon",
    category: "Salud",
    tags: ["activity","pulse","heartbeat","ecg"],
  },
  {
    name: "Pill",
    file: "pill-icon",
    category: "Salud",
    tags: ["pill","medicine","pharma","drug"],
  },
  {
    name: "Biohazard",
    file: "biohazard-icon",
    category: "Salud",
    tags: ["biohazard","danger","bio","waste"],
  },
  {
    name: "Bone",
    file: "bone-icon",
    category: "Salud",
    tags: ["bone","skeleton","doctor","pet"],
  },
  {
    name: "Syringe",
    file: "syringe-icon",
    category: "Salud",
    tags: ["syringe","needle","injection","vaccine"],
  },
  {
    name: "DNA",
    file: "dna-icon",
    category: "Salud",
    tags: ["dna","genetics","biology","helix"],
  },
  {
    name: "Baby",
    file: "baby-icon",
    category: "Salud",
    tags: ["baby","newborn","child","infant"],
  },
  {
    name: "Bandage",
    file: "bandage-icon",
    category: "Salud",
    tags: ["bandage","wound","plaster","medical"],
  },
  {
    name: "Tree pine",
    file: "tree-pine-icon",
    category: "Naturaleza",
    tags: ["tree","pine","forest","nature"],
  },
  {
    name: "Tree deciduous",
    file: "tree-deciduous-icon",
    category: "Naturaleza",
    tags: ["tree","deciduous","forest","nature"],
  },
  {
    name: "Flower",
    file: "flower-2-icon",
    category: "Naturaleza",
    tags: ["flower","blossom","nature","spring"],
  },
  {
    name: "Leaf",
    file: "leaf-icon",
    category: "Naturaleza",
    tags: ["leaf","nature","green","plant"],
  },
  {
    name: "Mountain snow",
    file: "mountain-snow-icon",
    category: "Naturaleza",
    tags: ["mountain","snow","peak","alps"],
  },
  {
    name: "Mountain",
    file: "mountain-icon",
    category: "Naturaleza",
    tags: ["mountain","hill","peak","nature"],
  },
  {
    name: "Sun moon",
    file: "sun-moon-icon",
    category: "Naturaleza",
    tags: ["sun","moon","day","night"],
  },
  {
    name: "Cloud fog",
    file: "cloud-fog-icon",
    category: "Clima",
    tags: ["fog","cloud","mist","weather"],
  },
  {
    name: "Sprout",
    file: "sprout-icon",
    category: "Naturaleza",
    tags: ["sprout","plant","grow","spring"],
  },
  {
    name: "Cloudy",
    file: "cloudy-icon",
    category: "Clima",
    tags: ["cloudy","cloud","weather","overcast"],
  },
  {
    name: "Train",
    file: "train-front-icon",
    category: "Viajes",
    tags: ["train","rail","transport","station"],
  },
  {
    name: "Tram",
    file: "tram-front-icon",
    category: "Viajes",
    tags: ["tram","streetcar","transport","city"],
  },
  {
    name: "Bus",
    file: "bus-front-icon",
    category: "Viajes",
    tags: ["bus","transport","vehicle"],
  },
  {
    name: "Sailboat",
    file: "sailboat-icon",
    category: "Viajes",
    tags: ["sailboat","boat","sail","sea"],
  },
  {
    name: "Tent",
    file: "tent-icon",
    category: "Viajes",
    tags: ["tent","camping","glamping","outdoor"],
  },
  {
    name: "Bike",
    file: "bike-icon",
    category: "Viajes",
    tags: ["bike","bicycle","cycle","ride"],
  },
  {
    name: "Life buoy",
    file: "life-buoy-icon",
    category: "Viajes",
    tags: ["buoy","life","rescue","sea"],
  },
  {
    name: "Luggage",
    file: "luggage-icon",
    category: "Viajes",
    tags: ["luggage","suitcase","bag","travel"],
  },
  {
    name: "Car front",
    file: "car-front-icon",
    category: "Viajes",
    tags: ["car","front","vehicle","drive"],
  },
  {
    name: "Train track",
    file: "train-track-icon",
    category: "Viajes",
    tags: ["train","track","rail","railway"],
  },
  {
    name: "Lock",
    file: "lock-icon",
    category: "Seguridad",
    tags: ["lock","secure","password","protected"],
  },
  {
    name: "Lock keyhole",
    file: "lock-keyhole-icon",
    category: "Seguridad",
    tags: ["lock","keyhole","secure","private"],
  },
  {
    name: "Lock open",
    file: "lock-keyhole-open-icon",
    category: "Seguridad",
    tags: ["lock","open","unlock","secure"],
  },
  {
    name: "Key round",
    file: "key-round-icon",
    category: "Seguridad",
    tags: ["key","round","password","access"],
  },
  {
    name: "Key square",
    file: "key-square-icon",
    category: "Seguridad",
    tags: ["key","square","password","access"],
  },
  {
    name: "Shield check",
    file: "shield-check-icon",
    category: "Seguridad",
    tags: ["shield","check","secure","verified"],
  },
  {
    name: "Shield alert",
    file: "shield-alert-icon",
    category: "Seguridad",
    tags: ["shield","alert","warning","danger"],
  },
  {
    name: "Radar",
    file: "radar-icon",
    category: "Seguridad",
    tags: ["radar","scan","detect","sonar"],
  },
  {
    name: "Scan face",
    file: "scan-face-icon",
    category: "Seguridad",
    tags: ["scan","face","id","biometric"],
  },
  {
    name: "Fingerprint",
    file: "fingerprint-pattern-icon",
    category: "Seguridad",
    tags: ["fingerprint","biometric","identity","touch"],
  },
  {
    name: "User",
    file: "user-round-icon",
    category: "Usuarios",
    tags: ["user","person","profile","account"],
  },
  {
    name: "User plus",
    file: "user-round-plus-icon",
    category: "Usuarios",
    tags: ["user","add","invite","person"],
  },
  {
    name: "User check",
    file: "user-round-check-icon",
    category: "Usuarios",
    tags: ["user","check","verified","person"],
  },
  {
    name: "User search",
    file: "user-round-search-icon",
    category: "Usuarios",
    tags: ["user","search","find","person"],
  },
  {
    name: "Users",
    file: "users-round-icon",
    category: "Usuarios",
    tags: ["users","people","team","group"],
  },
  {
    name: "User plus",
    file: "user-plus-icon",
    category: "Usuarios",
    tags: ["user","add","invite","person"],
  },
  {
    name: "User check",
    file: "user-check-icon",
    category: "Usuarios",
    tags: ["user","check","verified","approve"],
  },
  {
    name: "User search",
    file: "user-search-icon",
    category: "Usuarios",
    tags: ["user","search","find","person"],
  },
  {
    name: "Contact",
    file: "contact-round-icon",
    category: "Usuarios",
    tags: ["contact","user","person","avatar"],
  },
  {
    name: "User remove",
    file: "user-round-x-icon",
    category: "Usuarios",
    tags: ["user","remove","delete","person"],
  },
  {
    name: "Shapes",
    file: "shapes-icon",
    category: "Diseño",
    tags: ["shapes","geometry","design","forms"],
  },
  {
    name: "Pen tool",
    file: "pen-tool-icon",
    category: "Diseño",
    tags: ["pen","tool","vector","design"],
  },
  {
    name: "Brush",
    file: "brush-icon",
    category: "Diseño",
    tags: ["brush","paint","art","draw"],
  },
  {
    name: "Wand sparkles",
    file: "wand-sparkles-icon",
    category: "Diseño",
    tags: ["wand","magic","sparkles","edit"],
  },
  {
    name: "Spline",
    file: "spline-icon",
    category: "Diseño",
    tags: ["spline","curve","anchor","design"],
  },
  {
    name: "Cursor",
    file: "pointer-icon",
    category: "Diseño",
    tags: ["pointer","cursor","mouse","click"],
  },
  {
    name: "Mouse pointer",
    file: "mouse-pointer-2-icon",
    category: "Diseño",
    tags: ["mouse","pointer","cursor","click"],
  },
  {
    name: "Layers",
    file: "layers-icon",
    category: "Diseño",
    tags: ["layers","stack","depth","design"],
  },
  {
    name: "Layout grid",
    file: "layout-grid-icon",
    category: "Diseño",
    tags: ["layout","grid","cells","design"],
  },
  {
    name: "Layout dashboard",
    file: "layout-dashboard-icon",
    category: "Diseño",
    tags: ["layout","dashboard","panels","ui"],
  },
  {
    name: "Database zap",
    file: "database-zap-icon",
    category: "Bases de datos",
    tags: ["database","zap","fast","data"],
  },
  {
    name: "Database plus",
    file: "database-plus-icon",
    category: "Bases de datos",
    tags: ["database","add","create","data"],
  },
  {
    name: "Database search",
    file: "database-search-icon",
    category: "Bases de datos",
    tags: ["database","search","find","data"],
  },
  {
    name: "Database backup",
    file: "database-backup-icon",
    category: "Bases de datos",
    tags: ["database","backup","save","safety"],
  },
  {
    name: "Database check",
    file: "database-check-icon",
    category: "Bases de datos",
    tags: ["database","check","valid","ok"],
  },
  {
    name: "Database minus",
    file: "database-minus-icon",
    category: "Bases de datos",
    tags: ["database","remove","delete","data"],
  },
  {
    name: "Database close",
    file: "database-x-icon",
    category: "Bases de datos",
    tags: ["database","close","error","data"],
  },
  {
    name: "Database down",
    file: "database-arrow-down-icon",
    category: "Bases de datos",
    tags: ["database","down","import","data"],
  },
  {
    name: "Database up",
    file: "database-arrow-up-icon",
    category: "Bases de datos",
    tags: ["database","up","export","data"],
  },
  {
    name: "Archive restore",
    file: "archive-restore-icon",
    category: "Bases de datos",
    tags: ["archive","restore","recover","box"],
  },
  {
    name: "Braces",
    file: "braces-icon",
    category: "Desarrollo",
    tags: ["braces","code","json","dev"],
  },
  {
    name: "Brackets",
    file: "brackets-icon",
    category: "Desarrollo",
    tags: ["brackets","code","syntax","dev"],
  },
  {
    name: "Code XML",
    file: "code-xml-icon",
    category: "Desarrollo",
    tags: ["code","xml","html","tags"],
  },
  {
    name: "Terminal square",
    file: "square-terminal-icon",
    category: "Desarrollo",
    tags: ["terminal","console","command","shell"],
  },
  {
    name: "File terminal",
    file: "file-terminal-icon",
    category: "Desarrollo",
    tags: ["file","terminal","script","command"],
  },
  {
    name: "Git merge",
    file: "git-merge-icon",
    category: "Desarrollo",
    tags: ["git","merge","branch","version"],
  },
  {
    name: "Git commit",
    file: "git-commit-horizontal-icon",
    category: "Desarrollo",
    tags: ["git","commit","branch","version"],
  },
  {
    name: "Pull request",
    file: "git-pull-request-icon",
    category: "Desarrollo",
    tags: ["git","pull","request","merge"],
  },
  {
    name: "Heading 2",
    file: "heading-2-icon",
    category: "Desarrollo",
    tags: ["heading","title","text","format"],
  },
  {
    name: "Cursor input",
    file: "text-cursor-input-icon",
    category: "Desarrollo",
    tags: ["cursor","input","text","type"],
  },
  {
    name: "Share",
    file: "share-icon",
    category: "Redes sociales",
    tags: ["share","social","network","forward"],
  },
  {
    name: "Share nodes",
    file: "share-2-icon",
    category: "Redes sociales",
    tags: ["share","nodes","network","connect"],
  },
  {
    name: "RSS",
    file: "rss-icon",
    category: "Redes sociales",
    tags: ["rss","feed","subscribe","news"],
  },
  {
    name: "Megaphone",
    file: "megaphone-icon",
    category: "Redes sociales",
    tags: ["megaphone","announce","loud","speaker"],
  },
  {
    name: "Radio",
    file: "radio-icon",
    category: "Redes sociales",
    tags: ["radio","broadcast","music","waves"],
  },
  {
    name: "Ellipsis",
    file: "ellipsis-icon",
    category: "Redes sociales",
    tags: ["ellipsis","more","menu","dots"],
  },
  {
    name: "Ellipsis vertical",
    file: "ellipsis-vertical-icon",
    category: "Redes sociales",
    tags: ["ellipsis","more","menu","dots"],
  },
  {
    name: "Message share",
    file: "message-square-share-icon",
    category: "Redes sociales",
    tags: ["message","share","chat","social"],
  },
  {
    name: "Message heart",
    file: "message-circle-heart-icon",
    category: "Redes sociales",
    tags: ["message","heart","love","chat"],
  },
  {
    name: "Heart handshake",
    file: "heart-handshake-icon",
    category: "Redes sociales",
    tags: ["heart","handshake","help","care"],
  },
  {
    name: "Download",
    file: "download-icon",
    category: "Otros",
    tags: ["download","save","arrow","inbox"],
  },
  {
    name: "Upload",
    file: "upload-icon",
    category: "Otros",
    tags: ["upload","share","arrow","outbox"],
  },
  {
    name: "Star off",
    file: "star-off-icon",
    category: "Otros",
    tags: ["star","off","unfavorite","rating"],
  },
  {
    name: "Heart off",
    file: "heart-off-icon",
    category: "Otros",
    tags: ["heart","off","unfavorite","broken"],
  },
  {
    name: "Trash",
    file: "trash-2-icon",
    category: "Otros",
    tags: ["trash","delete","remove","bin"],
  },
  {
    name: "Flame",
    file: "flame-icon",
    category: "Otros",
    tags: ["flame","fire","hot","streak"],
  },
  {
    name: "Droplets",
    file: "droplets-icon",
    category: "Otros",
    tags: ["droplets","water","drop","rain"],
  },
  {
    name: "Ban",
    file: "ban-icon",
    category: "Otros",
    tags: ["ban","forbidden","no","stop"],
  },
  {
    name: "Run sprint",
    file: "run-sprint-icon",
    category: "Deporte",
    tags: ["run","sprint","jog","sport","speed"],
  },
  {
    name: "Play bug",
    file: "play-bug-icon",
    category: "Deporte",
    tags: ["bug","game","play","sport"],
  },
  {
    name: "Treasure chest",
    file: "treasure-chest-icon",
    category: "Juegos",
    tags: ["treasure","chest","loot","pirate","game"],
  },
  {
    name: "Twig",
    file: "twig-icon",
    category: "Naturaleza",
    tags: ["twig","branch","stick","nature"],
  },
  {
    name: "Rocking chair",
    file: "rocking-chair-icon",
    category: "Hogar",
    tags: ["chair","rocking","furniture","home"],
  },
  {
    name: "Remote control",
    file: "remote-control-icon",
    category: "Celular",
    tags: ["remote","control","tv","device"],
  },
  {
    name: "Yarn",
    file: "yarn-icon",
    category: "Otros",
    tags: ["yarn","knit","wool","craft"],
  },
  {
    name: "Thinking",
    file: "thinking-medium-icon",
    category: "Mood",
    tags: ["thinking","thought","mood","idea"],
  },
  {
    name: "Tags chevron",
    file: "tags-chevron-right-icon",
    category: "Comercio",
    tags: ["tags","labels","chevron","commerce"],
  },
  {
    name: "Tabs",
    file: "tabs-icon",
    category: "Desarrollo",
    tags: ["tabs","browser","development","window"],
  },
  {
    name: "Magnet",
    file: "magnet-icon",
    category: "Otros",
    tags: ["magnet","magnetic","attract","pull"],
  },
  {
    name: "Puzzle",
    file: "puzzle-icon",
    category: "Otros",
    tags: ["puzzle","piece","game","connect"],
  },
  {
    name: "Paw print",
    file: "paw-print-icon",
    category: "Otros",
    tags: ["paw","pet","animal","dog"],
  },
  {
    name: "Pencil ruler",
    file: "pencil-ruler-icon",
    category: "Otros",
    tags: ["pencil","ruler","design","measure"],
  },
  {
    name: "Award",
    file: "award-icon",
    category: "Otros",
    tags: ["award","prize","winner","medal"],
  },
  {
    name: "Zap",
    file: "zap-icon",
    category: "Otros",
    tags: ["zap","lightning","energy","fast"],
  },
  {
    name: "React",
    file: "react-icon",
    category: "Marcas",
    tags: ["react","framework","ui","javascript"],
  },
  {
    name: "Vercel",
    file: "vercel-icon",
    category: "Marcas",
    tags: ["vercel","next","deploy","hosting"],
  },
  {
    name: "Next.js",
    file: "next-icon",
    category: "Marcas",
    tags: ["next","nextjs","framework","react"],
  },
  {
    name: "Vue",
    file: "vue-icon",
    category: "Marcas",
    tags: ["vue","vuejs","framework","javascript"],
  },
  {
    name: "Angular",
    file: "angular-icon",
    category: "Marcas",
    tags: ["angular","framework","typescript"],
  },
  {
    name: "Svelte",
    file: "svelte-icon",
    category: "Marcas",
    tags: ["svelte","framework","javascript"],
  },
  {
    name: "TypeScript",
    file: "typescript-icon",
    category: "Marcas",
    tags: ["typescript","ts","language","typed"],
  },
  {
    name: "Python",
    file: "python-icon",
    category: "Marcas",
    tags: ["python","language","snake","script"],
  },
  {
    name: "Rust",
    file: "rust-icon",
    category: "Marcas",
    tags: ["rust","language","gear","systems"],
  },
  {
    name: "Node.js",
    file: "node-icon",
    category: "Marcas",
    tags: ["node","nodejs","javascript","server"],
  },
  {
    name: "Docker",
    file: "docker-icon",
    category: "Marcas",
    tags: ["docker","container","whale","devops"],
  },
  {
    name: "AWS",
    file: "aws-icon",
    category: "Marcas",
    tags: ["aws","amazon","cloud","smile"],
  },
  {
    name: "Figma",
    file: "figma-icon",
    category: "Marcas",
    tags: ["figma","design","ui","tool"],
  },
  {
    name: "Tailwind",
    file: "tailwind-icon",
    category: "Marcas",
    tags: ["tailwind","css","framework","design"],
  },
  {
    name: "Prisma",
    file: "prisma-icon",
    category: "Marcas",
    tags: ["prisma","database","orm","dev"],
  },
  {
    name: "Postgres",
    file: "postgres-icon",
    category: "Marcas",
    tags: ["postgres","postgresql","database","sql"],
  },
  {
    name: "Supabase",
    file: "supabase-icon",
    category: "Marcas",
    tags: ["supabase","database","backend","bada"],
  },
  {
    name: "Vite",
    file: "vite-icon",
    category: "Marcas",
    tags: ["vite","build","bundler","frontend"],
  },
  {
    name: "Stripe",
    file: "stripe-icon",
    category: "Marcas",
    tags: ["stripe","payments","billing","finance"],
  },
  {
    name: "PayPal",
    file: "paypal-icon",
    category: "Marcas",
    tags: ["paypal","payment","money","finance"],
  },
  {
    name: "Shopify",
    file: "shopify-icon",
    category: "Marcas",
    tags: ["shopify","store","ecommerce","shop"],
  },
  {
    name: "Google",
    file: "google-icon",
    category: "Marcas",
    tags: ["google","search","g","brand"],
  },
  {
    name: "X",
    file: "x-icon",
    category: "Marcas",
    tags: ["x","twitter","social","brand"],
  },
  {
    name: "Instagram",
    file: "instagram-icon",
    category: "Marcas",
    tags: ["instagram","social","camera","photo"],
  },
  {
    name: "LinkedIn",
    file: "linkedin-icon",
    category: "Marcas",
    tags: ["linkedin","social","job","network"],
  },
  {
    name: "YouTube",
    file: "youtube-icon",
    category: "Marcas",
    tags: ["youtube","video","play","media"],
  },
  {
    name: "Discord",
    file: "discord-icon",
    category: "Marcas",
    tags: ["discord","chat","gaming","voice"],
  },
  {
    name: "Slack",
    file: "slack-icon",
    category: "Marcas",
    tags: ["slack","chat","team","work"],
  },
  {
    name: "Spotify",
    file: "spotify-icon",
    category: "Marcas",
    tags: ["spotify","music","audio","stream"],
  },
  {
    name: "A",
    file: "letter-a-icon",
    category: "Abecedario",
    tags: ["letra","a","abecedario","alphabet"],
  },
  {
    name: "B",
    file: "letter-b-icon",
    category: "Abecedario",
    tags: ["letra","b","abecedario","alphabet"],
  },
  {
    name: "C",
    file: "letter-c-icon",
    category: "Abecedario",
    tags: ["letra","c","abecedario","alphabet"],
  },
  {
    name: "D",
    file: "letter-d-icon",
    category: "Abecedario",
    tags: ["letra","d","abecedario","alphabet"],
  },
  {
    name: "E",
    file: "letter-e-icon",
    category: "Abecedario",
    tags: ["letra","e","abecedario","alphabet"],
  },
  {
    name: "F",
    file: "letter-f-icon",
    category: "Abecedario",
    tags: ["letra","f","abecedario","alphabet"],
  },
  {
    name: "G",
    file: "letter-g-icon",
    category: "Abecedario",
    tags: ["letra","g","abecedario","alphabet"],
  },
  {
    name: "H",
    file: "letter-h-icon",
    category: "Abecedario",
    tags: ["letra","h","abecedario","alphabet"],
  },
  {
    name: "I",
    file: "letter-i-icon",
    category: "Abecedario",
    tags: ["letra","i","abecedario","alphabet"],
  },
  {
    name: "J",
    file: "letter-j-icon",
    category: "Abecedario",
    tags: ["letra","j","abecedario","alphabet"],
  },
  {
    name: "K",
    file: "letter-k-icon",
    category: "Abecedario",
    tags: ["letra","k","abecedario","alphabet"],
  },
  {
    name: "L",
    file: "letter-l-icon",
    category: "Abecedario",
    tags: ["letra","l","abecedario","alphabet"],
  },
  {
    name: "M",
    file: "letter-m-icon",
    category: "Abecedario",
    tags: ["letra","m","abecedario","alphabet"],
  },
  {
    name: "N",
    file: "letter-n-icon",
    category: "Abecedario",
    tags: ["letra","n","abecedario","alphabet"],
  },
  {
    name: "O",
    file: "letter-o-icon",
    category: "Abecedario",
    tags: ["letra","o","abecedario","alphabet"],
  },
  {
    name: "P",
    file: "letter-p-icon",
    category: "Abecedario",
    tags: ["letra","p","abecedario","alphabet"],
  },
  {
    name: "Q",
    file: "letter-q-icon",
    category: "Abecedario",
    tags: ["letra","q","abecedario","alphabet"],
  },
  {
    name: "R",
    file: "letter-r-icon",
    category: "Abecedario",
    tags: ["letra","r","abecedario","alphabet"],
  },
  {
    name: "S",
    file: "letter-s-icon",
    category: "Abecedario",
    tags: ["letra","s","abecedario","alphabet"],
  },
  {
    name: "T",
    file: "letter-t-icon",
    category: "Abecedario",
    tags: ["letra","t","abecedario","alphabet"],
  },
  {
    name: "U",
    file: "letter-u-icon",
    category: "Abecedario",
    tags: ["letra","u","abecedario","alphabet"],
  },
  {
    name: "V",
    file: "letter-v-icon",
    category: "Abecedario",
    tags: ["letra","v","abecedario","alphabet"],
  },
  {
    name: "W",
    file: "letter-w-icon",
    category: "Abecedario",
    tags: ["letra","w","abecedario","alphabet"],
  },
  {
    name: "X",
    file: "letter-x-icon",
    category: "Abecedario",
    tags: ["letra","x","abecedario","alphabet"],
  },
  {
    name: "Y",
    file: "letter-y-icon",
    category: "Abecedario",
    tags: ["letra","y","abecedario","alphabet"],
  },
  {
    name: "Z",
    file: "letter-z-icon",
    category: "Abecedario",
    tags: ["letra","z","abecedario","alphabet"],
  },
];

export function getIconCount(): number {
  return ICON_LIST.length;
}

export function getFeaturedIcons(limit = 5): IconMeta[] {
  return ICON_LIST.slice(-limit).reverse();
}

export function getCategories(): string[] {
  return Array.from(new Set(ICON_LIST.map((icon) => icon.category)));
}
