export interface IconMeta {
  name: string;
  file: string;
  category: string;
  tags: string[];
}

export const ICON_LIST: IconMeta[] = [
  {
    name: "Heart",
    file: "heart-icon",
    category: "UI essentials",
    tags: ["heart","love","favorite","like"],
  },
  {
    name: "Star",
    file: "star-icon",
    category: "UI essentials",
    tags: ["star","favorite","rating"],
  },
  {
    name: "Moon",
    file: "moon-icon",
    category: "UI essentials",
    tags: ["moon","night","dark"],
  },
  {
    name: "Sun",
    file: "sun-icon",
    category: "UI essentials",
    tags: ["sun","day","light","weather"],
  },
  {
    name: "Check",
    file: "check-icon",
    category: "UI essentials",
    tags: ["check","done","success"],
  },
  {
    name: "Bookmark",
    file: "bookmark-icon",
    category: "UI essentials",
    tags: ["bookmark","save","favorite"],
  },
  {
    name: "Settings",
    file: "settings-icon",
    category: "UI essentials",
    tags: ["settings","gear","configuration"],
  },
  {
    name: "Copy",
    file: "copy-icon",
    category: "UI essentials",
    tags: ["copy","duplicate","clipboard"],
  },
  {
    name: "Send",
    file: "send-icon",
    category: "UI essentials",
    tags: ["send","message","plane","paper"],
  },
  {
    name: "Bell",
    file: "bell-icon",
    category: "UI essentials",
    tags: ["bell","notification","alert"],
  },
  {
    name: "Camera",
    file: "camera-icon",
    category: "Media",
    tags: ["camera","photo","image","lens"],
  },
  {
    name: "Coffee",
    file: "coffee-icon",
    category: "Comida",
    tags: ["coffee","cafe","drink","break"],
  },
  {
    name: "Rocket",
    file: "rocket-icon",
    category: "UI essentials",
    tags: ["rocket","launch","ship"],
  },
  {
    name: "Smartphone",
    file: "smartphone-icon",
    category: "Celular",
    tags: ["smartphone","phone","mobile","cell"],
  },
  {
    name: "Tablet",
    file: "tablet-icon",
    category: "Celular",
    tags: ["tablet","screen","device"],
  },
  {
    name: "Laptop",
    file: "laptop-icon",
    category: "Celular",
    tags: ["laptop","computer","notebook"],
  },
  {
    name: "Monitor",
    file: "monitor-icon",
    category: "Celular",
    tags: ["monitor","screen","display"],
  },
  {
    name: "Battery",
    file: "battery-icon",
    category: "Celular",
    tags: ["battery","charge","power"],
  },
  {
    name: "Battery charging",
    file: "battery-charging-icon",
    category: "Celular",
    tags: ["battery","charging","power","energy"],
  },
  {
    name: "Wifi",
    file: "wifi-icon",
    category: "Celular",
    tags: ["wifi","wireless","internet","signal"],
  },
  {
    name: "Bluetooth",
    file: "bluetooth-icon",
    category: "Celular",
    tags: ["bluetooth","wireless","connect"],
  },
  {
    name: "Signal",
    file: "signal-icon",
    category: "Celular",
    tags: ["signal","antenna","bars","network"],
  },
  {
    name: "Phone",
    file: "phone-icon",
    category: "Celular",
    tags: ["phone","call","telephone"],
  },
  {
    name: "Code",
    file: "code-icon",
    category: "Desarrollo",
    tags: ["code","coding","developer","programming"],
  },
  {
    name: "Terminal",
    file: "terminal-icon",
    category: "Desarrollo",
    tags: ["terminal","console","command","shell"],
  },
  {
    name: "Git branch",
    file: "git-branch-icon",
    category: "Desarrollo",
    tags: ["git","branch","version","control"],
  },
  {
    name: "Database",
    file: "database-icon",
    category: "Desarrollo",
    tags: ["database","data","storage"],
  },
  {
    name: "Server",
    file: "server-icon",
    category: "Desarrollo",
    tags: ["server","hosting","backend"],
  },
  {
    name: "CPU",
    file: "cpu-icon",
    category: "Desarrollo",
    tags: ["cpu","chip","processor","hardware"],
  },
  {
    name: "File code",
    file: "file-code-icon",
    category: "Desarrollo",
    tags: ["file","code","source","programming"],
  },
  {
    name: "Languages",
    file: "languages-icon",
    category: "Desarrollo",
    tags: ["languages","translate","code","i18n"],
  },
  {
    name: "Calculator",
    file: "calculator-icon",
    category: "Desarrollo",
    tags: ["calculator","math","numbers"],
  },
  {
    name: "Bug",
    file: "bug-icon",
    category: "Desarrollo",
    tags: ["bug","insect","error","debug"],
  },
  {
    name: "Pizza",
    file: "pizza-icon",
    category: "Comida",
    tags: ["pizza","food","italian"],
  },
  {
    name: "Beer",
    file: "beer-icon",
    category: "Comida",
    tags: ["beer","drink","bar"],
  },
  {
    name: "Donut",
    file: "donut-icon",
    category: "Comida",
    tags: ["donut","doughnut","sweet","dessert"],
  },
  {
    name: "Ice cream",
    file: "ice-cream-bowl-icon",
    category: "Comida",
    tags: ["ice","cream","dessert","sweet"],
  },
  {
    name: "Cake",
    file: "cake-icon",
    category: "Comida",
    tags: ["cake","dessert","birthday"],
  },
  {
    name: "Apple",
    file: "apple-icon",
    category: "Comida",
    tags: ["apple","fruit","healthy"],
  },
  {
    name: "Sandwich",
    file: "sandwich-icon",
    category: "Comida",
    tags: ["sandwich","food","lunch"],
  },
  {
    name: "Utensils",
    file: "utensils-icon",
    category: "Comida",
    tags: ["utensils","fork","knife","eat","food"],
  },
  {
    name: "Croissant",
    file: "croissant-icon",
    category: "Comida",
    tags: ["croissant","bread","breakfast","pastry"],
  },
  {
    name: "Popcorn",
    file: "popcorn-icon",
    category: "Comida",
    tags: ["popcorn","movie","snack"],
  },
  {
    name: "Cloud",
    file: "cloud-icon",
    category: "Clima",
    tags: ["cloud","weather","sky"],
  },
  {
    name: "Cloud rain",
    file: "cloud-rain-icon",
    category: "Clima",
    tags: ["cloud","rain","weather","water"],
  },
  {
    name: "Cloud snow",
    file: "cloud-snow-icon",
    category: "Clima",
    tags: ["cloud","snow","winter","cold"],
  },
  {
    name: "Lightning",
    file: "cloud-lightning-icon",
    category: "Clima",
    tags: ["lightning","storm","thunder","cloud"],
  },
  {
    name: "Cloud sun",
    file: "cloud-sun-icon",
    category: "Clima",
    tags: ["cloud","sun","weather","partly"],
  },
  {
    name: "Snowflake",
    file: "snowflake-icon",
    category: "Clima",
    tags: ["snowflake","snow","winter","cold"],
  },
  {
    name: "Wind",
    file: "wind-icon",
    category: "Clima",
    tags: ["wind","air","weather","breeze"],
  },
  {
    name: "Umbrella",
    file: "umbrella-icon",
    category: "Clima",
    tags: ["umbrella","rain","protection"],
  },
  {
    name: "Rainbow",
    file: "rainbow-icon",
    category: "Clima",
    tags: ["rainbow","colors","sky","rain"],
  },
  {
    name: "Tornado",
    file: "tornado-icon",
    category: "Clima",
    tags: ["tornado","wind","storm","spin"],
  },
  {
    name: "Music",
    file: "music-icon",
    category: "Música",
    tags: ["music","note","song"],
  },
  {
    name: "Music note",
    file: "music-2-icon",
    category: "Música",
    tags: ["music","note","song"],
  },
  {
    name: "Headphones",
    file: "headphones-icon",
    category: "Música",
    tags: ["headphones","audio","listen","music"],
  },
  {
    name: "Mic",
    file: "mic-icon",
    category: "Música",
    tags: ["mic","microphone","voice","record"],
  },
  {
    name: "Play",
    file: "play-icon",
    category: "Música",
    tags: ["play","video","music","media"],
  },
  {
    name: "Pause",
    file: "pause-icon",
    category: "Música",
    tags: ["pause","video","music","media"],
  },
  {
    name: "Volume",
    file: "volume-2-icon",
    category: "Música",
    tags: ["volume","sound","loud","audio"],
  },
  {
    name: "Clapperboard",
    file: "clapperboard-icon",
    category: "Música",
    tags: ["clapperboard","film","movie","action"],
  },
  {
    name: "Gamepad",
    file: "gamepad-icon",
    category: "Música",
    tags: ["gamepad","controller","gaming","play"],
  },
  {
    name: "Film",
    file: "film-icon",
    category: "Música",
    tags: ["film","movie","video","reel"],
  },
  {
    name: "Plane",
    file: "plane-icon",
    category: "Viajes",
    tags: ["plane","airplane","travel","flight"],
  },
  {
    name: "Car",
    file: "car-icon",
    category: "Viajes",
    tags: ["car","vehicle","travel","drive"],
  },
  {
    name: "Bus",
    file: "bus-icon",
    category: "Viajes",
    tags: ["bus","vehicle","transport"],
  },
  {
    name: "Ship",
    file: "ship-icon",
    category: "Viajes",
    tags: ["ship","boat","sea","travel"],
  },
  {
    name: "Compass",
    file: "compass-icon",
    category: "Viajes",
    tags: ["compass","direction","navigate","travel"],
  },
  {
    name: "Map",
    file: "map-icon",
    category: "Viajes",
    tags: ["map","travel","navigation"],
  },
  {
    name: "Navigation",
    file: "navigation-icon",
    category: "Viajes",
    tags: ["navigation","gps","direction","arrow"],
  },
  {
    name: "Map pin",
    file: "map-pin-icon",
    category: "Viajes",
    tags: ["pin","location","map","address"],
  },
  {
    name: "Ticket",
    file: "ticket-icon",
    category: "Viajes",
    tags: ["ticket","entrance","event"],
  },
  {
    name: "Anchor",
    file: "anchor-icon",
    category: "Viajes",
    tags: ["anchor","ship","sea","marine"],
  },
  {
    name: "Home",
    file: "house-icon",
    category: "Hogar",
    tags: ["home","house","living"],
  },
  {
    name: "Lamp",
    file: "lamp-icon",
    category: "Hogar",
    tags: ["lamp","light","desk"],
  },
  {
    name: "Sofa",
    file: "sofa-icon",
    category: "Hogar",
    tags: ["sofa","couch","furniture","living"],
  },
  {
    name: "Bed",
    file: "bed-icon",
    category: "Hogar",
    tags: ["bed","sleep","rest"],
  },
  {
    name: "Lightbulb",
    file: "lightbulb-icon",
    category: "Hogar",
    tags: ["lightbulb","idea","light"],
  },
  {
    name: "TV",
    file: "tv-icon",
    category: "Hogar",
    tags: ["tv","television","screen"],
  },
  {
    name: "Keyboard",
    file: "keyboard-icon",
    category: "Hogar",
    tags: ["keyboard","type","key","input"],
  },
  {
    name: "Printer",
    file: "printer-icon",
    category: "Hogar",
    tags: ["printer","print","paper"],
  },
  {
    name: "Thermometer",
    file: "thermometer-icon",
    category: "Hogar",
    tags: ["thermometer","temperature","hot"],
  },
  {
    name: "Washing machine",
    file: "washing-machine-icon",
    category: "Hogar",
    tags: ["washing","machine","laundry","clean"],
  },
  {
    name: "Dollar",
    file: "dollar-sign-icon",
    category: "Negocios",
    tags: ["dollar","money","currency","cash"],
  },
  {
    name: "Bitcoin",
    file: "bitcoin-icon",
    category: "Negocios",
    tags: ["bitcoin","crypto","money","currency"],
  },
  {
    name: "Credit card",
    file: "credit-card-icon",
    category: "Negocios",
    tags: ["card","credit","payment","money"],
  },
  {
    name: "Wallet",
    file: "wallet-icon",
    category: "Negocios",
    tags: ["wallet","money","payment"],
  },
  {
    name: "Tag",
    file: "tag-icon",
    category: "Negocios",
    tags: ["tag","label","price","sale"],
  },
  {
    name: "Receipt",
    file: "receipt-icon",
    category: "Negocios",
    tags: ["receipt","invoice","bill","shop"],
  },
  {
    name: "Shopping cart",
    file: "shopping-cart-icon",
    category: "Negocios",
    tags: ["cart","shopping","buy","store"],
  },
  {
    name: "Trending up",
    file: "trending-up-icon",
    category: "Negocios",
    tags: ["trending","up","growth","chart"],
  },
  {
    name: "Pie chart",
    file: "chart-pie-icon",
    category: "Negocios",
    tags: ["pie","chart","stats","data"],
  },
  {
    name: "Coins",
    file: "coins-icon",
    category: "Negocios",
    tags: ["coins","money","currency","cash"],
  },
  {
    name: "Trophy",
    file: "trophy-icon",
    category: "Deportes",
    tags: ["trophy","award","winner","prize"],
  },
  {
    name: "Medal",
    file: "medal-icon",
    category: "Deportes",
    tags: ["medal","award","winner","olympics"],
  },
  {
    name: "Target",
    file: "target-icon",
    category: "Deportes",
    tags: ["target","goal","aim","shoot"],
  },
  {
    name: "Gift",
    file: "gift-icon",
    category: "Deportes",
    tags: ["gift","present","birthday","reward"],
  },
  {
    name: "Sparkle",
    file: "sparkle-icon",
    category: "Deportes",
    tags: ["sparkle","shine","glow","star"],
  },
  {
    name: "Palette",
    file: "palette-icon",
    category: "Deportes",
    tags: ["palette","colors","art","design"],
  },
  {
    name: "Gem",
    file: "gem-icon",
    category: "Deportes",
    tags: ["gem","diamond","jewel","premium"],
  },
];

export function getIconCount(): number {
  return ICON_LIST.length;
}

export function getFeaturedIcons(limit = 5): IconMeta[] {
  return ICON_LIST.slice(-limit).reverse();
}

export function getCategories(): string[] {
  return Array.from(new Set(ICON_LIST.map((icon) => icon.category)));
}
