"use client";

import { CodeIcon } from "@/icons/code-icon";
import { HeartIcon } from "@/icons/heart-icon";
import { SparkleIcon } from "@/icons/sparkle-icon";
import { ZapIcon } from "@/icons/zap-icon";
import { BellIcon } from "@/icons/bell-icon";
import { SearchIcon } from "@/icons/search-icon";
import { DownloadIcon } from "@/icons/download-icon";
import { GlobeIcon } from "@/icons/globe-icon";
import { CameraIcon } from "@/icons/camera-icon";
import { MoonIcon } from "@/icons/moon-icon";
import { CheckIcon } from "@/icons/check-icon";
import { SendIcon } from "@/icons/send-icon";
import { TerminalIcon } from "@/icons/terminal-icon";
import { StarIcon } from "@/icons/star-icon";
import { EyeIcon } from "@/icons/eye-icon";
import { CoffeeIcon } from "@/icons/coffee-icon";
import { PlayIcon } from "@/icons/play-icon";
import { LockIcon } from "@/icons/lock-icon";
import { FolderIcon } from "@/icons/folder-icon";
import { ArrowUpRightIcon } from "@/icons/arrow-up-right-icon";
import { BookmarkIcon } from "@/icons/bookmark-icon";
import { WifiIcon } from "@/icons/wifi-icon";
import { FireIcon } from "@/icons/fire-icon";
import { TrashIcon } from "@/icons/trash-icon";
import { PencilIcon } from "@/icons/pencil-icon";
import { CalendarIcon } from "@/icons/calendar-icon";
import { ClockIcon } from "@/icons/clock-icon";
import { MusicIcon } from "@/icons/music-icon";
import { VideoIcon } from "@/icons/video-icon";
import { UserIcon } from "@/icons/user-icon";
import { SettingsIcon } from "@/icons/settings-icon";
import { MicIcon } from "@/icons/mic-icon";
import { SunIcon } from "@/icons/sun-icon";
import { CloudIcon } from "@/icons/cloud-icon";
import { MapPinIcon } from "@/icons/map-pin-icon";
import { FlagIcon } from "@/icons/flag-icon";
import { ImageIcon } from "@/icons/image-icon";
import { HeadphonesIcon } from "@/icons/headphones-icon";
import { VolumeIcon } from "@/icons/volume-icon";
import { LinkIcon } from "@/icons/link-icon";
import { CopyIcon } from "@/icons/copy-icon";
import { ShareIcon } from "@/icons/share-icon";
import { FilterIcon } from "@/icons/filter-icon";
import { RefreshIcon } from "@/icons/refresh-icon";
import { BatteryIcon } from "@/icons/battery-icon";
import { PowerIcon } from "@/icons/power-icon";
import { TrophyIcon } from "@/icons/trophy-icon";
import { RocketIcon } from "@/icons/rocket-icon";
import { GiftIcon } from "@/icons/gift-icon";
import { SmileIcon } from "@/icons/smile-icon";
import { ThumbsUpIcon } from "@/icons/thumbs-up-icon";
import { MessageCircleIcon } from "@/icons/message-circle-icon";
import { MailIcon } from "@/icons/mail-icon";
import { HomeIcon } from "@/icons/home-icon";
import { FileIcon } from "@/icons/file-icon";
import { GitBranchIcon } from "@/icons/git-branch-icon";
import { DatabaseIcon } from "@/icons/database-icon";
import { LayersIcon } from "@/icons/layers-icon";
import { PackageIcon } from "@/icons/package-icon";
import { PaletteIcon } from "@/icons/palette-icon";
import { FilmIcon } from "@/icons/film-icon";
import { CompassIcon } from "@/icons/compass-icon";
import { LeafIcon } from "@/icons/leaf-icon";
import { ShieldIcon } from "@/icons/shield-icon";
import { KeyIcon } from "@/icons/key-icon";
import { TagIcon } from "@/icons/tag-icon";
import { InboxIcon } from "@/icons/inbox-icon";
import { ClipboardIcon } from "@/icons/clipboard-icon";
import { ServerIcon } from "@/icons/server-icon";
import { BugIcon } from "@/icons/bug-icon";
import { CpuIcon } from "@/icons/cpu-icon";
import { HardDriveIcon } from "@/icons/hard-drive-icon";
import { MonitorIcon } from "@/icons/monitor-icon";
import { AwardIcon } from "@/icons/award-icon";
import { UmbrellaIcon } from "@/icons/umbrella-icon";
import { AnchorIcon } from "@/icons/anchor-icon";
import { AtSignIcon } from "@/icons/at-sign-icon";
import { HashIcon } from "@/icons/hash-icon";

export type IconConfig = {
  color: string;
  speed: number;
  size: number;
};

export type LibraryIcon = {
  id: string;
  num: string;
  name: string;
  category: string;
  fileName: string;
  componentName: string;
  defaultConfig: IconConfig;
  Component: (props: {
    size?: number;
    className?: string;
    duration?: number;
  }) => React.ReactElement;
  baseDuration: number;
};

export const ICON_LIST: LibraryIcon[] = [
  {
    id: "sparkle",
    num: "01",
    name: "Sparkles",
    category: "Essentials",
    fileName: "sparkle-icon",
    componentName: "SparkleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SparkleIcon,
    baseDuration: 0.5,
  },
  {
    id: "heart",
    num: "02",
    name: "Heart",
    category: "Essentials",
    fileName: "heart-icon",
    componentName: "HeartIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HeartIcon,
    baseDuration: 0.55,
  },
  {
    id: "code",
    num: "03",
    name: "Code",
    category: "Development",
    fileName: "code-icon",
    componentName: "CodeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CodeIcon,
    baseDuration: 0.4,
  },
  {
    id: "zap",
    num: "04",
    name: "Zap",
    category: "Essentials",
    fileName: "zap-icon",
    componentName: "ZapIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ZapIcon,
    baseDuration: 0.45,
  },
  {
    id: "check",
    num: "05",
    name: "Check",
    category: "Essentials",
    fileName: "check-icon",
    componentName: "CheckIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CheckIcon,
    baseDuration: 0.45,
  },
  {
    id: "bell",
    num: "06",
    name: "Bell",
    category: "Interface",
    fileName: "bell-icon",
    componentName: "BellIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BellIcon,
    baseDuration: 0.55,
  },
  {
    id: "search",
    num: "07",
    name: "Search",
    category: "Interface",
    fileName: "search-icon",
    componentName: "SearchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SearchIcon,
    baseDuration: 0.5,
  },
  {
    id: "download",
    num: "08",
    name: "Download",
    category: "Interface",
    fileName: "download-icon",
    componentName: "DownloadIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DownloadIcon,
    baseDuration: 0.5,
  },
  {
    id: "globe",
    num: "09",
    name: "Globe",
    category: "Interface",
    fileName: "globe-icon",
    componentName: "GlobeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GlobeIcon,
    baseDuration: 0.6,
  },
  {
    id: "moon",
    num: "10",
    name: "Moon",
    category: "Interface",
    fileName: "moon-icon",
    componentName: "MoonIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MoonIcon,
    baseDuration: 0.55,
  },
  {
    id: "send",
    num: "11",
    name: "Send",
    category: "Interface",
    fileName: "send-icon",
    componentName: "SendIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SendIcon,
    baseDuration: 0.5,
  },
  {
    id: "camera",
    num: "12",
    name: "Camera",
    category: "Media",
    fileName: "camera-icon",
    componentName: "CameraIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CameraIcon,
    baseDuration: 0.5,
  },
  {
    id: "terminal",
    num: "13",
    name: "Terminal",
    category: "Development",
    fileName: "terminal-icon",
    componentName: "TerminalIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TerminalIcon,
    baseDuration: 0.5,
  },
  {
    id: "star",
    num: "14",
    name: "Star",
    category: "Essentials",
    fileName: "star-icon",
    componentName: "StarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: StarIcon,
    baseDuration: 0.5,
  },
  {
    id: "eye",
    num: "15",
    name: "Eye",
    category: "Interface",
    fileName: "eye-icon",
    componentName: "EyeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: EyeIcon,
    baseDuration: 0.55,
  },
  {
    id: "coffee",
    num: "16",
    name: "Coffee",
    category: "Essentials",
    fileName: "coffee-icon",
    componentName: "CoffeeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CoffeeIcon,
    baseDuration: 0.6,
  },
  {
    id: "play",
    num: "17",
    name: "Play",
    category: "Media",
    fileName: "play-icon",
    componentName: "PlayIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlayIcon,
    baseDuration: 0.5,
  },
  {
    id: "lock",
    num: "18",
    name: "Lock",
    category: "Interface",
    fileName: "lock-icon",
    componentName: "LockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LockIcon,
    baseDuration: 0.5,
  },
  {
    id: "folder",
    num: "19",
    name: "Folder",
    category: "Development",
    fileName: "folder-icon",
    componentName: "FolderIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FolderIcon,
    baseDuration: 0.5,
  },
  {
    id: "arrow-up-right",
    num: "20",
    name: "Arrow Up Right",
    category: "Interface",
    fileName: "arrow-up-right-icon",
    componentName: "ArrowUpRightIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ArrowUpRightIcon,
    baseDuration: 0.45,
  },
  {
    id: "bookmark",
    num: "21",
    name: "Bookmark",
    category: "Interface",
    fileName: "bookmark-icon",
    componentName: "BookmarkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BookmarkIcon,
    baseDuration: 0.5,
  },
  {
    id: "wifi",
    num: "22",
    name: "Wifi",
    category: "Interface",
    fileName: "wifi-icon",
    componentName: "WifiIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WifiIcon,
    baseDuration: 0.55,
  },
  {
    id: "fire",
    num: "23",
    name: "Fire",
    category: "Essentials",
    fileName: "fire-icon",
    componentName: "FireIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FireIcon,
    baseDuration: 0.55,
  },
  {
    id: "trash",
    num: "24",
    name: "Trash",
    category: "Interface",
    fileName: "trash-icon",
    componentName: "TrashIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TrashIcon,
    baseDuration: 0.5,
  },
  {
    id: "pencil",
    num: "25",
    name: "Pencil",
    category: "Interface",
    fileName: "pencil-icon",
    componentName: "PencilIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PencilIcon,
    baseDuration: 0.5,
  },
  {
    id: "calendar",
    num: "26",
    name: "Calendar",
    category: "Essentials",
    fileName: "calendar-icon",
    componentName: "CalendarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CalendarIcon,
    baseDuration: 0.55,
  },
  {
    id: "clock",
    num: "27",
    name: "Clock",
    category: "Essentials",
    fileName: "clock-icon",
    componentName: "ClockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClockIcon,
    baseDuration: 0.6,
  },
  {
    id: "music",
    num: "28",
    name: "Music",
    category: "Media",
    fileName: "music-icon",
    componentName: "MusicIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MusicIcon,
    baseDuration: 0.55,
  },
  {
    id: "video",
    num: "29",
    name: "Video",
    category: "Media",
    fileName: "video-icon",
    componentName: "VideoIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: VideoIcon,
    baseDuration: 0.5,
  },
  {
    id: "user",
    num: "30",
    name: "User",
    category: "Interface",
    fileName: "user-icon",
    componentName: "UserIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UserIcon,
    baseDuration: 0.5,
  },
  {
    id: "settings",
    num: "31",
    name: "Settings",
    category: "Development",
    fileName: "settings-icon",
    componentName: "SettingsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SettingsIcon,
    baseDuration: 0.6,
  },
  {
    id: "mic",
    num: "32",
    name: "Mic",
    category: "Media",
    fileName: "mic-icon",
    componentName: "MicIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MicIcon,
    baseDuration: 0.55,
  },
  {
    id: "sun",
    num: "33",
    name: "Sun",
    category: "Essentials",
    fileName: "sun-icon",
    componentName: "SunIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SunIcon,
    baseDuration: 0.55,
  },
  {
    id: "cloud",
    num: "34",
    name: "Cloud",
    category: "Essentials",
    fileName: "cloud-icon",
    componentName: "CloudIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CloudIcon,
    baseDuration: 0.55,
  },
  {
    id: "map-pin",
    num: "35",
    name: "Map Pin",
    category: "Interface",
    fileName: "map-pin-icon",
    componentName: "MapPinIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MapPinIcon,
    baseDuration: 0.5,
  },
  {
    id: "flag",
    num: "36",
    name: "Flag",
    category: "Interface",
    fileName: "flag-icon",
    componentName: "FlagIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FlagIcon,
    baseDuration: 0.5,
  },
  {
    id: "image",
    num: "37",
    name: "Image",
    category: "Media",
    fileName: "image-icon",
    componentName: "ImageIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ImageIcon,
    baseDuration: 0.5,
  },
  {
    id: "headphones",
    num: "38",
    name: "Headphones",
    category: "Media",
    fileName: "headphones-icon",
    componentName: "HeadphonesIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HeadphonesIcon,
    baseDuration: 0.55,
  },
  {
    id: "volume",
    num: "39",
    name: "Volume",
    category: "Media",
    fileName: "volume-icon",
    componentName: "VolumeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: VolumeIcon,
    baseDuration: 0.55,
  },
  {
    id: "link",
    num: "40",
    name: "Link",
    category: "Interface",
    fileName: "link-icon",
    componentName: "LinkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LinkIcon,
    baseDuration: 0.5,
  },
  {
    id: "copy",
    num: "41",
    name: "Copy",
    category: "Interface",
    fileName: "copy-icon",
    componentName: "CopyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CopyIcon,
    baseDuration: 0.5,
  },
  {
    id: "share",
    num: "42",
    name: "Share",
    category: "Interface",
    fileName: "share-icon",
    componentName: "ShareIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShareIcon,
    baseDuration: 0.5,
  },
  {
    id: "filter",
    num: "43",
    name: "Filter",
    category: "Development",
    fileName: "filter-icon",
    componentName: "FilterIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FilterIcon,
    baseDuration: 0.5,
  },
  {
    id: "refresh",
    num: "44",
    name: "Refresh",
    category: "Development",
    fileName: "refresh-icon",
    componentName: "RefreshIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RefreshIcon,
    baseDuration: 0.6,
  },
  {
    id: "battery",
    num: "45",
    name: "Battery",
    category: "Interface",
    fileName: "battery-icon",
    componentName: "BatteryIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BatteryIcon,
    baseDuration: 0.6,
  },
  {
    id: "power",
    num: "46",
    name: "Power",
    category: "Interface",
    fileName: "power-icon",
    componentName: "PowerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PowerIcon,
    baseDuration: 0.55,
  },
  {
    id: "trophy",
    num: "47",
    name: "Trophy",
    category: "Essentials",
    fileName: "trophy-icon",
    componentName: "TrophyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TrophyIcon,
    baseDuration: 0.55,
  },
  {
    id: "rocket",
    num: "48",
    name: "Rocket",
    category: "Development",
    fileName: "rocket-icon",
    componentName: "RocketIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RocketIcon,
    baseDuration: 0.55,
  },
  {
    id: "gift",
    num: "49",
    name: "Gift",
    category: "Essentials",
    fileName: "gift-icon",
    componentName: "GiftIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GiftIcon,
    baseDuration: 0.55,
  },
  {
    id: "smile",
    num: "50",
    name: "Smile",
    category: "Interface",
    fileName: "smile-icon",
    componentName: "SmileIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SmileIcon,
    baseDuration: 0.55,
  },
  {
    id: "thumbs-up",
    num: "51",
    name: "Thumbs Up",
    category: "Interface",
    fileName: "thumbs-up-icon",
    componentName: "ThumbsUpIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ThumbsUpIcon,
    baseDuration: 0.5,
  },
  {
    id: "message-circle",
    num: "52",
    name: "Message",
    category: "Interface",
    fileName: "message-circle-icon",
    componentName: "MessageCircleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MessageCircleIcon,
    baseDuration: 0.5,
  },
  {
    id: "mail",
    num: "53",
    name: "Mail",
    category: "Interface",
    fileName: "mail-icon",
    componentName: "MailIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MailIcon,
    baseDuration: 0.5,
  },
  {
    id: "home",
    num: "54",
    name: "Home",
    category: "Interface",
    fileName: "home-icon",
    componentName: "HomeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HomeIcon,
    baseDuration: 0.5,
  },
  {
    id: "file",
    num: "55",
    name: "File",
    category: "Development",
    fileName: "file-icon",
    componentName: "FileIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FileIcon,
    baseDuration: 0.5,
  },
  {
    id: "git-branch",
    num: "56",
    name: "Git Branch",
    category: "Development",
    fileName: "git-branch-icon",
    componentName: "GitBranchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GitBranchIcon,
    baseDuration: 0.55,
  },
  {
    id: "database",
    num: "57",
    name: "Database",
    category: "Development",
    fileName: "database-icon",
    componentName: "DatabaseIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DatabaseIcon,
    baseDuration: 0.6,
  },
  {
    id: "layers",
    num: "58",
    name: "Layers",
    category: "Development",
    fileName: "layers-icon",
    componentName: "LayersIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LayersIcon,
    baseDuration: 0.55,
  },
  {
    id: "package",
    num: "59",
    name: "Package",
    category: "Development",
    fileName: "package-icon",
    componentName: "PackageIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PackageIcon,
    baseDuration: 0.55,
  },
  {
    id: "palette",
    num: "60",
    name: "Palette",
    category: "Media",
    fileName: "palette-icon",
    componentName: "PaletteIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaletteIcon,
    baseDuration: 0.55,
  },
  {
    id: "film",
    num: "61",
    name: "Film",
    category: "Media",
    fileName: "film-icon",
    componentName: "FilmIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FilmIcon,
    baseDuration: 0.5,
  },
  {
    id: "compass",
    num: "62",
    name: "Compass",
    category: "Essentials",
    fileName: "compass-icon",
    componentName: "CompassIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CompassIcon,
    baseDuration: 0.6,
  },
  {
    id: "leaf",
    num: "63",
    name: "Leaf",
    category: "Essentials",
    fileName: "leaf-icon",
    componentName: "LeafIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LeafIcon,
    baseDuration: 0.55,
  },
  {
    id: "shield",
    num: "64",
    name: "Shield",
    category: "Interface",
    fileName: "shield-icon",
    componentName: "ShieldIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShieldIcon,
    baseDuration: 0.55,
  },
  {
    id: "key",
    num: "65",
    name: "Key",
    category: "Interface",
    fileName: "key-icon",
    componentName: "KeyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: KeyIcon,
    baseDuration: 0.6,
  },
  {
    id: "tag",
    num: "66",
    name: "Tag",
    category: "Interface",
    fileName: "tag-icon",
    componentName: "TagIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TagIcon,
    baseDuration: 0.5,
  },
  {
    id: "inbox",
    num: "67",
    name: "Inbox",
    category: "Interface",
    fileName: "inbox-icon",
    componentName: "InboxIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: InboxIcon,
    baseDuration: 0.5,
  },
  {
    id: "clipboard",
    num: "68",
    name: "Clipboard",
    category: "Development",
    fileName: "clipboard-icon",
    componentName: "ClipboardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClipboardIcon,
    baseDuration: 0.5,
  },
  {
    id: "server",
    num: "69",
    name: "Server",
    category: "Development",
    fileName: "server-icon",
    componentName: "ServerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ServerIcon,
    baseDuration: 0.55,
  },
  {
    id: "bug",
    num: "70",
    name: "Bug",
    category: "Development",
    fileName: "bug-icon",
    componentName: "BugIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BugIcon,
    baseDuration: 0.55,
  },
  {
    id: "cpu",
    num: "71",
    name: "CPU",
    category: "Development",
    fileName: "cpu-icon",
    componentName: "CpuIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CpuIcon,
    baseDuration: 0.55,
  },
  {
    id: "hard-drive",
    num: "72",
    name: "Hard Drive",
    category: "Development",
    fileName: "hard-drive-icon",
    componentName: "HardDriveIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HardDriveIcon,
    baseDuration: 0.55,
  },
  {
    id: "monitor",
    num: "73",
    name: "Monitor",
    category: "Media",
    fileName: "monitor-icon",
    componentName: "MonitorIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MonitorIcon,
    baseDuration: 0.5,
  },
  {
    id: "award",
    num: "74",
    name: "Award",
    category: "Essentials",
    fileName: "award-icon",
    componentName: "AwardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AwardIcon,
    baseDuration: 0.55,
  },
  {
    id: "umbrella",
    num: "75",
    name: "Umbrella",
    category: "Essentials",
    fileName: "umbrella-icon",
    componentName: "UmbrellaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UmbrellaIcon,
    baseDuration: 0.55,
  },
  {
    id: "anchor",
    num: "76",
    name: "Anchor",
    category: "Essentials",
    fileName: "anchor-icon",
    componentName: "AnchorIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AnchorIcon,
    baseDuration: 0.6,
  },
  {
    id: "at-sign",
    num: "77",
    name: "At Sign",
    category: "Interface",
    fileName: "at-sign-icon",
    componentName: "AtSignIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AtSignIcon,
    baseDuration: 0.6,
  },
  {
    id: "hash",
    num: "78",
    name: "Hash",
    category: "Interface",
    fileName: "hash-icon",
    componentName: "HashIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HashIcon,
    baseDuration: 0.5,
  },
];

export const CATEGORIES = [
  "All icons",
  ...Array.from(new Set(ICON_LIST.map((i) => i.category))),
];
