"use client";

import { CodeIcon } from "@/icons/code-icon";
import { HeartIcon } from "@/icons/heart-icon";
import { SparkleIcon } from "@/icons/sparkle-icon";
import { ZapIcon } from "@/icons/zap-icon";
import { BellIcon } from "@/icons/bell-icon";
import { SearchIcon } from "@/icons/search-icon";
import { DownloadIcon } from "@/icons/download-icon";
import { GlobeIcon } from "@/icons/globe-icon";
import { CameraIcon } from "@/icons/camera-icon";
import { MoonIcon } from "@/icons/moon-icon";
import { CheckIcon } from "@/icons/check-icon";
import { SendIcon } from "@/icons/send-icon";
import { TerminalIcon } from "@/icons/terminal-icon";
import { StarIcon } from "@/icons/star-icon";
import { EyeIcon } from "@/icons/eye-icon";
import { CoffeeIcon } from "@/icons/coffee-icon";
import { PlayIcon } from "@/icons/play-icon";
import { LockIcon } from "@/icons/lock-icon";
import { FolderIcon } from "@/icons/folder-icon";
import { ArrowUpRightIcon } from "@/icons/arrow-up-right-icon";
import { BookmarkIcon } from "@/icons/bookmark-icon";
import { WifiIcon } from "@/icons/wifi-icon";
import { FireIcon } from "@/icons/fire-icon";
import { TrashIcon } from "@/icons/trash-icon";
import { PencilIcon } from "@/icons/pencil-icon";
import { CalendarIcon } from "@/icons/calendar-icon";
import { ClockIcon } from "@/icons/clock-icon";
import { MusicIcon } from "@/icons/music-icon";
import { VideoIcon } from "@/icons/video-icon";
import { UserIcon } from "@/icons/user-icon";
import { SettingsIcon } from "@/icons/settings-icon";
import { MicIcon } from "@/icons/mic-icon";
import { SunIcon } from "@/icons/sun-icon";
import { CloudIcon } from "@/icons/cloud-icon";
import { MapPinIcon } from "@/icons/map-pin-icon";
import { FlagIcon } from "@/icons/flag-icon";
import { ImageIcon } from "@/icons/image-icon";
import { HeadphonesIcon } from "@/icons/headphones-icon";
import { VolumeIcon } from "@/icons/volume-icon";
import { LinkIcon } from "@/icons/link-icon";
import { CopyIcon } from "@/icons/copy-icon";
import { ShareIcon } from "@/icons/share-icon";
import { FilterIcon } from "@/icons/filter-icon";
import { RefreshIcon } from "@/icons/refresh-icon";
import { BatteryIcon } from "@/icons/battery-icon";
import { PowerIcon } from "@/icons/power-icon";
import { TrophyIcon } from "@/icons/trophy-icon";
import { RocketIcon } from "@/icons/rocket-icon";
import { GiftIcon } from "@/icons/gift-icon";
import { SmileIcon } from "@/icons/smile-icon";
import { ThumbsUpIcon } from "@/icons/thumbs-up-icon";
import { MessageCircleIcon } from "@/icons/message-circle-icon";
import { MailIcon } from "@/icons/mail-icon";
import { HomeIcon } from "@/icons/home-icon";
import { FileIcon } from "@/icons/file-icon";
import { GitBranchIcon } from "@/icons/git-branch-icon";
import { DatabaseIcon } from "@/icons/database-icon";
import { LayersIcon } from "@/icons/layers-icon";
import { PackageIcon } from "@/icons/package-icon";
import { PaletteIcon } from "@/icons/palette-icon";
import { FilmIcon } from "@/icons/film-icon";
import { CompassIcon } from "@/icons/compass-icon";
import { LeafIcon } from "@/icons/leaf-icon";
import { ShieldIcon } from "@/icons/shield-icon";
import { KeyIcon } from "@/icons/key-icon";
import { TagIcon } from "@/icons/tag-icon";
import { InboxIcon } from "@/icons/inbox-icon";
import { ClipboardIcon } from "@/icons/clipboard-icon";
import { ServerIcon } from "@/icons/server-icon";
import { BugIcon } from "@/icons/bug-icon";
import { CpuIcon } from "@/icons/cpu-icon";
import { HardDriveIcon } from "@/icons/hard-drive-icon";
import { MonitorIcon } from "@/icons/monitor-icon";
import { AwardIcon } from "@/icons/award-icon";
import { UmbrellaIcon } from "@/icons/umbrella-icon";
import { AnchorIcon } from "@/icons/anchor-icon";
import { AtSignIcon } from "@/icons/at-sign-icon";
import { HashIcon } from "@/icons/hash-icon";
import { ScissorsIcon } from "@/icons/scissors-icon";
import { CropIcon } from "@/icons/crop-icon";
import { SlidersIcon } from "@/icons/sliders-icon";
import { WrenchIcon } from "@/icons/wrench-icon";
import { PaperclipIcon } from "@/icons/paperclip-icon";
import { BrushIcon } from "@/icons/brush-icon";
import { RadioIcon } from "@/icons/radio-icon";
import { DiscIcon } from "@/icons/disc-icon";
import { NavigationIcon } from "@/icons/navigation-icon";
import { HourglassIcon } from "@/icons/hourglass-icon";
import { SnowflakeIcon } from "@/icons/snowflake-icon";
import { WindIcon } from "@/icons/wind-icon";
import { DropletIcon } from "@/icons/droplet-icon";
import { PercentIcon } from "@/icons/percent-icon";
import { ApertureIcon } from "@/icons/aperture-icon";
import { ChevronDownIcon } from "@/icons/chevron-down-icon";
import { GridIcon } from "@/icons/grid-icon";
import { MenuIcon } from "@/icons/menu-icon";
import { SunriseIcon } from "@/icons/sunrise-icon";
import { CloudRainIcon } from "@/icons/cloud-rain-icon";
import { MountainIcon } from "@/icons/mountain-icon";
import { GamepadIcon } from "@/icons/gamepad-icon";
import { FeatherIcon } from "@/icons/feather-icon";
import { HammerIcon } from "@/icons/hammer-icon";
import { RulerIcon } from "@/icons/ruler-icon";
import { MoveIcon } from "@/icons/move-icon";
import { MaximizeIcon } from "@/icons/maximize-icon";
import { ActivityIcon } from "@/icons/activity-icon";
import { PlugIcon } from "@/icons/plug-icon";
import { AlarmClockIcon } from "@/icons/alarm-clock-icon";
import { WalletIcon } from "@/icons/wallet-icon";
import { PhoneIcon } from "@/icons/phone-icon";
import { PlaneIcon } from "@/icons/plane-icon";
import { TicketIcon } from "@/icons/ticket-icon";
import { AtomIcon } from "@/icons/atom-icon";
import { LightbulbIcon } from "@/icons/lightbulb-icon";
import { FingerprintIcon } from "@/icons/fingerprint-icon";
import { QrCodeIcon } from "@/icons/qr-code-icon";
import { WavesIcon } from "@/icons/waves-icon";
import { CloudLightningIcon } from "@/icons/cloud-lightning-icon";
import { PuzzleIcon } from "@/icons/puzzle-icon";
import { TruckIcon } from "@/icons/truck-icon";
import { BikeIcon } from "@/icons/bike-icon";
import { PlusIcon } from "@/icons/plus-icon";
import { CircleIcon } from "@/icons/circle-icon";
import { BrainIcon } from "@/icons/brain-icon";
import { BotIcon } from "@/icons/bot-icon";
import { ScanIcon } from "@/icons/scan-icon";
import { UtensilsIcon } from "@/icons/utensils-icon";
import { TreePineIcon } from "@/icons/tree-pine-icon";
import { ShipIcon } from "@/icons/ship-icon";
import { CakeIcon } from "@/icons/cake-icon";
import { GhostIcon } from "@/icons/ghost-icon";
import { MinusIcon } from "@/icons/minus-icon";
import { TriangleIcon } from "@/icons/triangle-icon";
import { SquareIcon } from "@/icons/square-icon";
import { CookieIcon } from "@/icons/cookie-icon";
import { DumbbellIcon } from "@/icons/dumbbell-icon";
import { Flower2Icon } from "@/icons/flower-2-icon";
import { PaintBucketIcon } from "@/icons/paint-bucket-icon";
import { ClapperboardIcon } from "@/icons/clapperboard-icon";
import { Dice5Icon } from "@/icons/dice-5-icon";
import { CoinsIcon } from "@/icons/coins-icon";
import { BluetoothIcon } from "@/icons/bluetooth-icon";
import { MicroscopeIcon } from "@/icons/microscope-icon";

export type IconConfig = {
  color: string;
  speed: number;
  size: number;
};

export type LibraryIcon = {
  id: string;
  num: string;
  name: string;
  category: string;
  fileName: string;
  componentName: string;
  defaultConfig: IconConfig;
  Component: (props: {
    size?: number;
    className?: string;
    duration?: number;
  }) => React.ReactElement;
  baseDuration: number;
};

export const ICON_LIST: LibraryIcon[] = [
  {
    id: "sparkle",
    num: "01",
    name: "Sparkles",
    category: "Essentials",
    fileName: "sparkle-icon",
    componentName: "SparkleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SparkleIcon,
    baseDuration: 0.5,
  },
  {
    id: "heart",
    num: "02",
    name: "Heart",
    category: "Essentials",
    fileName: "heart-icon",
    componentName: "HeartIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HeartIcon,
    baseDuration: 0.55,
  },
  {
    id: "code",
    num: "03",
    name: "Code",
    category: "Development",
    fileName: "code-icon",
    componentName: "CodeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CodeIcon,
    baseDuration: 0.4,
  },
  {
    id: "zap",
    num: "04",
    name: "Zap",
    category: "Essentials",
    fileName: "zap-icon",
    componentName: "ZapIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ZapIcon,
    baseDuration: 0.45,
  },
  {
    id: "check",
    num: "05",
    name: "Check",
    category: "Essentials",
    fileName: "check-icon",
    componentName: "CheckIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CheckIcon,
    baseDuration: 0.45,
  },
  {
    id: "bell",
    num: "06",
    name: "Bell",
    category: "Interface",
    fileName: "bell-icon",
    componentName: "BellIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BellIcon,
    baseDuration: 0.55,
  },
  {
    id: "search",
    num: "07",
    name: "Search",
    category: "Interface",
    fileName: "search-icon",
    componentName: "SearchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SearchIcon,
    baseDuration: 0.5,
  },
  {
    id: "download",
    num: "08",
    name: "Download",
    category: "Interface",
    fileName: "download-icon",
    componentName: "DownloadIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DownloadIcon,
    baseDuration: 0.5,
  },
  {
    id: "globe",
    num: "09",
    name: "Globe",
    category: "Interface",
    fileName: "globe-icon",
    componentName: "GlobeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GlobeIcon,
    baseDuration: 0.6,
  },
  {
    id: "moon",
    num: "10",
    name: "Moon",
    category: "Interface",
    fileName: "moon-icon",
    componentName: "MoonIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MoonIcon,
    baseDuration: 0.55,
  },
  {
    id: "send",
    num: "11",
    name: "Send",
    category: "Interface",
    fileName: "send-icon",
    componentName: "SendIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SendIcon,
    baseDuration: 0.5,
  },
  {
    id: "camera",
    num: "12",
    name: "Camera",
    category: "Media",
    fileName: "camera-icon",
    componentName: "CameraIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CameraIcon,
    baseDuration: 0.5,
  },
  {
    id: "terminal",
    num: "13",
    name: "Terminal",
    category: "Development",
    fileName: "terminal-icon",
    componentName: "TerminalIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TerminalIcon,
    baseDuration: 0.5,
  },
  {
    id: "star",
    num: "14",
    name: "Star",
    category: "Essentials",
    fileName: "star-icon",
    componentName: "StarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: StarIcon,
    baseDuration: 0.5,
  },
  {
    id: "eye",
    num: "15",
    name: "Eye",
    category: "Interface",
    fileName: "eye-icon",
    componentName: "EyeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: EyeIcon,
    baseDuration: 0.55,
  },
  {
    id: "coffee",
    num: "16",
    name: "Coffee",
    category: "Essentials",
    fileName: "coffee-icon",
    componentName: "CoffeeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CoffeeIcon,
    baseDuration: 0.6,
  },
  {
    id: "play",
    num: "17",
    name: "Play",
    category: "Media",
    fileName: "play-icon",
    componentName: "PlayIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlayIcon,
    baseDuration: 0.5,
  },
  {
    id: "lock",
    num: "18",
    name: "Lock",
    category: "Interface",
    fileName: "lock-icon",
    componentName: "LockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LockIcon,
    baseDuration: 0.5,
  },
  {
    id: "folder",
    num: "19",
    name: "Folder",
    category: "Development",
    fileName: "folder-icon",
    componentName: "FolderIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FolderIcon,
    baseDuration: 0.5,
  },
  {
    id: "arrow-up-right",
    num: "20",
    name: "Arrow Up Right",
    category: "Interface",
    fileName: "arrow-up-right-icon",
    componentName: "ArrowUpRightIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ArrowUpRightIcon,
    baseDuration: 0.45,
  },
  {
    id: "bookmark",
    num: "21",
    name: "Bookmark",
    category: "Interface",
    fileName: "bookmark-icon",
    componentName: "BookmarkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BookmarkIcon,
    baseDuration: 0.5,
  },
  {
    id: "wifi",
    num: "22",
    name: "Wifi",
    category: "Interface",
    fileName: "wifi-icon",
    componentName: "WifiIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WifiIcon,
    baseDuration: 0.55,
  },
  {
    id: "fire",
    num: "23",
    name: "Fire",
    category: "Essentials",
    fileName: "fire-icon",
    componentName: "FireIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FireIcon,
    baseDuration: 0.55,
  },
  {
    id: "trash",
    num: "24",
    name: "Trash",
    category: "Interface",
    fileName: "trash-icon",
    componentName: "TrashIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TrashIcon,
    baseDuration: 0.5,
  },
  {
    id: "pencil",
    num: "25",
    name: "Pencil",
    category: "Interface",
    fileName: "pencil-icon",
    componentName: "PencilIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PencilIcon,
    baseDuration: 0.5,
  },
  {
    id: "calendar",
    num: "26",
    name: "Calendar",
    category: "Essentials",
    fileName: "calendar-icon",
    componentName: "CalendarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CalendarIcon,
    baseDuration: 0.55,
  },
  {
    id: "clock",
    num: "27",
    name: "Clock",
    category: "Essentials",
    fileName: "clock-icon",
    componentName: "ClockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClockIcon,
    baseDuration: 0.6,
  },
  {
    id: "music",
    num: "28",
    name: "Music",
    category: "Media",
    fileName: "music-icon",
    componentName: "MusicIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MusicIcon,
    baseDuration: 0.55,
  },
  {
    id: "video",
    num: "29",
    name: "Video",
    category: "Media",
    fileName: "video-icon",
    componentName: "VideoIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: VideoIcon,
    baseDuration: 0.5,
  },
  {
    id: "user",
    num: "30",
    name: "User",
    category: "Interface",
    fileName: "user-icon",
    componentName: "UserIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UserIcon,
    baseDuration: 0.5,
  },
  {
    id: "settings",
    num: "31",
    name: "Settings",
    category: "Development",
    fileName: "settings-icon",
    componentName: "SettingsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SettingsIcon,
    baseDuration: 0.6,
  },
  {
    id: "mic",
    num: "32",
    name: "Mic",
    category: "Media",
    fileName: "mic-icon",
    componentName: "MicIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MicIcon,
    baseDuration: 0.55,
  },
  {
    id: "sun",
    num: "33",
    name: "Sun",
    category: "Essentials",
    fileName: "sun-icon",
    componentName: "SunIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SunIcon,
    baseDuration: 0.55,
  },
  {
    id: "cloud",
    num: "34",
    name: "Cloud",
    category: "Essentials",
    fileName: "cloud-icon",
    componentName: "CloudIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CloudIcon,
    baseDuration: 0.55,
  },
  {
    id: "map-pin",
    num: "35",
    name: "Map Pin",
    category: "Interface",
    fileName: "map-pin-icon",
    componentName: "MapPinIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MapPinIcon,
    baseDuration: 0.5,
  },
  {
    id: "flag",
    num: "36",
    name: "Flag",
    category: "Interface",
    fileName: "flag-icon",
    componentName: "FlagIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FlagIcon,
    baseDuration: 0.5,
  },
  {
    id: "image",
    num: "37",
    name: "Image",
    category: "Media",
    fileName: "image-icon",
    componentName: "ImageIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ImageIcon,
    baseDuration: 0.5,
  },
  {
    id: "headphones",
    num: "38",
    name: "Headphones",
    category: "Media",
    fileName: "headphones-icon",
    componentName: "HeadphonesIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HeadphonesIcon,
    baseDuration: 0.55,
  },
  {
    id: "volume",
    num: "39",
    name: "Volume",
    category: "Media",
    fileName: "volume-icon",
    componentName: "VolumeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: VolumeIcon,
    baseDuration: 0.55,
  },
  {
    id: "link",
    num: "40",
    name: "Link",
    category: "Interface",
    fileName: "link-icon",
    componentName: "LinkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LinkIcon,
    baseDuration: 0.5,
  },
  {
    id: "copy",
    num: "41",
    name: "Copy",
    category: "Interface",
    fileName: "copy-icon",
    componentName: "CopyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CopyIcon,
    baseDuration: 0.5,
  },
  {
    id: "share",
    num: "42",
    name: "Share",
    category: "Interface",
    fileName: "share-icon",
    componentName: "ShareIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShareIcon,
    baseDuration: 0.5,
  },
  {
    id: "filter",
    num: "43",
    name: "Filter",
    category: "Development",
    fileName: "filter-icon",
    componentName: "FilterIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FilterIcon,
    baseDuration: 0.5,
  },
  {
    id: "refresh",
    num: "44",
    name: "Refresh",
    category: "Development",
    fileName: "refresh-icon",
    componentName: "RefreshIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RefreshIcon,
    baseDuration: 0.6,
  },
  {
    id: "battery",
    num: "45",
    name: "Battery",
    category: "Interface",
    fileName: "battery-icon",
    componentName: "BatteryIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BatteryIcon,
    baseDuration: 0.6,
  },
  {
    id: "power",
    num: "46",
    name: "Power",
    category: "Interface",
    fileName: "power-icon",
    componentName: "PowerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PowerIcon,
    baseDuration: 0.55,
  },
  {
    id: "trophy",
    num: "47",
    name: "Trophy",
    category: "Essentials",
    fileName: "trophy-icon",
    componentName: "TrophyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TrophyIcon,
    baseDuration: 0.55,
  },
  {
    id: "rocket",
    num: "48",
    name: "Rocket",
    category: "Development",
    fileName: "rocket-icon",
    componentName: "RocketIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RocketIcon,
    baseDuration: 0.55,
  },
  {
    id: "gift",
    num: "49",
    name: "Gift",
    category: "Essentials",
    fileName: "gift-icon",
    componentName: "GiftIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GiftIcon,
    baseDuration: 0.55,
  },
  {
    id: "smile",
    num: "50",
    name: "Smile",
    category: "Interface",
    fileName: "smile-icon",
    componentName: "SmileIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SmileIcon,
    baseDuration: 0.55,
  },
  {
    id: "thumbs-up",
    num: "51",
    name: "Thumbs Up",
    category: "Interface",
    fileName: "thumbs-up-icon",
    componentName: "ThumbsUpIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ThumbsUpIcon,
    baseDuration: 0.5,
  },
  {
    id: "message-circle",
    num: "52",
    name: "Message",
    category: "Interface",
    fileName: "message-circle-icon",
    componentName: "MessageCircleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MessageCircleIcon,
    baseDuration: 0.5,
  },
  {
    id: "mail",
    num: "53",
    name: "Mail",
    category: "Interface",
    fileName: "mail-icon",
    componentName: "MailIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MailIcon,
    baseDuration: 0.5,
  },
  {
    id: "home",
    num: "54",
    name: "Home",
    category: "Interface",
    fileName: "home-icon",
    componentName: "HomeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HomeIcon,
    baseDuration: 0.5,
  },
  {
    id: "file",
    num: "55",
    name: "File",
    category: "Development",
    fileName: "file-icon",
    componentName: "FileIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FileIcon,
    baseDuration: 0.5,
  },
  {
    id: "git-branch",
    num: "56",
    name: "Git Branch",
    category: "Development",
    fileName: "git-branch-icon",
    componentName: "GitBranchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GitBranchIcon,
    baseDuration: 0.55,
  },
  {
    id: "database",
    num: "57",
    name: "Database",
    category: "Development",
    fileName: "database-icon",
    componentName: "DatabaseIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DatabaseIcon,
    baseDuration: 0.6,
  },
  {
    id: "layers",
    num: "58",
    name: "Layers",
    category: "Development",
    fileName: "layers-icon",
    componentName: "LayersIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LayersIcon,
    baseDuration: 0.55,
  },
  {
    id: "package",
    num: "59",
    name: "Package",
    category: "Development",
    fileName: "package-icon",
    componentName: "PackageIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PackageIcon,
    baseDuration: 0.55,
  },
  {
    id: "palette",
    num: "60",
    name: "Palette",
    category: "Media",
    fileName: "palette-icon",
    componentName: "PaletteIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaletteIcon,
    baseDuration: 0.55,
  },
  {
    id: "film",
    num: "61",
    name: "Film",
    category: "Media",
    fileName: "film-icon",
    componentName: "FilmIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FilmIcon,
    baseDuration: 0.5,
  },
  {
    id: "compass",
    num: "62",
    name: "Compass",
    category: "Essentials",
    fileName: "compass-icon",
    componentName: "CompassIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CompassIcon,
    baseDuration: 0.6,
  },
  {
    id: "leaf",
    num: "63",
    name: "Leaf",
    category: "Essentials",
    fileName: "leaf-icon",
    componentName: "LeafIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LeafIcon,
    baseDuration: 0.55,
  },
  {
    id: "shield",
    num: "64",
    name: "Shield",
    category: "Interface",
    fileName: "shield-icon",
    componentName: "ShieldIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShieldIcon,
    baseDuration: 0.55,
  },
  {
    id: "key",
    num: "65",
    name: "Key",
    category: "Interface",
    fileName: "key-icon",
    componentName: "KeyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: KeyIcon,
    baseDuration: 0.6,
  },
  {
    id: "tag",
    num: "66",
    name: "Tag",
    category: "Interface",
    fileName: "tag-icon",
    componentName: "TagIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TagIcon,
    baseDuration: 0.5,
  },
  {
    id: "inbox",
    num: "67",
    name: "Inbox",
    category: "Interface",
    fileName: "inbox-icon",
    componentName: "InboxIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: InboxIcon,
    baseDuration: 0.5,
  },
  {
    id: "clipboard",
    num: "68",
    name: "Clipboard",
    category: "Development",
    fileName: "clipboard-icon",
    componentName: "ClipboardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClipboardIcon,
    baseDuration: 0.5,
  },
  {
    id: "server",
    num: "69",
    name: "Server",
    category: "Development",
    fileName: "server-icon",
    componentName: "ServerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ServerIcon,
    baseDuration: 0.55,
  },
  {
    id: "bug",
    num: "70",
    name: "Bug",
    category: "Development",
    fileName: "bug-icon",
    componentName: "BugIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BugIcon,
    baseDuration: 0.55,
  },
  {
    id: "cpu",
    num: "71",
    name: "CPU",
    category: "Development",
    fileName: "cpu-icon",
    componentName: "CpuIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CpuIcon,
    baseDuration: 0.55,
  },
  {
    id: "hard-drive",
    num: "72",
    name: "Hard Drive",
    category: "Development",
    fileName: "hard-drive-icon",
    componentName: "HardDriveIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HardDriveIcon,
    baseDuration: 0.55,
  },
  {
    id: "monitor",
    num: "73",
    name: "Monitor",
    category: "Media",
    fileName: "monitor-icon",
    componentName: "MonitorIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MonitorIcon,
    baseDuration: 0.5,
  },
  {
    id: "award",
    num: "74",
    name: "Award",
    category: "Essentials",
    fileName: "award-icon",
    componentName: "AwardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AwardIcon,
    baseDuration: 0.55,
  },
  {
    id: "umbrella",
    num: "75",
    name: "Umbrella",
    category: "Essentials",
    fileName: "umbrella-icon",
    componentName: "UmbrellaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UmbrellaIcon,
    baseDuration: 0.55,
  },
  {
    id: "anchor",
    num: "76",
    name: "Anchor",
    category: "Essentials",
    fileName: "anchor-icon",
    componentName: "AnchorIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AnchorIcon,
    baseDuration: 0.6,
  },
  {
    id: "at-sign",
    num: "77",
    name: "At Sign",
    category: "Interface",
    fileName: "at-sign-icon",
    componentName: "AtSignIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AtSignIcon,
    baseDuration: 0.6,
  },
  {
    id: "hash",
    num: "78",
    name: "Hash",
    category: "Interface",
    fileName: "hash-icon",
    componentName: "HashIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HashIcon,
    baseDuration: 0.5,
  },
  {
    id: "scissors",
    num: "79",
    name: "Scissors",
    category: "Interface",
    fileName: "scissors-icon",
    componentName: "ScissorsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ScissorsIcon,
    baseDuration: 0.5,
  },
  {
    id: "crop",
    num: "80",
    name: "Crop",
    category: "Interface",
    fileName: "crop-icon",
    componentName: "CropIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CropIcon,
    baseDuration: 0.5,
  },
  {
    id: "sliders",
    num: "81",
    name: "Sliders",
    category: "Interface",
    fileName: "sliders-icon",
    componentName: "SlidersIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SlidersIcon,
    baseDuration: 0.55,
  },
  {
    id: "wrench",
    num: "82",
    name: "Wrench",
    category: "Development",
    fileName: "wrench-icon",
    componentName: "WrenchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WrenchIcon,
    baseDuration: 0.55,
  },
  {
    id: "paperclip",
    num: "83",
    name: "Paperclip",
    category: "Interface",
    fileName: "paperclip-icon",
    componentName: "PaperclipIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaperclipIcon,
    baseDuration: 0.5,
  },
  {
    id: "brush",
    num: "84",
    name: "Brush",
    category: "Media",
    fileName: "brush-icon",
    componentName: "BrushIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BrushIcon,
    baseDuration: 0.55,
  },
  {
    id: "radio",
    num: "85",
    name: "Radio",
    category: "Media",
    fileName: "radio-icon",
    componentName: "RadioIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RadioIcon,
    baseDuration: 0.55,
  },
  {
    id: "disc",
    num: "86",
    name: "Disc",
    category: "Media",
    fileName: "disc-icon",
    componentName: "DiscIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DiscIcon,
    baseDuration: 0.7,
  },
  {
    id: "navigation",
    num: "87",
    name: "Navigation",
    category: "Interface",
    fileName: "navigation-icon",
    componentName: "NavigationIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: NavigationIcon,
    baseDuration: 0.55,
  },
  {
    id: "hourglass",
    num: "88",
    name: "Hourglass",
    category: "Essentials",
    fileName: "hourglass-icon",
    componentName: "HourglassIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HourglassIcon,
    baseDuration: 0.7,
  },
  {
    id: "snowflake",
    num: "89",
    name: "Snowflake",
    category: "Essentials",
    fileName: "snowflake-icon",
    componentName: "SnowflakeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SnowflakeIcon,
    baseDuration: 0.7,
  },
  {
    id: "wind",
    num: "90",
    name: "Wind",
    category: "Essentials",
    fileName: "wind-icon",
    componentName: "WindIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WindIcon,
    baseDuration: 0.6,
  },
  {
    id: "droplet",
    num: "91",
    name: "Droplet",
    category: "Essentials",
    fileName: "droplet-icon",
    componentName: "DropletIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DropletIcon,
    baseDuration: 0.55,
  },
  {
    id: "percent",
    num: "92",
    name: "Percent",
    category: "Interface",
    fileName: "percent-icon",
    componentName: "PercentIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PercentIcon,
    baseDuration: 0.5,
  },
  {
    id: "aperture",
    num: "93",
    name: "Aperture",
    category: "Media",
    fileName: "aperture-icon",
    componentName: "ApertureIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ApertureIcon,
    baseDuration: 0.6,
  },
  {
    id: "chevron-down",
    num: "94",
    name: "Chevron Down",
    category: "Interface",
    fileName: "chevron-down-icon",
    componentName: "ChevronDownIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ChevronDownIcon,
    baseDuration: 0.5,
  },
  {
    id: "grid",
    num: "95",
    name: "Grid",
    category: "Interface",
    fileName: "grid-icon",
    componentName: "GridIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GridIcon,
    baseDuration: 0.5,
  },
  {
    id: "menu",
    num: "96",
    name: "Menu",
    category: "Interface",
    fileName: "menu-icon",
    componentName: "MenuIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MenuIcon,
    baseDuration: 0.5,
  },
  {
    id: "sunrise",
    num: "97",
    name: "Sunrise",
    category: "Essentials",
    fileName: "sunrise-icon",
    componentName: "SunriseIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SunriseIcon,
    baseDuration: 0.6,
  },
  {
    id: "cloud-rain",
    num: "98",
    name: "Cloud Rain",
    category: "Essentials",
    fileName: "cloud-rain-icon",
    componentName: "CloudRainIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CloudRainIcon,
    baseDuration: 0.55,
  },
  {
    id: "mountain",
    num: "99",
    name: "Mountain",
    category: "Essentials",
    fileName: "mountain-icon",
    componentName: "MountainIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MountainIcon,
    baseDuration: 0.6,
  },
  {
    id: "gamepad",
    num: "100",
    name: "Gamepad",
    category: "Media",
    fileName: "gamepad-icon",
    componentName: "GamepadIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GamepadIcon,
    baseDuration: 0.55,
  },
  {
    id: "feather",
    num: "101",
    name: "Feather",
    category: "Media",
    fileName: "feather-icon",
    componentName: "FeatherIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FeatherIcon,
    baseDuration: 0.55,
  },
  {
    id: "hammer",
    num: "102",
    name: "Hammer",
    category: "Development",
    fileName: "hammer-icon",
    componentName: "HammerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HammerIcon,
    baseDuration: 0.5,
  },
  {
    id: "ruler",
    num: "103",
    name: "Ruler",
    category: "Development",
    fileName: "ruler-icon",
    componentName: "RulerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RulerIcon,
    baseDuration: 0.55,
  },
  {
    id: "move",
    num: "104",
    name: "Move",
    category: "Interface",
    fileName: "move-icon",
    componentName: "MoveIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MoveIcon,
    baseDuration: 0.55,
  },
  {
    id: "maximize",
    num: "105",
    name: "Maximize",
    category: "Interface",
    fileName: "maximize-icon",
    componentName: "MaximizeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MaximizeIcon,
    baseDuration: 0.5,
  },
  {
    id: "activity",
    num: "106",
    name: "Activity",
    category: "Essentials",
    fileName: "activity-icon",
    componentName: "ActivityIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ActivityIcon,
    baseDuration: 0.6,
  },
  {
    id: "plug",
    num: "107",
    name: "Plug",
    category: "Essentials",
    fileName: "plug-icon",
    componentName: "PlugIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlugIcon,
    baseDuration: 0.55,
  },
  {
    id: "alarm-clock",
    num: "108",
    name: "Alarm Clock",
    category: "Essentials",
    fileName: "alarm-clock-icon",
    componentName: "AlarmClockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AlarmClockIcon,
    baseDuration: 0.5,
  },
  {
    id: "wallet",
    num: "109",
    name: "Wallet",
    category: "Essentials",
    fileName: "wallet-icon",
    componentName: "WalletIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WalletIcon,
    baseDuration: 0.55,
  },
  {
    id: "phone",
    num: "110",
    name: "Phone",
    category: "Essentials",
    fileName: "phone-icon",
    componentName: "PhoneIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PhoneIcon,
    baseDuration: 0.55,
  },
  {
    id: "plane",
    num: "111",
    name: "Plane",
    category: "Media",
    fileName: "plane-icon",
    componentName: "PlaneIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlaneIcon,
    baseDuration: 0.6,
  },
  {
    id: "ticket",
    num: "112",
    name: "Ticket",
    category: "Media",
    fileName: "ticket-icon",
    componentName: "TicketIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TicketIcon,
    baseDuration: 0.55,
  },
  {
    id: "atom",
    num: "113",
    name: "Atom",
    category: "Development",
    fileName: "atom-icon",
    componentName: "AtomIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AtomIcon,
    baseDuration: 0.7,
  },
  {
    id: "lightbulb",
    num: "114",
    name: "Lightbulb",
    category: "Essentials",
    fileName: "lightbulb-icon",
    componentName: "LightbulbIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LightbulbIcon,
    baseDuration: 0.55,
  },
  {
    id: "fingerprint",
    num: "115",
    name: "Fingerprint",
    category: "Development",
    fileName: "fingerprint-icon",
    componentName: "FingerprintIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FingerprintIcon,
    baseDuration: 0.7,
  },
  {
    id: "qr-code",
    num: "116",
    name: "QR Code",
    category: "Development",
    fileName: "qr-code-icon",
    componentName: "QrCodeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: QrCodeIcon,
    baseDuration: 0.5,
  },
  {
    id: "waves",
    num: "117",
    name: "Waves",
    category: "Essentials",
    fileName: "waves-icon",
    componentName: "WavesIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WavesIcon,
    baseDuration: 0.6,
  },
  {
    id: "cloud-lightning",
    num: "118",
    name: "Cloud Lightning",
    category: "Essentials",
    fileName: "cloud-lightning-icon",
    componentName: "CloudLightningIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CloudLightningIcon,
    baseDuration: 0.5,
  },
  {
    id: "puzzle",
    num: "119",
    name: "Puzzle",
    category: "Media",
    fileName: "puzzle-icon",
    componentName: "PuzzleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PuzzleIcon,
    baseDuration: 0.55,
  },
  {
    id: "truck",
    num: "120",
    name: "Truck",
    category: "Media",
    fileName: "truck-icon",
    componentName: "TruckIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TruckIcon,
    baseDuration: 0.6,
  },
  {
    id: "bike",
    num: "121",
    name: "Bike",
    category: "Media",
    fileName: "bike-icon",
    componentName: "BikeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BikeIcon,
    baseDuration: 0.6,
  },
  {
    id: "plus",
    num: "122",
    name: "Plus",
    category: "Interface",
    fileName: "plus-icon",
    componentName: "PlusIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlusIcon,
    baseDuration: 0.5,
  },
  {
    id: "circle",
    num: "123",
    name: "Circle",
    category: "Interface",
    fileName: "circle-icon",
    componentName: "CircleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CircleIcon,
    baseDuration: 0.6,
  },
  {
    id: "brain",
    num: "124",
    name: "Brain",
    category: "Development",
    fileName: "brain-icon",
    componentName: "BrainIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BrainIcon,
    baseDuration: 0.6,
  },
  {
    id: "bot",
    num: "125",
    name: "Bot",
    category: "Development",
    fileName: "bot-icon",
    componentName: "BotIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BotIcon,
    baseDuration: 0.55,
  },
  {
    id: "scan",
    num: "126",
    name: "Scan",
    category: "Interface",
    fileName: "scan-icon",
    componentName: "ScanIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ScanIcon,
    baseDuration: 0.6,
  },
  {
    id: "utensils",
    num: "127",
    name: "Utensils",
    category: "Essentials",
    fileName: "utensils-icon",
    componentName: "UtensilsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UtensilsIcon,
    baseDuration: 0.55,
  },
  {
    id: "tree-pine",
    num: "128",
    name: "Tree Pine",
    category: "Essentials",
    fileName: "tree-pine-icon",
    componentName: "TreePineIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TreePineIcon,
    baseDuration: 0.6,
  },
  {
    id: "ship",
    num: "129",
    name: "Ship",
    category: "Media",
    fileName: "ship-icon",
    componentName: "ShipIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShipIcon,
    baseDuration: 0.7,
  },
  {
    id: "cake",
    num: "130",
    name: "Cake",
    category: "Media",
    fileName: "cake-icon",
    componentName: "CakeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CakeIcon,
    baseDuration: 0.5,
  },
  {
    id: "ghost",
    num: "131",
    name: "Ghost",
    category: "Media",
    fileName: "ghost-icon",
    componentName: "GhostIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GhostIcon,
    baseDuration: 0.6,
  },
  {
    id: "minus",
    num: "132",
    name: "Minus",
    category: "Interface",
    fileName: "minus-icon",
    componentName: "MinusIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MinusIcon,
    baseDuration: 0.5,
  },
  {
    id: "triangle",
    num: "133",
    name: "Triangle",
    category: "Interface",
    fileName: "triangle-icon",
    componentName: "TriangleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TriangleIcon,
    baseDuration: 0.6,
  },
  {
    id: "square",
    num: "134",
    name: "Square",
    category: "Interface",
    fileName: "square-icon",
    componentName: "SquareIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SquareIcon,
    baseDuration: 0.55,
  },
  {
    id: "cookie",
    num: "135",
    name: "Cookie",
    category: "Essentials",
    fileName: "cookie-icon",
    componentName: "CookieIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CookieIcon,
    baseDuration: 0.7,
  },
  {
    id: "dumbbell",
    num: "136",
    name: "Dumbbell",
    category: "Essentials",
    fileName: "dumbbell-icon",
    componentName: "DumbbellIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DumbbellIcon,
    baseDuration: 0.55,
  },
  {
    id: "flower-2",
    num: "137",
    name: "Flower",
    category: "Essentials",
    fileName: "flower-2-icon",
    componentName: "Flower2Icon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: Flower2Icon,
    baseDuration: 0.7,
  },
  {
    id: "paint-bucket",
    num: "138",
    name: "Paint Bucket",
    category: "Media",
    fileName: "paint-bucket-icon",
    componentName: "PaintBucketIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaintBucketIcon,
    baseDuration: 0.6,
  },
  {
    id: "clapperboard",
    num: "139",
    name: "Clapperboard",
    category: "Media",
    fileName: "clapperboard-icon",
    componentName: "ClapperboardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClapperboardIcon,
    baseDuration: 0.5,
  },
  {
    id: "dice-5",
    num: "140",
    name: "Dice",
    category: "Media",
    fileName: "dice-5-icon",
    componentName: "Dice5Icon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: Dice5Icon,
    baseDuration: 0.7,
  },
  {
    id: "coins",
    num: "141",
    name: "Coins",
    category: "Essentials",
    fileName: "coins-icon",
    componentName: "CoinsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CoinsIcon,
    baseDuration: 0.55,
  },
  {
    id: "bluetooth",
    num: "142",
    name: "Bluetooth",
    category: "Interface",
    fileName: "bluetooth-icon",
    componentName: "BluetoothIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BluetoothIcon,
    baseDuration: 0.6,
  },
  {
    id: "microscope",
    num: "143",
    name: "Microscope",
    category: "Development",
    fileName: "microscope-icon",
    componentName: "MicroscopeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MicroscopeIcon,
    baseDuration: 0.55,
  },
];

export const CATEGORIES = [
  "All icons",
  ...Array.from(new Set(ICON_LIST.map((i) => i.category))),
];
