"use client";

import { CodeIcon } from "@/icons/code-icon";
import { HeartIcon } from "@/icons/heart-icon";
import { SparkleIcon } from "@/icons/sparkle-icon";
import { ZapIcon } from "@/icons/zap-icon";
import { BellIcon } from "@/icons/bell-icon";
import { SearchIcon } from "@/icons/search-icon";
import { DownloadIcon } from "@/icons/download-icon";
import { GlobeIcon } from "@/icons/globe-icon";
import { CameraIcon } from "@/icons/camera-icon";
import { MoonIcon } from "@/icons/moon-icon";
import { CheckIcon } from "@/icons/check-icon";
import { SendIcon } from "@/icons/send-icon";
import { TerminalIcon } from "@/icons/terminal-icon";
import { StarIcon } from "@/icons/star-icon";
import { EyeIcon } from "@/icons/eye-icon";
import { CoffeeIcon } from "@/icons/coffee-icon";
import { PlayIcon } from "@/icons/play-icon";
import { LockIcon } from "@/icons/lock-icon";
import { FolderIcon } from "@/icons/folder-icon";
import { ArrowUpRightIcon } from "@/icons/arrow-up-right-icon";
import { BookmarkIcon } from "@/icons/bookmark-icon";
import { WifiIcon } from "@/icons/wifi-icon";
import { FireIcon } from "@/icons/fire-icon";
import { TrashIcon } from "@/icons/trash-icon";
import { PencilIcon } from "@/icons/pencil-icon";
import { CalendarIcon } from "@/icons/calendar-icon";
import { ClockIcon } from "@/icons/clock-icon";
import { MusicIcon } from "@/icons/music-icon";
import { VideoIcon } from "@/icons/video-icon";
import { UserIcon } from "@/icons/user-icon";
import { SettingsIcon } from "@/icons/settings-icon";
import { MicIcon } from "@/icons/mic-icon";
import { SunIcon } from "@/icons/sun-icon";
import { CloudIcon } from "@/icons/cloud-icon";
import { MapPinIcon } from "@/icons/map-pin-icon";
import { FlagIcon } from "@/icons/flag-icon";
import { ImageIcon } from "@/icons/image-icon";
import { HeadphonesIcon } from "@/icons/headphones-icon";
import { VolumeIcon } from "@/icons/volume-icon";
import { LinkIcon } from "@/icons/link-icon";
import { CopyIcon } from "@/icons/copy-icon";
import { ShareIcon } from "@/icons/share-icon";
import { FilterIcon } from "@/icons/filter-icon";
import { RefreshIcon } from "@/icons/refresh-icon";
import { BatteryIcon } from "@/icons/battery-icon";
import { PowerIcon } from "@/icons/power-icon";
import { TrophyIcon } from "@/icons/trophy-icon";
import { RocketIcon } from "@/icons/rocket-icon";
import { GiftIcon } from "@/icons/gift-icon";
import { SmileIcon } from "@/icons/smile-icon";
import { ThumbsUpIcon } from "@/icons/thumbs-up-icon";
import { MessageCircleIcon } from "@/icons/message-circle-icon";
import { MailIcon } from "@/icons/mail-icon";
import { HomeIcon } from "@/icons/home-icon";
import { FileIcon } from "@/icons/file-icon";
import { GitBranchIcon } from "@/icons/git-branch-icon";
import { DatabaseIcon } from "@/icons/database-icon";
import { LayersIcon } from "@/icons/layers-icon";
import { PackageIcon } from "@/icons/package-icon";
import { PaletteIcon } from "@/icons/palette-icon";
import { FilmIcon } from "@/icons/film-icon";
import { CompassIcon } from "@/icons/compass-icon";
import { LeafIcon } from "@/icons/leaf-icon";
import { ShieldIcon } from "@/icons/shield-icon";
import { KeyIcon } from "@/icons/key-icon";
import { TagIcon } from "@/icons/tag-icon";
import { InboxIcon } from "@/icons/inbox-icon";
import { ClipboardIcon } from "@/icons/clipboard-icon";
import { ServerIcon } from "@/icons/server-icon";
import { BugIcon } from "@/icons/bug-icon";
import { CpuIcon } from "@/icons/cpu-icon";
import { HardDriveIcon } from "@/icons/hard-drive-icon";
import { MonitorIcon } from "@/icons/monitor-icon";
import { AwardIcon } from "@/icons/award-icon";
import { UmbrellaIcon } from "@/icons/umbrella-icon";
import { AnchorIcon } from "@/icons/anchor-icon";
import { AtSignIcon } from "@/icons/at-sign-icon";
import { HashIcon } from "@/icons/hash-icon";
import { ScissorsIcon } from "@/icons/scissors-icon";
import { CropIcon } from "@/icons/crop-icon";
import { SlidersIcon } from "@/icons/sliders-icon";
import { WrenchIcon } from "@/icons/wrench-icon";
import { PaperclipIcon } from "@/icons/paperclip-icon";
import { BrushIcon } from "@/icons/brush-icon";
import { RadioIcon } from "@/icons/radio-icon";
import { DiscIcon } from "@/icons/disc-icon";
import { NavigationIcon } from "@/icons/navigation-icon";
import { HourglassIcon } from "@/icons/hourglass-icon";
import { SnowflakeIcon } from "@/icons/snowflake-icon";
import { WindIcon } from "@/icons/wind-icon";
import { DropletIcon } from "@/icons/droplet-icon";
import { PercentIcon } from "@/icons/percent-icon";
import { ApertureIcon } from "@/icons/aperture-icon";
import { ChevronDownIcon } from "@/icons/chevron-down-icon";
import { GridIcon } from "@/icons/grid-icon";
import { MenuIcon } from "@/icons/menu-icon";
import { SunriseIcon } from "@/icons/sunrise-icon";
import { CloudRainIcon } from "@/icons/cloud-rain-icon";
import { MountainIcon } from "@/icons/mountain-icon";
import { GamepadIcon } from "@/icons/gamepad-icon";
import { FeatherIcon } from "@/icons/feather-icon";
import { HammerIcon } from "@/icons/hammer-icon";
import { RulerIcon } from "@/icons/ruler-icon";
import { MoveIcon } from "@/icons/move-icon";
import { MaximizeIcon } from "@/icons/maximize-icon";
import { ActivityIcon } from "@/icons/activity-icon";
import { PlugIcon } from "@/icons/plug-icon";
import { AlarmClockIcon } from "@/icons/alarm-clock-icon";
import { WalletIcon } from "@/icons/wallet-icon";
import { PhoneIcon } from "@/icons/phone-icon";
import { PlaneIcon } from "@/icons/plane-icon";
import { TicketIcon } from "@/icons/ticket-icon";
import { AtomIcon } from "@/icons/atom-icon";
import { LightbulbIcon } from "@/icons/lightbulb-icon";
import { FingerprintIcon } from "@/icons/fingerprint-icon";
import { QrCodeIcon } from "@/icons/qr-code-icon";
import { WavesIcon } from "@/icons/waves-icon";
import { CloudLightningIcon } from "@/icons/cloud-lightning-icon";
import { PuzzleIcon } from "@/icons/puzzle-icon";
import { TruckIcon } from "@/icons/truck-icon";
import { BikeIcon } from "@/icons/bike-icon";
import { PlusIcon } from "@/icons/plus-icon";
import { CircleIcon } from "@/icons/circle-icon";
import { BrainIcon } from "@/icons/brain-icon";
import { BotIcon } from "@/icons/bot-icon";
import { ScanIcon } from "@/icons/scan-icon";
import { UtensilsIcon } from "@/icons/utensils-icon";
import { TreePineIcon } from "@/icons/tree-pine-icon";
import { ShipIcon } from "@/icons/ship-icon";
import { CakeIcon } from "@/icons/cake-icon";
import { GhostIcon } from "@/icons/ghost-icon";
import { MinusIcon } from "@/icons/minus-icon";
import { TriangleIcon } from "@/icons/triangle-icon";
import { SquareIcon } from "@/icons/square-icon";
import { CookieIcon } from "@/icons/cookie-icon";
import { DumbbellIcon } from "@/icons/dumbbell-icon";
import { Flower2Icon } from "@/icons/flower-2-icon";
import { PaintBucketIcon } from "@/icons/paint-bucket-icon";
import { ClapperboardIcon } from "@/icons/clapperboard-icon";
import { Dice5Icon } from "@/icons/dice-5-icon";
import { CoinsIcon } from "@/icons/coins-icon";
import { BluetoothIcon } from "@/icons/bluetooth-icon";
import { MicroscopeIcon } from "@/icons/microscope-icon";
import { SirenIcon } from "@/icons/siren-icon";
import { FlaskConicalIcon } from "@/icons/flask-conical-icon";
import { GemIcon } from "@/icons/gem-icon";
import { SwordsIcon } from "@/icons/swords-icon";
import { PopcornIcon } from "@/icons/popcorn-icon";
import { BookOpenIcon } from "@/icons/book-open-icon";
import { MagnetIcon } from "@/icons/magnet-icon";
import { PartyPopperIcon } from "@/icons/party-popper-icon";
import { HardHatIcon } from "@/icons/hard-hat-icon";
import { GuitarIcon } from "@/icons/guitar-icon";
import { FanIcon } from "@/icons/fan-icon";
import { SailboatIcon } from "@/icons/sailboat-icon";
import { WashingMachineIcon } from "@/icons/washing-machine-icon";
import { PianoIcon } from "@/icons/piano-icon";
import { BracesIcon } from "@/icons/braces-icon";
import { FlashlightIcon } from "@/icons/flashlight-icon";
import { TentIcon } from "@/icons/tent-icon";
import { PillIcon } from "@/icons/pill-icon";
import { DramaIcon } from "@/icons/drama-icon";
import { WaypointsIcon } from "@/icons/waypoints-icon";
import { LandmarkIcon } from "@/icons/landmark-icon";
import { PodcastIcon } from "@/icons/podcast-icon";
import { StickyNoteIcon } from "@/icons/sticky-note-icon";
import { DrumIcon } from "@/icons/drum-icon";
import { ScrollIcon } from "@/icons/scroll-icon";
import { SproutIcon } from "@/icons/sprout-icon";
import { BinaryIcon } from "@/icons/binary-icon";
import { CarrotIcon } from "@/icons/carrot-icon";
import { CrosshairIcon } from "@/icons/crosshair-icon";
import { BlocksIcon } from "@/icons/blocks-icon";
import { SatelliteIcon } from "@/icons/satellite-icon";
import { BackpackIcon } from "@/icons/backpack-icon";
import { RabbitIcon } from "@/icons/rabbit-icon";
import { SandwichIcon } from "@/icons/sandwich-icon";
import { BoneIcon } from "@/icons/bone-icon";
import { TelescopeIcon } from "@/icons/telescope-icon";
import { SkullIcon } from "@/icons/skull-icon";
import { AnvilIcon } from "@/icons/anvil-icon";
import { MergeIcon } from "@/icons/merge-icon";
import { HandshakeIcon } from "@/icons/handshake-icon";
import { BananaIcon } from "@/icons/banana-icon";
import { MilkIcon } from "@/icons/milk-icon";
import { CupSodaIcon } from "@/icons/cup-soda-icon";
import { PizzaIcon } from "@/icons/pizza-icon";
import { PickaxeIcon } from "@/icons/pickaxe-icon";
import { RadioTowerIcon } from "@/icons/radio-tower-icon";
import { WatchIcon } from "@/icons/watch-icon";
import { CitrusIcon } from "@/icons/citrus-icon";
import { NotebookIcon } from "@/icons/notebook-icon";
import { BirdIcon } from "@/icons/bird-icon";
import { PaintbrushIcon } from "@/icons/paintbrush-icon";
import { MegaphoneIcon } from "@/icons/megaphone-icon";
import { ArchiveIcon } from "@/icons/archive-icon";
import { SyringeIcon } from "@/icons/syringe-icon";
import { BombIcon } from "@/icons/bomb-icon";
import { ShellIcon } from "@/icons/shell-icon";
import { InfinityIcon } from "@/icons/infinity-icon";
import { CarIcon } from "@/icons/car-icon";
import { ShuffleIcon } from "@/icons/shuffle-icon";
import { CookingPotIcon } from "@/icons/cooking-pot-icon";
import { BoxIcon } from "@/icons/box-icon";
import { FishIcon } from "@/icons/fish-icon";
import { DnaIcon } from "@/icons/dna-icon";
import { HighlighterIcon } from "@/icons/highlighter-icon";
import { EraserIcon } from "@/icons/eraser-icon";
import { TreeDeciduousIcon } from "@/icons/tree-deciduous-icon";
import { OrbitIcon } from "@/icons/orbit-icon";
import { GitCommitIcon } from "@/icons/git-commit-icon";
import { ShapesIcon } from "@/icons/shapes-icon";
import { SofaIcon } from "@/icons/sofa-icon";
import { BedIcon } from "@/icons/bed-icon";
import { DoorOpenIcon } from "@/icons/door-open-icon";
import { RecycleIcon } from "@/icons/recycle-icon";
import { GrapeIcon } from "@/icons/grape-icon";
import { AppleIcon } from "@/icons/apple-icon";
import { PenIcon } from "@/icons/pen-icon";
import { StampIcon } from "@/icons/stamp-icon";
import { ArmchairIcon } from "@/icons/armchair-icon";
import { LayoutDashboardIcon } from "@/icons/layout-dashboard-icon";
import { SignalIcon } from "@/icons/signal-icon";
import { StethoscopeIcon } from "@/icons/stethoscope-icon";
import { HeartPulseIcon } from "@/icons/heart-pulse-icon";
import { ThermometerIcon } from "@/icons/thermometer-icon";
import { EarIcon } from "@/icons/ear-icon";
import { BathIcon } from "@/icons/bath-icon";
import { TimerIcon } from "@/icons/timer-icon";
import { ScaleIcon } from "@/icons/scale-icon";
import { CandyIcon } from "@/icons/candy-icon";
import { CroissantIcon } from "@/icons/croissant-icon";
import { UtensilsCrossedIcon } from "@/icons/utensils-crossed-icon";

export type IconConfig = {
  color: string;
  speed: number;
  size: number;
};

export type LibraryIcon = {
  id: string;
  num: string;
  name: string;
  category: string;
  fileName: string;
  componentName: string;
  defaultConfig: IconConfig;
  Component: (props: {
    size?: number;
    className?: string;
    duration?: number;
  }) => React.ReactElement;
  baseDuration: number;
};

export const ICON_LIST: LibraryIcon[] = [
  {
    id: "sparkle",
    num: "01",
    name: "Sparkles",
    category: "Essentials",
    fileName: "sparkle-icon",
    componentName: "SparkleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SparkleIcon,
    baseDuration: 0.5,
  },
  {
    id: "heart",
    num: "02",
    name: "Heart",
    category: "Essentials",
    fileName: "heart-icon",
    componentName: "HeartIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HeartIcon,
    baseDuration: 0.55,
  },
  {
    id: "code",
    num: "03",
    name: "Code",
    category: "Development",
    fileName: "code-icon",
    componentName: "CodeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CodeIcon,
    baseDuration: 0.4,
  },
  {
    id: "zap",
    num: "04",
    name: "Zap",
    category: "Essentials",
    fileName: "zap-icon",
    componentName: "ZapIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ZapIcon,
    baseDuration: 0.45,
  },
  {
    id: "check",
    num: "05",
    name: "Check",
    category: "Essentials",
    fileName: "check-icon",
    componentName: "CheckIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CheckIcon,
    baseDuration: 0.45,
  },
  {
    id: "bell",
    num: "06",
    name: "Bell",
    category: "Interface",
    fileName: "bell-icon",
    componentName: "BellIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BellIcon,
    baseDuration: 0.55,
  },
  {
    id: "search",
    num: "07",
    name: "Search",
    category: "Interface",
    fileName: "search-icon",
    componentName: "SearchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SearchIcon,
    baseDuration: 0.5,
  },
  {
    id: "download",
    num: "08",
    name: "Download",
    category: "Interface",
    fileName: "download-icon",
    componentName: "DownloadIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DownloadIcon,
    baseDuration: 0.5,
  },
  {
    id: "globe",
    num: "09",
    name: "Globe",
    category: "Interface",
    fileName: "globe-icon",
    componentName: "GlobeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GlobeIcon,
    baseDuration: 0.6,
  },
  {
    id: "moon",
    num: "10",
    name: "Moon",
    category: "Interface",
    fileName: "moon-icon",
    componentName: "MoonIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MoonIcon,
    baseDuration: 0.55,
  },
  {
    id: "send",
    num: "11",
    name: "Send",
    category: "Interface",
    fileName: "send-icon",
    componentName: "SendIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SendIcon,
    baseDuration: 0.5,
  },
  {
    id: "camera",
    num: "12",
    name: "Camera",
    category: "Media",
    fileName: "camera-icon",
    componentName: "CameraIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CameraIcon,
    baseDuration: 0.5,
  },
  {
    id: "terminal",
    num: "13",
    name: "Terminal",
    category: "Development",
    fileName: "terminal-icon",
    componentName: "TerminalIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TerminalIcon,
    baseDuration: 0.5,
  },
  {
    id: "star",
    num: "14",
    name: "Star",
    category: "Essentials",
    fileName: "star-icon",
    componentName: "StarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: StarIcon,
    baseDuration: 0.5,
  },
  {
    id: "eye",
    num: "15",
    name: "Eye",
    category: "Interface",
    fileName: "eye-icon",
    componentName: "EyeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: EyeIcon,
    baseDuration: 0.55,
  },
  {
    id: "coffee",
    num: "16",
    name: "Coffee",
    category: "Essentials",
    fileName: "coffee-icon",
    componentName: "CoffeeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CoffeeIcon,
    baseDuration: 0.6,
  },
  {
    id: "play",
    num: "17",
    name: "Play",
    category: "Media",
    fileName: "play-icon",
    componentName: "PlayIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlayIcon,
    baseDuration: 0.5,
  },
  {
    id: "lock",
    num: "18",
    name: "Lock",
    category: "Interface",
    fileName: "lock-icon",
    componentName: "LockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LockIcon,
    baseDuration: 0.5,
  },
  {
    id: "folder",
    num: "19",
    name: "Folder",
    category: "Development",
    fileName: "folder-icon",
    componentName: "FolderIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FolderIcon,
    baseDuration: 0.5,
  },
  {
    id: "arrow-up-right",
    num: "20",
    name: "Arrow Up Right",
    category: "Interface",
    fileName: "arrow-up-right-icon",
    componentName: "ArrowUpRightIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ArrowUpRightIcon,
    baseDuration: 0.45,
  },
  {
    id: "bookmark",
    num: "21",
    name: "Bookmark",
    category: "Interface",
    fileName: "bookmark-icon",
    componentName: "BookmarkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BookmarkIcon,
    baseDuration: 0.5,
  },
  {
    id: "wifi",
    num: "22",
    name: "Wifi",
    category: "Interface",
    fileName: "wifi-icon",
    componentName: "WifiIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WifiIcon,
    baseDuration: 0.55,
  },
  {
    id: "fire",
    num: "23",
    name: "Fire",
    category: "Essentials",
    fileName: "fire-icon",
    componentName: "FireIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FireIcon,
    baseDuration: 0.55,
  },
  {
    id: "trash",
    num: "24",
    name: "Trash",
    category: "Interface",
    fileName: "trash-icon",
    componentName: "TrashIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TrashIcon,
    baseDuration: 0.5,
  },
  {
    id: "pencil",
    num: "25",
    name: "Pencil",
    category: "Interface",
    fileName: "pencil-icon",
    componentName: "PencilIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PencilIcon,
    baseDuration: 0.5,
  },
  {
    id: "calendar",
    num: "26",
    name: "Calendar",
    category: "Essentials",
    fileName: "calendar-icon",
    componentName: "CalendarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CalendarIcon,
    baseDuration: 0.55,
  },
  {
    id: "clock",
    num: "27",
    name: "Clock",
    category: "Essentials",
    fileName: "clock-icon",
    componentName: "ClockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClockIcon,
    baseDuration: 0.6,
  },
  {
    id: "music",
    num: "28",
    name: "Music",
    category: "Media",
    fileName: "music-icon",
    componentName: "MusicIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MusicIcon,
    baseDuration: 0.55,
  },
  {
    id: "video",
    num: "29",
    name: "Video",
    category: "Media",
    fileName: "video-icon",
    componentName: "VideoIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: VideoIcon,
    baseDuration: 0.5,
  },
  {
    id: "user",
    num: "30",
    name: "User",
    category: "Interface",
    fileName: "user-icon",
    componentName: "UserIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UserIcon,
    baseDuration: 0.5,
  },
  {
    id: "settings",
    num: "31",
    name: "Settings",
    category: "Development",
    fileName: "settings-icon",
    componentName: "SettingsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SettingsIcon,
    baseDuration: 0.6,
  },
  {
    id: "mic",
    num: "32",
    name: "Mic",
    category: "Media",
    fileName: "mic-icon",
    componentName: "MicIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MicIcon,
    baseDuration: 0.55,
  },
  {
    id: "sun",
    num: "33",
    name: "Sun",
    category: "Essentials",
    fileName: "sun-icon",
    componentName: "SunIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SunIcon,
    baseDuration: 0.55,
  },
  {
    id: "cloud",
    num: "34",
    name: "Cloud",
    category: "Essentials",
    fileName: "cloud-icon",
    componentName: "CloudIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CloudIcon,
    baseDuration: 0.55,
  },
  {
    id: "map-pin",
    num: "35",
    name: "Map Pin",
    category: "Interface",
    fileName: "map-pin-icon",
    componentName: "MapPinIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MapPinIcon,
    baseDuration: 0.5,
  },
  {
    id: "flag",
    num: "36",
    name: "Flag",
    category: "Interface",
    fileName: "flag-icon",
    componentName: "FlagIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FlagIcon,
    baseDuration: 0.5,
  },
  {
    id: "image",
    num: "37",
    name: "Image",
    category: "Media",
    fileName: "image-icon",
    componentName: "ImageIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ImageIcon,
    baseDuration: 0.5,
  },
  {
    id: "headphones",
    num: "38",
    name: "Headphones",
    category: "Media",
    fileName: "headphones-icon",
    componentName: "HeadphonesIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HeadphonesIcon,
    baseDuration: 0.55,
  },
  {
    id: "volume",
    num: "39",
    name: "Volume",
    category: "Media",
    fileName: "volume-icon",
    componentName: "VolumeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: VolumeIcon,
    baseDuration: 0.55,
  },
  {
    id: "link",
    num: "40",
    name: "Link",
    category: "Interface",
    fileName: "link-icon",
    componentName: "LinkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LinkIcon,
    baseDuration: 0.5,
  },
  {
    id: "copy",
    num: "41",
    name: "Copy",
    category: "Interface",
    fileName: "copy-icon",
    componentName: "CopyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CopyIcon,
    baseDuration: 0.5,
  },
  {
    id: "share",
    num: "42",
    name: "Share",
    category: "Interface",
    fileName: "share-icon",
    componentName: "ShareIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShareIcon,
    baseDuration: 0.5,
  },
  {
    id: "filter",
    num: "43",
    name: "Filter",
    category: "Development",
    fileName: "filter-icon",
    componentName: "FilterIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FilterIcon,
    baseDuration: 0.5,
  },
  {
    id: "refresh",
    num: "44",
    name: "Refresh",
    category: "Development",
    fileName: "refresh-icon",
    componentName: "RefreshIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RefreshIcon,
    baseDuration: 0.6,
  },
  {
    id: "battery",
    num: "45",
    name: "Battery",
    category: "Interface",
    fileName: "battery-icon",
    componentName: "BatteryIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BatteryIcon,
    baseDuration: 0.6,
  },
  {
    id: "power",
    num: "46",
    name: "Power",
    category: "Interface",
    fileName: "power-icon",
    componentName: "PowerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PowerIcon,
    baseDuration: 0.55,
  },
  {
    id: "trophy",
    num: "47",
    name: "Trophy",
    category: "Essentials",
    fileName: "trophy-icon",
    componentName: "TrophyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TrophyIcon,
    baseDuration: 0.55,
  },
  {
    id: "rocket",
    num: "48",
    name: "Rocket",
    category: "Development",
    fileName: "rocket-icon",
    componentName: "RocketIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RocketIcon,
    baseDuration: 0.55,
  },
  {
    id: "gift",
    num: "49",
    name: "Gift",
    category: "Essentials",
    fileName: "gift-icon",
    componentName: "GiftIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GiftIcon,
    baseDuration: 0.55,
  },
  {
    id: "smile",
    num: "50",
    name: "Smile",
    category: "Interface",
    fileName: "smile-icon",
    componentName: "SmileIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SmileIcon,
    baseDuration: 0.55,
  },
  {
    id: "thumbs-up",
    num: "51",
    name: "Thumbs Up",
    category: "Interface",
    fileName: "thumbs-up-icon",
    componentName: "ThumbsUpIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ThumbsUpIcon,
    baseDuration: 0.5,
  },
  {
    id: "message-circle",
    num: "52",
    name: "Message",
    category: "Interface",
    fileName: "message-circle-icon",
    componentName: "MessageCircleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MessageCircleIcon,
    baseDuration: 0.5,
  },
  {
    id: "mail",
    num: "53",
    name: "Mail",
    category: "Interface",
    fileName: "mail-icon",
    componentName: "MailIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MailIcon,
    baseDuration: 0.5,
  },
  {
    id: "home",
    num: "54",
    name: "Home",
    category: "Interface",
    fileName: "home-icon",
    componentName: "HomeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HomeIcon,
    baseDuration: 0.5,
  },
  {
    id: "file",
    num: "55",
    name: "File",
    category: "Development",
    fileName: "file-icon",
    componentName: "FileIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FileIcon,
    baseDuration: 0.5,
  },
  {
    id: "git-branch",
    num: "56",
    name: "Git Branch",
    category: "Development",
    fileName: "git-branch-icon",
    componentName: "GitBranchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GitBranchIcon,
    baseDuration: 0.55,
  },
  {
    id: "database",
    num: "57",
    name: "Database",
    category: "Development",
    fileName: "database-icon",
    componentName: "DatabaseIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DatabaseIcon,
    baseDuration: 0.6,
  },
  {
    id: "layers",
    num: "58",
    name: "Layers",
    category: "Development",
    fileName: "layers-icon",
    componentName: "LayersIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LayersIcon,
    baseDuration: 0.55,
  },
  {
    id: "package",
    num: "59",
    name: "Package",
    category: "Development",
    fileName: "package-icon",
    componentName: "PackageIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PackageIcon,
    baseDuration: 0.55,
  },
  {
    id: "palette",
    num: "60",
    name: "Palette",
    category: "Media",
    fileName: "palette-icon",
    componentName: "PaletteIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaletteIcon,
    baseDuration: 0.55,
  },
  {
    id: "film",
    num: "61",
    name: "Film",
    category: "Media",
    fileName: "film-icon",
    componentName: "FilmIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FilmIcon,
    baseDuration: 0.5,
  },
  {
    id: "compass",
    num: "62",
    name: "Compass",
    category: "Essentials",
    fileName: "compass-icon",
    componentName: "CompassIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CompassIcon,
    baseDuration: 0.6,
  },
  {
    id: "leaf",
    num: "63",
    name: "Leaf",
    category: "Essentials",
    fileName: "leaf-icon",
    componentName: "LeafIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LeafIcon,
    baseDuration: 0.55,
  },
  {
    id: "shield",
    num: "64",
    name: "Shield",
    category: "Interface",
    fileName: "shield-icon",
    componentName: "ShieldIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShieldIcon,
    baseDuration: 0.55,
  },
  {
    id: "key",
    num: "65",
    name: "Key",
    category: "Interface",
    fileName: "key-icon",
    componentName: "KeyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: KeyIcon,
    baseDuration: 0.6,
  },
  {
    id: "tag",
    num: "66",
    name: "Tag",
    category: "Interface",
    fileName: "tag-icon",
    componentName: "TagIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TagIcon,
    baseDuration: 0.5,
  },
  {
    id: "inbox",
    num: "67",
    name: "Inbox",
    category: "Interface",
    fileName: "inbox-icon",
    componentName: "InboxIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: InboxIcon,
    baseDuration: 0.5,
  },
  {
    id: "clipboard",
    num: "68",
    name: "Clipboard",
    category: "Development",
    fileName: "clipboard-icon",
    componentName: "ClipboardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClipboardIcon,
    baseDuration: 0.5,
  },
  {
    id: "server",
    num: "69",
    name: "Server",
    category: "Development",
    fileName: "server-icon",
    componentName: "ServerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ServerIcon,
    baseDuration: 0.55,
  },
  {
    id: "bug",
    num: "70",
    name: "Bug",
    category: "Development",
    fileName: "bug-icon",
    componentName: "BugIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BugIcon,
    baseDuration: 0.55,
  },
  {
    id: "cpu",
    num: "71",
    name: "CPU",
    category: "Development",
    fileName: "cpu-icon",
    componentName: "CpuIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CpuIcon,
    baseDuration: 0.55,
  },
  {
    id: "hard-drive",
    num: "72",
    name: "Hard Drive",
    category: "Development",
    fileName: "hard-drive-icon",
    componentName: "HardDriveIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HardDriveIcon,
    baseDuration: 0.55,
  },
  {
    id: "monitor",
    num: "73",
    name: "Monitor",
    category: "Media",
    fileName: "monitor-icon",
    componentName: "MonitorIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MonitorIcon,
    baseDuration: 0.5,
  },
  {
    id: "award",
    num: "74",
    name: "Award",
    category: "Essentials",
    fileName: "award-icon",
    componentName: "AwardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AwardIcon,
    baseDuration: 0.55,
  },
  {
    id: "umbrella",
    num: "75",
    name: "Umbrella",
    category: "Essentials",
    fileName: "umbrella-icon",
    componentName: "UmbrellaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UmbrellaIcon,
    baseDuration: 0.55,
  },
  {
    id: "anchor",
    num: "76",
    name: "Anchor",
    category: "Essentials",
    fileName: "anchor-icon",
    componentName: "AnchorIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AnchorIcon,
    baseDuration: 0.6,
  },
  {
    id: "at-sign",
    num: "77",
    name: "At Sign",
    category: "Interface",
    fileName: "at-sign-icon",
    componentName: "AtSignIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AtSignIcon,
    baseDuration: 0.6,
  },
  {
    id: "hash",
    num: "78",
    name: "Hash",
    category: "Interface",
    fileName: "hash-icon",
    componentName: "HashIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HashIcon,
    baseDuration: 0.5,
  },
  {
    id: "scissors",
    num: "79",
    name: "Scissors",
    category: "Interface",
    fileName: "scissors-icon",
    componentName: "ScissorsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ScissorsIcon,
    baseDuration: 0.5,
  },
  {
    id: "crop",
    num: "80",
    name: "Crop",
    category: "Interface",
    fileName: "crop-icon",
    componentName: "CropIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CropIcon,
    baseDuration: 0.5,
  },
  {
    id: "sliders",
    num: "81",
    name: "Sliders",
    category: "Interface",
    fileName: "sliders-icon",
    componentName: "SlidersIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SlidersIcon,
    baseDuration: 0.55,
  },
  {
    id: "wrench",
    num: "82",
    name: "Wrench",
    category: "Development",
    fileName: "wrench-icon",
    componentName: "WrenchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WrenchIcon,
    baseDuration: 0.55,
  },
  {
    id: "paperclip",
    num: "83",
    name: "Paperclip",
    category: "Interface",
    fileName: "paperclip-icon",
    componentName: "PaperclipIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaperclipIcon,
    baseDuration: 0.5,
  },
  {
    id: "brush",
    num: "84",
    name: "Brush",
    category: "Media",
    fileName: "brush-icon",
    componentName: "BrushIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BrushIcon,
    baseDuration: 0.55,
  },
  {
    id: "radio",
    num: "85",
    name: "Radio",
    category: "Media",
    fileName: "radio-icon",
    componentName: "RadioIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RadioIcon,
    baseDuration: 0.55,
  },
  {
    id: "disc",
    num: "86",
    name: "Disc",
    category: "Media",
    fileName: "disc-icon",
    componentName: "DiscIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DiscIcon,
    baseDuration: 0.7,
  },
  {
    id: "navigation",
    num: "87",
    name: "Navigation",
    category: "Interface",
    fileName: "navigation-icon",
    componentName: "NavigationIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: NavigationIcon,
    baseDuration: 0.55,
  },
  {
    id: "hourglass",
    num: "88",
    name: "Hourglass",
    category: "Essentials",
    fileName: "hourglass-icon",
    componentName: "HourglassIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HourglassIcon,
    baseDuration: 0.7,
  },
  {
    id: "snowflake",
    num: "89",
    name: "Snowflake",
    category: "Essentials",
    fileName: "snowflake-icon",
    componentName: "SnowflakeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SnowflakeIcon,
    baseDuration: 0.7,
  },
  {
    id: "wind",
    num: "90",
    name: "Wind",
    category: "Essentials",
    fileName: "wind-icon",
    componentName: "WindIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WindIcon,
    baseDuration: 0.6,
  },
  {
    id: "droplet",
    num: "91",
    name: "Droplet",
    category: "Essentials",
    fileName: "droplet-icon",
    componentName: "DropletIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DropletIcon,
    baseDuration: 0.55,
  },
  {
    id: "percent",
    num: "92",
    name: "Percent",
    category: "Interface",
    fileName: "percent-icon",
    componentName: "PercentIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PercentIcon,
    baseDuration: 0.5,
  },
  {
    id: "aperture",
    num: "93",
    name: "Aperture",
    category: "Media",
    fileName: "aperture-icon",
    componentName: "ApertureIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ApertureIcon,
    baseDuration: 0.6,
  },
  {
    id: "chevron-down",
    num: "94",
    name: "Chevron Down",
    category: "Interface",
    fileName: "chevron-down-icon",
    componentName: "ChevronDownIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ChevronDownIcon,
    baseDuration: 0.5,
  },
  {
    id: "grid",
    num: "95",
    name: "Grid",
    category: "Interface",
    fileName: "grid-icon",
    componentName: "GridIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GridIcon,
    baseDuration: 0.5,
  },
  {
    id: "menu",
    num: "96",
    name: "Menu",
    category: "Interface",
    fileName: "menu-icon",
    componentName: "MenuIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MenuIcon,
    baseDuration: 0.5,
  },
  {
    id: "sunrise",
    num: "97",
    name: "Sunrise",
    category: "Essentials",
    fileName: "sunrise-icon",
    componentName: "SunriseIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SunriseIcon,
    baseDuration: 0.6,
  },
  {
    id: "cloud-rain",
    num: "98",
    name: "Cloud Rain",
    category: "Essentials",
    fileName: "cloud-rain-icon",
    componentName: "CloudRainIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CloudRainIcon,
    baseDuration: 0.55,
  },
  {
    id: "mountain",
    num: "99",
    name: "Mountain",
    category: "Essentials",
    fileName: "mountain-icon",
    componentName: "MountainIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MountainIcon,
    baseDuration: 0.6,
  },
  {
    id: "gamepad",
    num: "100",
    name: "Gamepad",
    category: "Media",
    fileName: "gamepad-icon",
    componentName: "GamepadIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GamepadIcon,
    baseDuration: 0.55,
  },
  {
    id: "feather",
    num: "101",
    name: "Feather",
    category: "Media",
    fileName: "feather-icon",
    componentName: "FeatherIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FeatherIcon,
    baseDuration: 0.55,
  },
  {
    id: "hammer",
    num: "102",
    name: "Hammer",
    category: "Development",
    fileName: "hammer-icon",
    componentName: "HammerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HammerIcon,
    baseDuration: 0.5,
  },
  {
    id: "ruler",
    num: "103",
    name: "Ruler",
    category: "Development",
    fileName: "ruler-icon",
    componentName: "RulerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RulerIcon,
    baseDuration: 0.55,
  },
  {
    id: "move",
    num: "104",
    name: "Move",
    category: "Interface",
    fileName: "move-icon",
    componentName: "MoveIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MoveIcon,
    baseDuration: 0.55,
  },
  {
    id: "maximize",
    num: "105",
    name: "Maximize",
    category: "Interface",
    fileName: "maximize-icon",
    componentName: "MaximizeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MaximizeIcon,
    baseDuration: 0.5,
  },
  {
    id: "activity",
    num: "106",
    name: "Activity",
    category: "Essentials",
    fileName: "activity-icon",
    componentName: "ActivityIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ActivityIcon,
    baseDuration: 0.6,
  },
  {
    id: "plug",
    num: "107",
    name: "Plug",
    category: "Essentials",
    fileName: "plug-icon",
    componentName: "PlugIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlugIcon,
    baseDuration: 0.55,
  },
  {
    id: "alarm-clock",
    num: "108",
    name: "Alarm Clock",
    category: "Essentials",
    fileName: "alarm-clock-icon",
    componentName: "AlarmClockIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AlarmClockIcon,
    baseDuration: 0.5,
  },
  {
    id: "wallet",
    num: "109",
    name: "Wallet",
    category: "Essentials",
    fileName: "wallet-icon",
    componentName: "WalletIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WalletIcon,
    baseDuration: 0.55,
  },
  {
    id: "phone",
    num: "110",
    name: "Phone",
    category: "Essentials",
    fileName: "phone-icon",
    componentName: "PhoneIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PhoneIcon,
    baseDuration: 0.55,
  },
  {
    id: "plane",
    num: "111",
    name: "Plane",
    category: "Media",
    fileName: "plane-icon",
    componentName: "PlaneIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlaneIcon,
    baseDuration: 0.6,
  },
  {
    id: "ticket",
    num: "112",
    name: "Ticket",
    category: "Media",
    fileName: "ticket-icon",
    componentName: "TicketIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TicketIcon,
    baseDuration: 0.55,
  },
  {
    id: "atom",
    num: "113",
    name: "Atom",
    category: "Development",
    fileName: "atom-icon",
    componentName: "AtomIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AtomIcon,
    baseDuration: 0.7,
  },
  {
    id: "lightbulb",
    num: "114",
    name: "Lightbulb",
    category: "Essentials",
    fileName: "lightbulb-icon",
    componentName: "LightbulbIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LightbulbIcon,
    baseDuration: 0.55,
  },
  {
    id: "fingerprint",
    num: "115",
    name: "Fingerprint",
    category: "Development",
    fileName: "fingerprint-icon",
    componentName: "FingerprintIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FingerprintIcon,
    baseDuration: 0.7,
  },
  {
    id: "qr-code",
    num: "116",
    name: "QR Code",
    category: "Development",
    fileName: "qr-code-icon",
    componentName: "QrCodeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: QrCodeIcon,
    baseDuration: 0.5,
  },
  {
    id: "waves",
    num: "117",
    name: "Waves",
    category: "Essentials",
    fileName: "waves-icon",
    componentName: "WavesIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WavesIcon,
    baseDuration: 0.6,
  },
  {
    id: "cloud-lightning",
    num: "118",
    name: "Cloud Lightning",
    category: "Essentials",
    fileName: "cloud-lightning-icon",
    componentName: "CloudLightningIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CloudLightningIcon,
    baseDuration: 0.5,
  },
  {
    id: "puzzle",
    num: "119",
    name: "Puzzle",
    category: "Media",
    fileName: "puzzle-icon",
    componentName: "PuzzleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PuzzleIcon,
    baseDuration: 0.55,
  },
  {
    id: "truck",
    num: "120",
    name: "Truck",
    category: "Media",
    fileName: "truck-icon",
    componentName: "TruckIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TruckIcon,
    baseDuration: 0.6,
  },
  {
    id: "bike",
    num: "121",
    name: "Bike",
    category: "Media",
    fileName: "bike-icon",
    componentName: "BikeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BikeIcon,
    baseDuration: 0.6,
  },
  {
    id: "plus",
    num: "122",
    name: "Plus",
    category: "Interface",
    fileName: "plus-icon",
    componentName: "PlusIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PlusIcon,
    baseDuration: 0.5,
  },
  {
    id: "circle",
    num: "123",
    name: "Circle",
    category: "Interface",
    fileName: "circle-icon",
    componentName: "CircleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CircleIcon,
    baseDuration: 0.6,
  },
  {
    id: "brain",
    num: "124",
    name: "Brain",
    category: "Development",
    fileName: "brain-icon",
    componentName: "BrainIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BrainIcon,
    baseDuration: 0.6,
  },
  {
    id: "bot",
    num: "125",
    name: "Bot",
    category: "Development",
    fileName: "bot-icon",
    componentName: "BotIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BotIcon,
    baseDuration: 0.55,
  },
  {
    id: "scan",
    num: "126",
    name: "Scan",
    category: "Interface",
    fileName: "scan-icon",
    componentName: "ScanIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ScanIcon,
    baseDuration: 0.6,
  },
  {
    id: "utensils",
    num: "127",
    name: "Utensils",
    category: "Essentials",
    fileName: "utensils-icon",
    componentName: "UtensilsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UtensilsIcon,
    baseDuration: 0.55,
  },
  {
    id: "tree-pine",
    num: "128",
    name: "Tree Pine",
    category: "Essentials",
    fileName: "tree-pine-icon",
    componentName: "TreePineIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TreePineIcon,
    baseDuration: 0.6,
  },
  {
    id: "ship",
    num: "129",
    name: "Ship",
    category: "Media",
    fileName: "ship-icon",
    componentName: "ShipIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShipIcon,
    baseDuration: 0.7,
  },
  {
    id: "cake",
    num: "130",
    name: "Cake",
    category: "Media",
    fileName: "cake-icon",
    componentName: "CakeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CakeIcon,
    baseDuration: 0.5,
  },
  {
    id: "ghost",
    num: "131",
    name: "Ghost",
    category: "Media",
    fileName: "ghost-icon",
    componentName: "GhostIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GhostIcon,
    baseDuration: 0.6,
  },
  {
    id: "minus",
    num: "132",
    name: "Minus",
    category: "Interface",
    fileName: "minus-icon",
    componentName: "MinusIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MinusIcon,
    baseDuration: 0.5,
  },
  {
    id: "triangle",
    num: "133",
    name: "Triangle",
    category: "Interface",
    fileName: "triangle-icon",
    componentName: "TriangleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TriangleIcon,
    baseDuration: 0.6,
  },
  {
    id: "square",
    num: "134",
    name: "Square",
    category: "Interface",
    fileName: "square-icon",
    componentName: "SquareIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SquareIcon,
    baseDuration: 0.55,
  },
  {
    id: "cookie",
    num: "135",
    name: "Cookie",
    category: "Essentials",
    fileName: "cookie-icon",
    componentName: "CookieIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CookieIcon,
    baseDuration: 0.7,
  },
  {
    id: "dumbbell",
    num: "136",
    name: "Dumbbell",
    category: "Essentials",
    fileName: "dumbbell-icon",
    componentName: "DumbbellIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DumbbellIcon,
    baseDuration: 0.55,
  },
  {
    id: "flower-2",
    num: "137",
    name: "Flower",
    category: "Essentials",
    fileName: "flower-2-icon",
    componentName: "Flower2Icon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: Flower2Icon,
    baseDuration: 0.7,
  },
  {
    id: "paint-bucket",
    num: "138",
    name: "Paint Bucket",
    category: "Media",
    fileName: "paint-bucket-icon",
    componentName: "PaintBucketIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaintBucketIcon,
    baseDuration: 0.6,
  },
  {
    id: "clapperboard",
    num: "139",
    name: "Clapperboard",
    category: "Media",
    fileName: "clapperboard-icon",
    componentName: "ClapperboardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ClapperboardIcon,
    baseDuration: 0.5,
  },
  {
    id: "dice-5",
    num: "140",
    name: "Dice",
    category: "Media",
    fileName: "dice-5-icon",
    componentName: "Dice5Icon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: Dice5Icon,
    baseDuration: 0.7,
  },
  {
    id: "coins",
    num: "141",
    name: "Coins",
    category: "Essentials",
    fileName: "coins-icon",
    componentName: "CoinsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CoinsIcon,
    baseDuration: 0.55,
  },
  {
    id: "bluetooth",
    num: "142",
    name: "Bluetooth",
    category: "Interface",
    fileName: "bluetooth-icon",
    componentName: "BluetoothIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BluetoothIcon,
    baseDuration: 0.6,
  },
  {
    id: "microscope",
    num: "143",
    name: "Microscope",
    category: "Development",
    fileName: "microscope-icon",
    componentName: "MicroscopeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MicroscopeIcon,
    baseDuration: 0.55,
  },
  {
    id: "siren",
    num: "144",
    name: "Siren",
    category: "Media",
    fileName: "siren-icon",
    componentName: "SirenIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SirenIcon,
    baseDuration: 0.55,
  },
  {
    id: "flask-conical",
    num: "145",
    name: "Flask",
    category: "Development",
    fileName: "flask-conical-icon",
    componentName: "FlaskConicalIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FlaskConicalIcon,
    baseDuration: 0.6,
  },
  {
    id: "gem",
    num: "146",
    name: "Gem",
    category: "Essentials",
    fileName: "gem-icon",
    componentName: "GemIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GemIcon,
    baseDuration: 0.6,
  },
  {
    id: "swords",
    num: "147",
    name: "Swords",
    category: "Media",
    fileName: "swords-icon",
    componentName: "SwordsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SwordsIcon,
    baseDuration: 0.5,
  },
  {
    id: "popcorn",
    num: "148",
    name: "Popcorn",
    category: "Media",
    fileName: "popcorn-icon",
    componentName: "PopcornIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PopcornIcon,
    baseDuration: 0.55,
  },
  {
    id: "book-open",
    num: "149",
    name: "Book Open",
    category: "Essentials",
    fileName: "book-open-icon",
    componentName: "BookOpenIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BookOpenIcon,
    baseDuration: 0.6,
  },
  {
    id: "magnet",
    num: "150",
    name: "Magnet",
    category: "Development",
    fileName: "magnet-icon",
    componentName: "MagnetIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MagnetIcon,
    baseDuration: 0.55,
  },
  {
    id: "party-popper",
    num: "151",
    name: "Party Popper",
    category: "Media",
    fileName: "party-popper-icon",
    componentName: "PartyPopperIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PartyPopperIcon,
    baseDuration: 0.6,
  },
  {
    id: "hard-hat",
    num: "152",
    name: "Hard Hat",
    category: "Essentials",
    fileName: "hard-hat-icon",
    componentName: "HardHatIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HardHatIcon,
    baseDuration: 0.55,
  },
  {
    id: "guitar",
    num: "153",
    name: "Guitar",
    category: "Media",
    fileName: "guitar-icon",
    componentName: "GuitarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GuitarIcon,
    baseDuration: 0.6,
  },
  {
    id: "fan",
    num: "154",
    name: "Fan",
    category: "Essentials",
    fileName: "fan-icon",
    componentName: "FanIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FanIcon,
    baseDuration: 1.2,
  },
  {
    id: "sailboat",
    num: "155",
    name: "Sailboat",
    category: "Media",
    fileName: "sailboat-icon",
    componentName: "SailboatIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SailboatIcon,
    baseDuration: 0.7,
  },
  {
    id: "washing-machine",
    num: "156",
    name: "Washing Machine",
    category: "Essentials",
    fileName: "washing-machine-icon",
    componentName: "WashingMachineIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WashingMachineIcon,
    baseDuration: 1,
  },
  {
    id: "piano",
    num: "157",
    name: "Piano",
    category: "Media",
    fileName: "piano-icon",
    componentName: "PianoIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PianoIcon,
    baseDuration: 0.55,
  },
  {
    id: "braces",
    num: "158",
    name: "Braces",
    category: "Development",
    fileName: "braces-icon",
    componentName: "BracesIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BracesIcon,
    baseDuration: 0.55,
  },
  {
    id: "flashlight",
    num: "159",
    name: "Flashlight",
    category: "Essentials",
    fileName: "flashlight-icon",
    componentName: "FlashlightIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FlashlightIcon,
    baseDuration: 0.55,
  },
  {
    id: "tent",
    num: "160",
    name: "Tent",
    category: "Essentials",
    fileName: "tent-icon",
    componentName: "TentIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TentIcon,
    baseDuration: 0.6,
  },
  {
    id: "pill",
    num: "161",
    name: "Pill",
    category: "Essentials",
    fileName: "pill-icon",
    componentName: "PillIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PillIcon,
    baseDuration: 0.7,
  },
  {
    id: "drama",
    num: "162",
    name: "Drama",
    category: "Media",
    fileName: "drama-icon",
    componentName: "DramaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DramaIcon,
    baseDuration: 0.6,
  },
  {
    id: "waypoints",
    num: "163",
    name: "Waypoints",
    category: "Development",
    fileName: "waypoints-icon",
    componentName: "WaypointsIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WaypointsIcon,
    baseDuration: 0.6,
  },
  {
    id: "landmark",
    num: "164",
    name: "Landmark",
    category: "Essentials",
    fileName: "landmark-icon",
    componentName: "LandmarkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LandmarkIcon,
    baseDuration: 0.55,
  },
  {
    id: "podcast",
    num: "165",
    name: "Podcast",
    category: "Media",
    fileName: "podcast-icon",
    componentName: "PodcastIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PodcastIcon,
    baseDuration: 0.6,
  },
  {
    id: "sticky-note",
    num: "166",
    name: "Sticky Note",
    category: "Interface",
    fileName: "sticky-note-icon",
    componentName: "StickyNoteIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: StickyNoteIcon,
    baseDuration: 0.55,
  },
  {
    id: "drum",
    num: "167",
    name: "Drum",
    category: "Media",
    fileName: "drum-icon",
    componentName: "DrumIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DrumIcon,
    baseDuration: 0.5,
  },
  {
    id: "scroll",
    num: "168",
    name: "Scroll",
    category: "Essentials",
    fileName: "scroll-icon",
    componentName: "ScrollIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ScrollIcon,
    baseDuration: 0.6,
  },
  {
    id: "sprout",
    num: "169",
    name: "Sprout",
    category: "Essentials",
    fileName: "sprout-icon",
    componentName: "SproutIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SproutIcon,
    baseDuration: 0.6,
  },
  {
    id: "binary",
    num: "170",
    name: "Binary",
    category: "Development",
    fileName: "binary-icon",
    componentName: "BinaryIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BinaryIcon,
    baseDuration: 0.5,
  },
  {
    id: "carrot",
    num: "171",
    name: "Carrot",
    category: "Essentials",
    fileName: "carrot-icon",
    componentName: "CarrotIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CarrotIcon,
    baseDuration: 0.55,
  },
  {
    id: "crosshair",
    num: "172",
    name: "Crosshair",
    category: "Interface",
    fileName: "crosshair-icon",
    componentName: "CrosshairIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CrosshairIcon,
    baseDuration: 0.55,
  },
  {
    id: "blocks",
    num: "173",
    name: "Blocks",
    category: "Development",
    fileName: "blocks-icon",
    componentName: "BlocksIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BlocksIcon,
    baseDuration: 0.55,
  },
  {
    id: "satellite",
    num: "174",
    name: "Satellite",
    category: "Development",
    fileName: "satellite-icon",
    componentName: "SatelliteIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SatelliteIcon,
    baseDuration: 0.6,
  },
  {
    id: "backpack",
    num: "175",
    name: "Backpack",
    category: "Essentials",
    fileName: "backpack-icon",
    componentName: "BackpackIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BackpackIcon,
    baseDuration: 0.55,
  },
  {
    id: "rabbit",
    num: "176",
    name: "Rabbit",
    category: "Media",
    fileName: "rabbit-icon",
    componentName: "RabbitIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RabbitIcon,
    baseDuration: 0.5,
  },
  {
    id: "sandwich",
    num: "177",
    name: "Sandwich",
    category: "Essentials",
    fileName: "sandwich-icon",
    componentName: "SandwichIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SandwichIcon,
    baseDuration: 0.55,
  },
  {
    id: "bone",
    num: "178",
    name: "Bone",
    category: "Essentials",
    fileName: "bone-icon",
    componentName: "BoneIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BoneIcon,
    baseDuration: 0.6,
  },
  {
    id: "telescope",
    num: "179",
    name: "Telescope",
    category: "Development",
    fileName: "telescope-icon",
    componentName: "TelescopeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TelescopeIcon,
    baseDuration: 0.6,
  },
  {
    id: "skull",
    num: "180",
    name: "Skull",
    category: "Media",
    fileName: "skull-icon",
    componentName: "SkullIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SkullIcon,
    baseDuration: 0.55,
  },
  {
    id: "anvil",
    num: "181",
    name: "Anvil",
    category: "Development",
    fileName: "anvil-icon",
    componentName: "AnvilIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AnvilIcon,
    baseDuration: 0.5,
  },
  {
    id: "merge",
    num: "182",
    name: "Merge",
    category: "Development",
    fileName: "merge-icon",
    componentName: "MergeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MergeIcon,
    baseDuration: 0.6,
  },
  {
    id: "handshake",
    num: "183",
    name: "Handshake",
    category: "Essentials",
    fileName: "handshake-icon",
    componentName: "HandshakeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HandshakeIcon,
    baseDuration: 0.55,
  },
  {
    id: "banana",
    num: "184",
    name: "Banana",
    category: "Essentials",
    fileName: "banana-icon",
    componentName: "BananaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BananaIcon,
    baseDuration: 0.6,
  },
  {
    id: "milk",
    num: "185",
    name: "Milk",
    category: "Essentials",
    fileName: "milk-icon",
    componentName: "MilkIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MilkIcon,
    baseDuration: 0.55,
  },
  {
    id: "cup-soda",
    num: "186",
    name: "Cup Soda",
    category: "Essentials",
    fileName: "cup-soda-icon",
    componentName: "CupSodaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CupSodaIcon,
    baseDuration: 0.6,
  },
  {
    id: "pizza",
    num: "187",
    name: "Pizza",
    category: "Essentials",
    fileName: "pizza-icon",
    componentName: "PizzaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PizzaIcon,
    baseDuration: 0.55,
  },
  {
    id: "pickaxe",
    num: "188",
    name: "Pickaxe",
    category: "Development",
    fileName: "pickaxe-icon",
    componentName: "PickaxeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PickaxeIcon,
    baseDuration: 0.5,
  },
  {
    id: "radio-tower",
    num: "189",
    name: "Radio Tower",
    category: "Media",
    fileName: "radio-tower-icon",
    componentName: "RadioTowerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RadioTowerIcon,
    baseDuration: 0.6,
  },
  {
    id: "watch",
    num: "190",
    name: "Watch",
    category: "Interface",
    fileName: "watch-icon",
    componentName: "WatchIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: WatchIcon,
    baseDuration: 0.5,
  },
  {
    id: "citrus",
    num: "191",
    name: "Citrus",
    category: "Essentials",
    fileName: "citrus-icon",
    componentName: "CitrusIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CitrusIcon,
    baseDuration: 0.6,
  },
  {
    id: "notebook",
    num: "192",
    name: "Notebook",
    category: "Interface",
    fileName: "notebook-icon",
    componentName: "NotebookIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: NotebookIcon,
    baseDuration: 0.55,
  },
  {
    id: "bird",
    num: "193",
    name: "Bird",
    category: "Media",
    fileName: "bird-icon",
    componentName: "BirdIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BirdIcon,
    baseDuration: 0.55,
  },
  {
    id: "paintbrush",
    num: "194",
    name: "Paintbrush",
    category: "Interface",
    fileName: "paintbrush-icon",
    componentName: "PaintbrushIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PaintbrushIcon,
    baseDuration: 0.6,
  },
  {
    id: "megaphone",
    num: "195",
    name: "Megaphone",
    category: "Interface",
    fileName: "megaphone-icon",
    componentName: "MegaphoneIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: MegaphoneIcon,
    baseDuration: 0.5,
  },
  {
    id: "archive",
    num: "196",
    name: "Archive",
    category: "Interface",
    fileName: "archive-icon",
    componentName: "ArchiveIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ArchiveIcon,
    baseDuration: 0.55,
  },
  {
    id: "syringe",
    num: "197",
    name: "Syringe",
    category: "Essentials",
    fileName: "syringe-icon",
    componentName: "SyringeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SyringeIcon,
    baseDuration: 0.45,
  },
  {
    id: "bomb",
    num: "198",
    name: "Bomb",
    category: "Media",
    fileName: "bomb-icon",
    componentName: "BombIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BombIcon,
    baseDuration: 0.5,
  },
  {
    id: "shell",
    num: "199",
    name: "Shell",
    category: "Essentials",
    fileName: "shell-icon",
    componentName: "ShellIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShellIcon,
    baseDuration: 0.6,
  },
  {
    id: "infinity",
    num: "200",
    name: "Infinity",
    category: "Development",
    fileName: "infinity-icon",
    componentName: "InfinityIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: InfinityIcon,
    baseDuration: 0.9,
  },
  {
    id: "car",
    num: "201",
    name: "Car",
    category: "Essentials",
    fileName: "car-icon",
    componentName: "CarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CarIcon,
    baseDuration: 0.55,
  },
  {
    id: "shuffle",
    num: "202",
    name: "Shuffle",
    category: "Development",
    fileName: "shuffle-icon",
    componentName: "ShuffleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShuffleIcon,
    baseDuration: 0.6,
  },
  {
    id: "cooking-pot",
    num: "203",
    name: "Cooking Pot",
    category: "Essentials",
    fileName: "cooking-pot-icon",
    componentName: "CookingPotIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CookingPotIcon,
    baseDuration: 0.55,
  },
  {
    id: "box",
    num: "204",
    name: "Box",
    category: "Essentials",
    fileName: "box-icon",
    componentName: "BoxIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BoxIcon,
    baseDuration: 0.55,
  },
  {
    id: "fish",
    num: "205",
    name: "Fish",
    category: "Media",
    fileName: "fish-icon",
    componentName: "FishIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: FishIcon,
    baseDuration: 0.6,
  },
  {
    id: "dna",
    num: "206",
    name: "DNA",
    category: "Development",
    fileName: "dna-icon",
    componentName: "DnaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DnaIcon,
    baseDuration: 0.7,
  },
  {
    id: "highlighter",
    num: "207",
    name: "Highlighter",
    category: "Interface",
    fileName: "highlighter-icon",
    componentName: "HighlighterIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HighlighterIcon,
    baseDuration: 0.6,
  },
  {
    id: "eraser",
    num: "208",
    name: "Eraser",
    category: "Interface",
    fileName: "eraser-icon",
    componentName: "EraserIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: EraserIcon,
    baseDuration: 0.5,
  },
  {
    id: "tree-deciduous",
    num: "209",
    name: "Tree Deciduous",
    category: "Essentials",
    fileName: "tree-deciduous-icon",
    componentName: "TreeDeciduousIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TreeDeciduousIcon,
    baseDuration: 0.6,
  },
  {
    id: "orbit",
    num: "210",
    name: "Orbit",
    category: "Development",
    fileName: "orbit-icon",
    componentName: "OrbitIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: OrbitIcon,
    baseDuration: 1.2,
  },
  {
    id: "git-commit",
    num: "211",
    name: "Git Commit",
    category: "Development",
    fileName: "git-commit-icon",
    componentName: "GitCommitIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GitCommitIcon,
    baseDuration: 0.6,
  },
  {
    id: "shapes",
    num: "212",
    name: "Shapes",
    category: "Interface",
    fileName: "shapes-icon",
    componentName: "ShapesIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ShapesIcon,
    baseDuration: 0.55,
  },
  {
    id: "sofa",
    num: "213",
    name: "Sofa",
    category: "Essentials",
    fileName: "sofa-icon",
    componentName: "SofaIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SofaIcon,
    baseDuration: 0.55,
  },
  {
    id: "bed",
    num: "214",
    name: "Bed",
    category: "Essentials",
    fileName: "bed-icon",
    componentName: "BedIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BedIcon,
    baseDuration: 0.55,
  },
  {
    id: "door-open",
    num: "215",
    name: "Door Open",
    category: "Interface",
    fileName: "door-open-icon",
    componentName: "DoorOpenIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: DoorOpenIcon,
    baseDuration: 0.6,
  },
  {
    id: "recycle",
    num: "216",
    name: "Recycle",
    category: "Development",
    fileName: "recycle-icon",
    componentName: "RecycleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: RecycleIcon,
    baseDuration: 0.65,
  },
  {
    id: "grape",
    num: "217",
    name: "Grape",
    category: "Essentials",
    fileName: "grape-icon",
    componentName: "GrapeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: GrapeIcon,
    baseDuration: 0.55,
  },
  {
    id: "apple",
    num: "218",
    name: "Apple",
    category: "Essentials",
    fileName: "apple-icon",
    componentName: "AppleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: AppleIcon,
    baseDuration: 0.55,
  },
  {
    id: "pen",
    num: "219",
    name: "Pen",
    category: "Interface",
    fileName: "pen-icon",
    componentName: "PenIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: PenIcon,
    baseDuration: 0.5,
  },
  {
    id: "stamp",
    num: "220",
    name: "Stamp",
    category: "Interface",
    fileName: "stamp-icon",
    componentName: "StampIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: StampIcon,
    baseDuration: 0.5,
  },
  {
    id: "armchair",
    num: "221",
    name: "Armchair",
    category: "Essentials",
    fileName: "armchair-icon",
    componentName: "ArmchairIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ArmchairIcon,
    baseDuration: 0.55,
  },
  {
    id: "layout-dashboard",
    num: "222",
    name: "Layout Dashboard",
    category: "Interface",
    fileName: "layout-dashboard-icon",
    componentName: "LayoutDashboardIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: LayoutDashboardIcon,
    baseDuration: 0.55,
  },
  {
    id: "signal",
    num: "223",
    name: "Signal",
    category: "Media",
    fileName: "signal-icon",
    componentName: "SignalIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: SignalIcon,
    baseDuration: 0.55,
  },
  {
    id: "stethoscope",
    num: "224",
    name: "Stethoscope",
    category: "Essentials",
    fileName: "stethoscope-icon",
    componentName: "StethoscopeIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: StethoscopeIcon,
    baseDuration: 0.6,
  },
  {
    id: "heart-pulse",
    num: "225",
    name: "Heart Pulse",
    category: "Essentials",
    fileName: "heart-pulse-icon",
    componentName: "HeartPulseIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: HeartPulseIcon,
    baseDuration: 0.5,
  },
  {
    id: "thermometer",
    num: "226",
    name: "Thermometer",
    category: "Essentials",
    fileName: "thermometer-icon",
    componentName: "ThermometerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ThermometerIcon,
    baseDuration: 0.7,
  },
  {
    id: "ear",
    num: "227",
    name: "Ear",
    category: "Essentials",
    fileName: "ear-icon",
    componentName: "EarIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: EarIcon,
    baseDuration: 0.6,
  },
  {
    id: "bath",
    num: "228",
    name: "Bath",
    category: "Essentials",
    fileName: "bath-icon",
    componentName: "BathIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: BathIcon,
    baseDuration: 0.6,
  },
  {
    id: "timer",
    num: "229",
    name: "Timer",
    category: "Interface",
    fileName: "timer-icon",
    componentName: "TimerIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: TimerIcon,
    baseDuration: 0.5,
  },
  {
    id: "scale",
    num: "230",
    name: "Scale",
    category: "Essentials",
    fileName: "scale-icon",
    componentName: "ScaleIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: ScaleIcon,
    baseDuration: 0.6,
  },
  {
    id: "candy",
    num: "231",
    name: "Candy",
    category: "Essentials",
    fileName: "candy-icon",
    componentName: "CandyIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CandyIcon,
    baseDuration: 0.55,
  },
  {
    id: "croissant",
    num: "232",
    name: "Croissant",
    category: "Essentials",
    fileName: "croissant-icon",
    componentName: "CroissantIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: CroissantIcon,
    baseDuration: 0.6,
  },
  {
    id: "utensils-crossed",
    num: "233",
    name: "Utensils Crossed",
    category: "Essentials",
    fileName: "utensils-crossed-icon",
    componentName: "UtensilsCrossedIcon",
    defaultConfig: { color: "#18181b", speed: 1, size: 48 },
    Component: UtensilsCrossedIcon,
    baseDuration: 0.55,
  },
];

export const CATEGORIES = [
  "All icons",
  ...Array.from(new Set(ICON_LIST.map((i) => i.category))),
];
